### ISSUE TITLE
Task: Investigate alphabetizing suite.test / main.go and cleaning files

### ISSUE THREAD

**Issue by melonrush13** [Azure/azure-service-operator#1008]
Suite.test and Main.go have turned into very long files because of the # of operators we have. 
It would be great if we could figure out a way to declare differently so we don't have to have a long repetitive list.

Either that, or figure out a way to alphabetize the list of operators so it isn't as messy.

**Done criteria**
- Investigate the following methods
- Alphabetize the list of operators in suite.test/main.go
- Or: redeclare operators in more efficient manner.

**User story reference**

#<issue number of the user story that this task accrues to>

**Comment by matthchr** [comment]
Closing this - This will be improved as part of the code generation effort.
