### ISSUE TITLE
Task: Consolidate docs to be more concise and readable (merge helm readme)

### ISSUE THREAD

**Issue by jananivMS** [Azure/azure-service-operator#1023]
Currently the docs seem to have multiple ways of doing the same thing. We shoudl consolidate this and also make sure managed identity config is more front and center. Also helm readme needs to be consolidated.

**Done criteria**
This is the "done" criteria for this task

- [ ] Docs are concise and dont have repetitions for managed identity config
- [ ] Helm deploy of operator is the mainly documented way to install operator

**Comment by sakthi-vetrivel** [comment]
This has been completed.
