### ISSUE TITLE
Task: Fix transient failures in EventHub Controller test with Secrets & re-enable test

### ISSUE THREAD

**Issue by dkisselev** [Azure/azure-service-operator#1026]
#1016 disabled an EventHub controller test due to unreproducible build errors (investigated in #1015).

This task is just a reminder to continue watching that issue and re-enable (or fully remove) the test at a future date.

Marked as a task as it does not seem to be a bug in the actual operator.

**Comment by matthchr** [comment]
Closing given that V1 is in maintenance mode.
