### ISSUE TITLE
Bug: VM Operator should check if the VM is in 'Running' state and return successful resource provisioned status

### ISSUE THREAD

**Issue by huangpf** [Azure/azure-service-operator#1089]
**Describe the bug**
VM Operator should check if the VM is in 'Running' state and return successful resource provisioned status.

**To Reproduce**
Simply create a VM using the operator and observe how quick it's declared successfully provisioned.

**Expected behavior**
The VM should be in 'Running' state when the status above is declared.

**Screenshots**
```
11379 ± k get AzureVirtualMachine                                                                                                                                     ✹ ✭
NAME                PROVISIONED   MESSAGE
rg-vmextestin-vm3   true          successfully provisioned

that is 4 seconds from creation...you want the operator to reconcile until "Running" then set success
```

**Additional context**
Probably also applies to VMSS operator which is pending on further check.

A potential fix prototype could look like this:
https://github.com/Azure/azure-service-operator/blob/master/pkg/resourcemanager/vm/reconcile.go#L54
```
if err == nil {
    if (someProvisioningState == "Running") {
        instance.Status.Provisioned = true
        instance.Status.Provisioning = false
        instance.Status.Message = resourcemanager.SuccessMsg
        instance.Status.ResourceId = *item.ID
        return true, nil
    }
    else {
        // otherwise
        return false, nil
    }
}
```

**Comment by huangpf** [comment]
Hi Admin -- please help assign this issue to me. :-)

**Comment by huangpf** [comment]
Assign it to @haagha from the CPlat SDK Core team.

**Comment by haagha** [comment]
PR https://github.com/Azure/azure-service-operator/pull/1222

**Comment by haagha** [comment]
Can we close this issue? PR is merged

**Comment by matthchr** [comment]
Closing based on above
