### ISSUE TITLE
Task: Add support for configuring labels as tags for PSQL and cosmos db

### ISSUE THREAD

**Issue by jananivMS** [Azure/azure-service-operator#1091]
Need to add support for adding labels as tags to PSQL and MySQL server for customer 

**Done criteria**
This is the "done" criteria for this task

- [ ] Labels in Yaml can be translated to Tags for Postgresql and cosmos db

**Comment by frodopwns** [comment]
both are supported already...looks like the sample files just don't have a labels section like some others do
