### ISSUE TITLE
Enhancement: Update the SDK version in Azure SQL operators to v3.0

### ISSUE THREAD

**Issue by WilliamMortlMicrosoft** [Azure/azure-service-operator#1118]
Currently all Azure SQL operators use the 2015 version of the Azure SQL management SDK. Adding support for retention policies to Azure SQL databases required co-mingling the v3.0 version (this is the latest version) of the SDK with the older 2015 version.

Going forward, we should move completely to the v3.0 of the SDK, and remove all references to the 2015 sdk.

The difficulty is that this probably will not be a simple update as method names / call signatures / structs have seeming changed in some cases since 2015. Consider this to be a sizeable PR that will take 1 or more sprints.

**Comment by matthchr** [comment]
This is solved by how we do versioning in ASOv2. Closing.
