### ISSUE TITLE
Task: Investigate and to do:  How Azure manage the users within cosmosDB (using mongo API) and whether service operator can support this.

### ISSUE THREAD

**Issue by buhongw7583c** [Azure/azure-service-operator#1121]

**Comment by jpflueger** [comment]
@buhongw7583c It is currently not possible to manage users for Mongo 3.6 in CosmosDB. [Here's a link to the docs](https://docs.microsoft.com/en-us/azure/cosmos-db/mongodb-feature-support-36#user-and-role-management). I tried to do it anyways just to verify. You can see the error if you connect to a CosmosDB account with MongoDB 3.6 API and try to create a user:
```
globaldb:PRIMARY> db.createUser({ user: "justin", pwd: "football" })
2020-06-04T14:06:43.495-0600 E  QUERY    [js] uncaught exception: Error: couldn't add user: Command createUser not supported. :
_getErrorWithCode@src/mongo/shell/utils.js:25:13
DB.prototype.createUser@src/mongo/shell/db.js:1370:11
```

You can manage users using the CoreSQL API but currently that is the only API with support for users. There are some security recommendations in the docs that recommend using Managed Identity to control access to CosmosDB resources [here](https://docs.microsoft.com/en-us/azure/cosmos-db/how-to-restrict-user-data). Another thing we could do is add an "Action" similar to Azure SQL and Redis Cache to be able to roll the account keys. 

We can keep the conversation going here but I think this ticket should be closed and we should look at other avenues for securing access, if that is the primary concern.
