### ISSUE TITLE
Task: Update kubebuilder install make target to install 2.3.1 version and update docs to refer to the make target

### ISSUE THREAD

**Issue by jananivMS** [Azure/azure-service-operator#1128]
We have different parts in the project - make target and docs - specify different versions of Kubebuilder. We should update this to be all v 2.3.1 to be consistent.

**Done criteria**
This is the "done" criteria for this task

- [ ] Make target for install-kubebuilder and the docs all rrefer to installing kubebuilder v 2.3.1

**Comment by matthchr** [comment]
This is done now
