### ISSUE TITLE
Task: Create happy path test for ApimService

### ISSUE THREAD

**Issue by melonrush13** [Azure/azure-service-operator#1134]
NOTE: The creation of APIMService takes too long (more than 60 mins), so this is impractical. to add a test for. We should evaluate this carefully if this really adds value.

----------------
Currently we have no tests in the controller for ApimService

**Done criteria**
Create a happy path test in the controller for ApimService
`apimservice_controller_test.go`

**User story reference**

#<issue number of the user story that this task accrues to>

**Comment by Porges** [comment]
Specific to v1, will not apply to v2.
