### ISSUE TITLE
Task: Separate KeyVault Key and KeyVault CRDs logic

### ISSUE THREAD

**Issue by melonrush13** [Azure/azure-service-operator#1135]
Please see this [doc](https://github.com/Azure/azure-service-operator/edit/master/docs/howto/newoperatorguide.md) for information on how we organize our operators logic - specifically, Step 8b. 

We want to ensure all CRDs are following this workflow, as it is the new standard going forward.

Currently, KeyVault and KeyVault Key are not following this worfklow.

We should separate the logic for KeyVault and KeyVault Key as they are two seperate operators, as well as follow our folder hierarchies from the above documentation.

**Done criteria**
- Seperate logic for the following CRDS: KeyVault and KeyVaultKey
- Organize into appropriate folder hierarchies for pkg/resourcemanager/keyvault

Please create a new issue for any other CRDs you see not following this pattern.

**Comment by matthchr** [comment]
ASO v1 is in maintenance mode and this isn't a critical bug, so closing it.
