### ISSUE TITLE
Task: Update makefile to use "kubectl kustomize"

### ISSUE THREAD

**Issue by jpflueger** [Azure/azure-service-operator#1136]
When we install kubebuilder, it comes with kubectl version 1.14.X. Since 1.14.X kubectl comes with a kustomize sub-command `kubectl kustomize`. We should be able to use this kustomize command instead of installing a stand alone version of kustomize to remove an install/setup step. 

**Done criteria**
This is the "done" criteria for this task

- [ ] Makefile defaults to use `kubectl kustomize` instead of `kustomize build`
- [ ] Makefile allows overriding the kustomize command so users can use a specific version if necessary
- [ ] Update documentation to reflect one less setup step

**Comment by matthchr** [comment]
Closing this as no longer applicable
