### ISSUE TITLE
Task: Retry auto assigning ip for Redis in vnet if race condition occurs

### ISSUE THREAD

**Issue by frodopwns** [Azure/azure-service-operator#1145]
If a user places a RedisCache in a VNET and leaves StaticIP empty, the operator will attempt to grab an available ip. This happens within a second or 2 of binding to that ip but it is possible that another service could take it. In this case we want to try another ip rather than failing completely.

**Done criteria**
Auto assign avoids race condition and tries new ip.

This should not affect requests that define an ip explicitly. Those requests should still fail if their ip is not available.

**Comment by matthchr** [comment]
ASO v1 is in maintenance mode and this will likely not be fixed there. ASO v2 supports Redis but doesn't perform auto-assigning IPs and so this issue doesn't apply there. Going to close this.
