### ISSUE TITLE
Optimization MySQLUser service: use a common function for duplicated codes in mysqlusers.go. 

### ISSUE THREAD

**Issue by buhongw7583c** [Azure/azure-service-operator#1146]
Use a common function to return the adminsecret and usersecret in mysqluser_reconcile.go and psqluser_reconcile.go.  

e.g. in psqluser_reconcile.go Ensure(), the lines of code 
https://github.com/Azure/azure-service-operator/blob/d0294e15530da5a40bb42e82ce60a01213188551/pkg/resourcemanager/psql/psqluser/psqluser_reconcile.go#L44-L74

are the same as in Delete(). 
https://github.com/Azure/azure-service-operator/blob/d0294e15530da5a40bb42e82ce60a01213188551/pkg/resourcemanager/psql/psqluser/psqluser_reconcile.go#L200-L228

These lines of code could be subtracted as a common function, e.g. GetAdminSecret, GetUserSecret. 
The same applies for mysqluser_reconcile.go. 

**Done criteria**
- [ ] A common function to return the adminsecret and usersecret in mysqluser_reconcile.go
- [ ] A common function to return the adminsecret and usersecret in psqluser_reconcile.go.

**Comment by matthchr** [comment]
This has been done
