### ISSUE TITLE
Task: investigate to use sql db for SQL commands in MySQLUser and PostgreSQLUser. 

### ISSUE THREAD

**Issue by buhongw7583c** [Azure/azure-service-operator#1147]
In MySQLUser and PostgreSQLUser, there are several SQL commands using SQL injections. 
e.g. in https://github.com/Azure/azure-service-operator/blob/d0294e15530da5a40bb42e82ce60a01213188551/pkg/resourcemanager/psql/psqluser/psqluser.go#L124

The reason using the SQL injection for MySQLUser and PostgreSQLUser SQL commands is the db.exec() provided by database/sql packages cannot executed and accepted by MySQL and PostgreSQL. 
It worth doing an investigation to see whether we can use database/sql db functions to execute the SQL Commands. 

Reference  document: https://www.calhoun.io/what-is-sql-injection-and-how-do-i-avoid-it-in-go/. . 

**Done criteria**
This is the "done" criteria for this task

- [ ] Investigate whether the MySQLUser's createuser, GrantUserRoles, DropUser command can use db.Exec to execute instead of SQL injection. 
- [ ] Investigate whether PostgreSQLUser's createuser, GrantUserRoles, DropUser commands can use db.Exec to execute instead of SQL injection.

**Comment by davefellows** [comment]
Have you got an example of the code you've tried and the error you're hitting?

Not sure if this is relevant:
https://stackoverflow.com/questions/50206617/db-exec-args-always-results-in-an-error-for-my-placeholder

**Comment by buhongw7583c** [comment]
@davefellows, Dave, for example, the mysql command for drop user is
```
 DROP USER 'username'@'servername';
```
We at first used the db.exec to run. 
```

	tsql := "DROP USER ?"
        user:= string("'username'@'servername'")
	_, err := db.ExecContext(ctx, tsql, user)
```
Then the error 
```
You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '?' at line 1
```
Yeah, worth checking your referred document.

**Comment by buhongw7583c** [comment]
Add the result from a quick test: 
using the 'interpolateParams' set to true for mysql db connection and the db.exec works for create user and drop user. User could be added/deleted without error. 
@davefellows , great finding of the document! There should be similar one for postgresql and sql for go as well. 
```
       //connection to mysql server
        var connectionString = fmt.Sprintf("%s:%s@tcp(%s:3306)/%s?tls=skip-verify&interpolateParams=true", user, password, host, database)

	// Initialize connection object.
	db, err := sql.Open("mysql", connectionString)
	checkError(err)
	defer db.Close()

	err = db.Ping()
	checkError(err)
	fmt.Println("Successfully created connection to database.")

        //create user
        tsql := "create user ?@? identified by ?"
        res, err := db.Exec(tsql, string(username), string(server), string(password))
	checkError(err)
	rowCount, err := res.RowsAffected()
	fmt.Printf("Inserted %d row(s) of data.\n", rowCount)

       //drop user
       	tsql := "drop user ?@?"
	res, err := db.Exec(tsql, string(username), string(server))
	checkError(err)
	rowCount, err := res.RowsAffected()
	fmt.Printf("Inserted %d row(s) of data.\n", rowCount)
```

**Comment by buhongw7583c** [comment]
Update On Jun16/2020: 
The newly created PR https://github.com/Azure/azure-service-operator/pull/1160 fixed the SQL injection for MySQL CreateUser and DropUser. The left issue is for GrantUser, 
https://github.com/Azure/azure-service-operator/blob/078ea90f7e67f04863dfa55c3862a7f82da54124/pkg/resourcemanager/mysql/mysqluser/mysqluser.go#L88
Even with the InterpolateParams parameter set to TRUE, the SQL injection for the grant user command will always result to error: 
``` You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '?' at line 1```

**Comment by matthchr** [comment]
I've done a bit of additional looking into this issue - here's the comment I've added to the code at least for mysql:

```
		// Due to how go-mysql-driver performs parameter replacement, it always wraps
		// string parameters in ''. That doesn't work for this query because some of
		// our parameters are actually SQL keywords or identifiers (surrounded by backticks). Admittedly
		// protecting against SQL injection here is probably pointless as we're giving the caller
		// permission to create users, which means there's nothing stopping them from creating
		// an administrator user and then doing whatever they want without SQL injection.
		// See https://github.com/go-sql-driver/mysql/blob/3b935426341bc5d229eafd936e4f4240da027ccd/connection.go#L198
		// for specifics of what go-mysql-driver supports.
                tsql := fmt.Sprintf("GRANT %s ON `%s`.* TO '%s'", role, database, user)
```

**Comment by matthchr** [comment]
@babbageclunk I see the comment I had added at one point I think is removed and I know you refactored this some #1362 - is this fixed now? My cursory glance through the code suggests that the `user` is now being managed via the SQL library parameter replacement (and so is safe), but the `role` and `database` fields aren't protected.

Should we revive my comment (or some part of it?)

**Comment by matthchr** [comment]
I've revisited this and confirmed that there are still areas for improvement.

We're still using `DROP USER %s` in PSQL and AzureSQL (mySQL is `DROP USER ?` which is correct).
`GRANT` is also still using `%s` although that may not be avoidable.

We should think about this as we design these resources for ASO v2.

**Comment by matthchr** [comment]
Closing this as it's about ASOv1.
