### ISSUE TITLE
Feature: Support Microsoft.Cdn resources

### ISSUE THREAD

**Issue by frodopwns** [Azure/azure-service-operator#1150]
The portal allows users to configure a Storage Account to enable CDN for files stored within blob containers. Come up with a way to mimic this functionality in ASO.

**Done criteria**
CDN can be enabled for Storage Accounts.

**Comment by theunrepentantgeek** [comment]
At first inspection, it appears this just requires support for the `microsoft.cdn` resource type.

For an ARM template example, see https://docs.microsoft.com/en-us/azure/cdn/create-profile-endpoint-template

**Comment by matthchr** [comment]
Confirmed that this is just the `Microsoft.cdn` `profile` and `profile/endpoint` resource. Have updated the issue title and labels accordingly
