### ISSUE TITLE
Task: Rename storage account secret name 

### ISSUE THREAD

**Issue by melonrush13** [Azure/azure-service-operator#1152]
Currently, the storage account secret displays as the following when doing a `k get secret` 

```
10471 ± k get secret                                                                                                                                                
NAME                                           TYPE                                  DATA   AGE                                5      96m
storageaccount-rg-expotest-dev-saexpotestdev   Opaque                                5      93m
erins-MBP ॐ  ~/go/src/github.com/frodopwns/exposure-notifications-server/examples/aso-dev-deploy:(18h1m|git@chartdraft!)

10472 ± k get storageaccount                                                                                                                                        
NAME            PROVISIONED   MESSAGE
saexpotestdev   true          successfully provisioned
```

We should rename the secret `storageaccount-rg-expotest-dev-saexpotestdev ` to the standard naming convention across controllers for secrets, or something more declarative.

**Done criteria**
Rename the name of the storage account secret to the standard naming convention across containers.

- [ ] For eg. After this task is done, the user should be able to use either webhooks or the declarative model for K8s

**User story reference**

#<issue number of the user story that this task accrues to>

**Comment by matthchr** [comment]
This has been fixed by #1358
