### ISSUE TITLE
Bug: Operator fails to start (port 433) when PodSecurity or SCC is enabled on the cluster

### ISSUE THREAD

**Issue by lenisha** [Azure/azure-service-operator#1177]
**Describe the bug**
When running operator in environment where Pod Security Policy or SCC in OpenShift are enabled , operator pod crashes as it can't bind to privileged port
```
2020-06-22T13:23:53.834Z         INFO          controller-runtime.controller  Starting EventSource                   {"controller": "resourcegroup", "source": "kind source: /, Kind="}
2020-06-22T13:23:53.834Z         ERROR       setup         problem running manager         {"error": "listen tcp :443: bind: permission denied"}
github.com/go-logr/zapr.(*zapLogger).Error
                    /go/pkg/mod/github.com/go-logr/zapr@v0.1.0/zapr.go:128
main.main
                    /workspace/main.go:790
runtime.main
                    /usr/local/go/src/runtime/proc.go:203

```

**Expected behavior**
Expected Operator to use port > 1024 range and run in non-privilege mode

**Comment by madorn** [comment]
@lenisha If not specified, controller-runtime sets default webhook port to 443: https://github.com/kubernetes-sigs/controller-runtime/blob/master/pkg/webhook/server.go#L49-L51

@joelanford has opened an issue here: https://github.com/kubernetes-sigs/controller-runtime/issues/1018

kubebuilder has been scaffolding main.go to default the webhook server port to 9443: https://github.com/kubernetes-sigs/kubebuilder/commit/7af89cb00c224c57ece37dc14ea37caf1eb769db

Azure Service Operator could set it here: https://github.com/Azure/azure-service-operator/blob/master/main.go#L116-L122
and update kustomize webook scaffolds to use that port.
