### ISSUE TITLE
Feature: Do not use cert manager on OpenShift

### ISSUE THREAD

**Issue by lenisha** [Azure/azure-service-operator#1179]
<Describe what the task is about>
OpenShift cluster has built in features to issue and manage certificates
 https://docs.openshift.com/container-platform/4.3/authentication/certificates/service-serving-certificate.html

Allow configuration to switch from using cert manager to OpenShift native cert management.

**Comment by madorn** [comment]
Deploying on OpenShift without cert-manager addressed here: https://github.com/Azure/azure-service-operator/issues/1257

**Comment by babbageclunk** [comment]
The v1 operator bundle uses the OpenShift certificate handling now, rather than trying to use cert-manager. (v2 isn't bundled yet but will do the same when it is.)
