### ISSUE TITLE
Task: Investigate improving optional/required annotations and types

### ISSUE THREAD

**Issue by matthchr** [Azure/azure-service-operator#1182]
The optionality of various fields is not always correct (in the Go types or the generated CRDs).

For example if you look at [event hub Destination](https://github.com/Azure/azure-service-operator/blob/master/api/v1alpha1/eventhub_types.go#L58) you can see the `StorageAccount` field is marked `omitempty` and optional, but is a value type (not a pointer).

This causes the innards of `EventHubStorageAccount` to be optional as well, even though in reality both the `ResourceGroup` and `AccountName` fields are required.

We should investigate doing a pass through some of the types to fix issues like this one

**Done criteria**
- Types more closely represent what is allowed (optional/required, along with associated kubebuilder annotations)

**Comment by babbageclunk** [comment]
This is fixed in v2 (to the degree that the swagger is right).
