### ISSUE TITLE
Allow support for Private Endpoints

### ISSUE THREAD

**Issue by mkosieradzki** [Azure/azure-service-operator#1186]
Users should be able to create service, e.g. database, storage account or key vault together with a private endpoint. Private DNS zone should be created, integrated with the private endpoint and associated with cluster vnet.

This CRD extension should expose an annotation that will trigger creation of a Network Policy rule allowing egress connectivity to this private endpoint IP addresses to all pods (or custom selector) in the namespace owning the resource.

**Comment by matthchr** [comment]
Redis should be included in the above list as well

**Comment by matthchr** [comment]
This seems very similar to #2159.

**Comment by theunrepentantgeek** [comment]
This should be unblocked now that #2323 has been merged; I'll self assign with an aim of doing this post `beta.4`.

**Comment by super-harsh** [comment]
closed by #2733
