### ISSUE TITLE
Value proposition over Crossplane

### ISSUE THREAD

**Issue by mkosieradzki** [Azure/azure-service-operator#1190]
I am having really hard time understanding what is the goal of this project and how does it differ from crossplane.io despite this one is Azure-only and is not OAM-compatible… I am obviously missing something. What am I missing?

**Comment by frodopwns** [comment]
Your confusion is understandable!

We aren't claiming a value proposition over Crossplane but we do think the service management should be the cloud provider's responsibility and Crossplane should remain the abstraction layer. For this reason we will be looking at ways to shim ASO into Crossplane to allow them to shift this responsibility to us.

**Comment by mkosieradzki** [comment]
Thanks, this makes a lot of sense and might allow to provide updated resource APIs faster.

**Comment by bassam** [comment]
(disclosure: I'm a crossplane maintainer)

We are working with Microsoft on getting the two projects closer together - we agree that the community benefits from a converged effort here 🚀

**Comment by sakthi-vetrivel** [comment]
Closing this issue as we continue to engage with Crossplane on tracking these project closer together moving forward.
