### ISSUE TITLE
Task: Add liveness/readiness probes

### ISSUE THREAD

**Issue by frodopwns** [Azure/azure-service-operator#1201]
The initial health checking probe was removed in #1198 to avoid issues where the Kubelet could not connect to the health endpoint on some clusters. The initial check was only doing a naive check anyway. We should regroup and investigate what these endpoints should actually do in order to ensure the operator is functioning and the reintroduce the code changes.

**Comment by babbageclunk** [comment]
We should check how to do this in controller-runtime and whether we can add custom health logic.

**Comment by matthchr** [comment]
We still think this is worth investigating. @super-harsh was looking at this some
