### ISSUE TITLE
Add example/quickstart for Azure Event Hubs

### ISSUE THREAD

**Issue by abhirockzz** [Azure/azure-service-operator#1207]
**Describe the current behavior**

I noticed that there are ready-to-use examples/references for using ASO with [Azure Redis Cache](https://github.com/Azure/azure-service-operator/blob/master/examples/demo/azure-vote-app-redis.yaml) and a nice demo for [Azure SQL Server](https://github.com/Azure/azure-service-operator/blob/master/docs/services/azuresql/azuresql.md#demo)

Don't see such resources for for Azure Event Hubs

**Describe the improvement**

It would be great to have a quickstart guide for Azure Event Hubs to complement the following resources the [standard doc](https://github.com/Azure/azure-service-operator/blob/master/docs/services/eventhub/eventhub.md) and sample YAMLs.

**Additional context**

If this sounds like a good idea, I would be happy to help!

**Comment by abhirockzz** [comment]
Hello @sakthi-vetrivel , just checking to see if this is something I can help with adding [here](https://github.com/Azure/azure-service-operator/blob/master/docs/services/eventhub/eventhub.md)?

**Comment by sakthi-vetrivel** [comment]
@abhirockzz  Absolutely! Feel free to get started - might take me a while to get to this one :)
