### ISSUE TITLE
Support for "tags"

### ISSUE THREAD

**Issue by abhirockzz** [Azure/azure-service-operator#1210]
**Describe the current behavior**

All Azure resources allow "tags", but I see this is not possible in ASO CRDs. For e.g. I was creating a Resource Group via ASO and it failed since our subscription has a policy which looks for a tag.

**Describe the improvement**

Allow tags to be added to Azure resources created via ASO

**Additional context**
NA

**Comment by Porges** [comment]
This is addressed in codegen controller.

**Comment by theunrepentantgeek** [comment]
Tags are supported from the [v2.0.0-alpha.0](https://github.com/Azure/azure-service-operator/releases/tag/v2.0.0-alpha.0) release of the operator. 

Please have a go and let us know how you get on.
