### ISSUE TITLE
Pipeline: Make the step of selecting an available AKS cluster in the pipeline more robust

### ISSUE THREAD

**Issue by jananivMS** [Azure/azure-service-operator#1213]
**Describe the current behavior**
Currently the step to choose a free AKS cluster to run the pipeline deploy stage on, chooses an AKS cluster and connects to it, However, this step seems to fail on some runs because another pipeline run might have selected this cluster and executed a command on it. 
Below is an example run showing this issue.
 https://dev.azure.com/azure/azure-service-operator/_build/results?buildId=11562&view=logs&j=12f1170f-54f2-53f3-20dd-22fc7dff55f9&t=ed51bc88-ea39-56fb-53bb-66c4adef626f

**Describe the improvement**
The stage should be updated to make it more robust so we can pick another AKS cluster if this one is not available or has been chosen by another pipeline run. It seems to be a race condition so needs better handling.

**Additional context**
Add any other context about the suggested improvement.

**Comment by matthchr** [comment]
We're not investing in improving this pipeline as it's part of ASOv1 which is in maintenance mode.
