### ISSUE TITLE
Improve auto IP assignment of RedisCache CRD

### ISSUE THREAD

**Issue by matthchr** [Azure/azure-service-operator#1227]
**Describe the improvement**
RedisCache CRD: For auto IP assignment.  If the first selected IP is taken, Controller should automatically retry with next available IP instead of failing the RedisCRD.  This makes the CRD more convenient.

**Comment by theunrepentantgeek** [comment]
ASO v1 is currently in maintenance mode, and this is not functionality that we're considering for ASO v2.
