### ISSUE TITLE
Feature: Add AzureManagedIdentity CRD

### ISSUE THREAD

**Issue by matthchr** [Azure/azure-service-operator#1228]
Add a CRD for AzureManagedIdentity to help us create them in a declarative way like other Azure resources.

**Comment by sakthi-vetrivel** [comment]
Will be included as a part of the auto-generation effort mentioned in #1192

**Comment by matthchr** [comment]
This was released as part of [ASO v2-alpha2](https://github.com/Azure/azure-service-operator/releases/tag/v2.0.0-alpha.1) - `UserAssignedIdentity`.
