### ISSUE TITLE
Default location and resource group

### ISSUE THREAD

**Issue by kyschouv** [Azure/azure-service-operator#1237]
Is it possible to set a default location and resource group? It seems like location can perhaps be specified with `AZURE_LOCATION_DEFAULT`, but I couldn't find anything for default resource group, and `AZURE_LOCATION_DEFAULT` doesn't seem to be settable through the helm chart.. It would be very helpful for our use case to be able to set defaults for these, such that our own charts/deployments don't need to be resource group or location aware.

As an example, we might deploy an ASP.NET Core application, and would like an Application Insights resource deployed with it. We'd want that Application Insights resource to be in the same location as the nodes the application pods run on, but our application doesn't need to be too aware of where the actual resource is created or managed.

**Comment by theunrepentantgeek** [comment]
As discussed in#1247, we don't think ASO is the right place for this kind of control.
