### ISSUE TITLE
Feature: Schedule Community calls to engage with the community

### ISSUE THREAD

**Issue by nmeisenzahl** [Azure/azure-service-operator#1240]
Not a real feature request. 

It would be nice if the team could engage with the community via a community call (maybe monthly). Demoing new features, share feature ideas and roadmap and gather feedback are only some possible ideas.

**Comment by sakthi-vetrivel** [comment]
@nmeisenzahl Yup, this is something we've been discussing as well. We're hoping to get started in the next month.

**Comment by sakthi-vetrivel** [comment]
Monthly community call scheduled for the first Wednesday of every month at 4 PM (PST). Details here: https://docs.google.com/document/d/1MEx5W8X_BwxvVJ4NRfgublQJ2sTrw5dSqrJ8Z4YxV94/edit?usp=sharing

**Comment by nmeisenzahl** [comment]
@sakthi-vetrivel thanks for making this happen and for the feedback. Unfortunately, I don't think this will work for me. It is 2 am my time (Germany). Are there any plans to share the recording?
