### ISSUE TITLE
Improve the way Provisioning, FailedProvisioning, Provisioned booleans are managed

### ISSUE THREAD

**Issue by matthchr** [Azure/azure-service-operator#1243]
**Describe the current behavior**
`FailedProvisioning`, `Provisioning`, `Message`, `Provisioned` are all related to one another. We should consider a helper method/class to manage these in a way that is less error prone.

Long term we may want to consider an alternative enum or something which more correctly represents valid scenarios.

**Comment by theunrepentantgeek** [comment]
ASO v1 is in maintenance mode and won't be changed.
This is addressed in v2.
