### ISSUE TITLE
Adding Extension to PostgresSQLDB using Azure-Operator : timescaledb extension 

### ISSUE THREAD

**Issue by alshafeekbgf** [Azure/azure-service-operator#1256]
Hi Team,

I had deployed the azure operarator and deployed the PostgreSQL server,while creating the extension am getting below error

  extensions:
    - name: "postgis"
    - name: "timescaledb"
    - name: "tablefunc"

error is 
```
azure-operator-service
{"level":"info","ts":"2020-08-20T08:04:35.543Z","logger":"azure-operator","msg":"Processing PostgreSQL Database:","name":"igrid/gf-sqldb-igrid-igrid-t-azwe"}
azure-operator-service
{"level":"info","ts":"2020-08-20T08:04:35.856Z","logger":"azure-operator","msg":"There is gf-sqldb-igrid-igrid-t-azwe PostgreSQL Database already in gf-sqlsrv-igrid-t-azwe server"}
azure-operator-service
{"level":"info","ts":"2020-08-20T08:04:36.123Z","logger":"azure-operator","msg":"There is igrid_user PostgreSQL Database user already in gf-sqldb-igrid-igrid-t-azwe database"}
azure-operator-service
{"level":"info","ts":"2020-08-20T08:04:36.126Z","logger":"azure-operator","msg":"There is postgis PostgreSQL Database extension already in gf-sqldb-igrid-igrid-t-azwe database"}
azure-operator-service
{"level":"error","ts":"2020-08-20T08:04:36.596Z","logger":"azure-operator","msg":"error creating PostgreSQL Database extension: timescaledb","name":"igrid/gf-sqldb-igrid-igrid-t-azwe","error":"read tcp 10.101.0.60:33950->13.69.105.208:5432: read: connection reset by peer"}
azure-operator-service
{"level":"error","ts":"2020-08-20T08:04:36.596Z","logger":"controller-runtime.controller","msg":"Reconciler error","controller":"postgresqldb","request":"igrid/gf-sqldb-igrid-igrid-t-azwe","error":"read tcp 10.101.0.60:33950->13.69.105.208:5432: read: connection reset by peer"}
```

**Comment by babbageclunk** [comment]
Hi @alshafeekbgf  - can you give us more information about what happened after these messages were logged? Was the timescaledb extension available in the database? Was there any more logging from the operator? Did it keep trying to reconcile the database?

Thanks!

**Comment by alshafeekbgf** [comment]
Am not able to add tomescaledb with extension.When I enable timescaldb manually through UI,it is working and the error disappears.

{"level":"error","ts":"2020-08-20T08:04:36.596Z","logger":"azure-operator","msg":"error creating PostgreSQL Database extension: timescaledb","name":"igrid/gf-sqldb-igrid-igrid-t-azwe","error":"read tcp 10.101.0.60:33950->13.69.105.208:5432: read: connection reset by peer"}

**Comment by theunrepentantgeek** [comment]
@babbageclunk Would you please try to repro this issue?

**Comment by babbageclunk** [comment]
I don't think this is anything to do with ASO - there's no way to manage extensions using the custom resource at the moment. 

Activating the timescaledb extension requires changing the `shared_preload_libraries` parameter to include `timescaledb` - there's no ASO custom resource corresponding to the ARM configuration resource, so it needs to be done with the Azure CLI or in the portal. Then the server needs to be restarted, and then the `CREATE EXTENSION timescaledb` command can run successfully. If you try to create the extension without the parameter and restart, the server drops the connection - maybe that was the error you were seeing?
