### ISSUE TITLE
Understanding dependencies of resources

### ISSUE THREAD

**Issue by VenkatGowrishankar** [Azure/azure-service-operator#1258]
Hi, 

In the example for Azure SQL deployment - the ordering of dependent resources is switched? 
`$ kubectl apply -f azure-votes-sql/manifests/azure_v1_resourcegroup.yaml`
`$ kubectl apply -f azure-votes-sql/manifests/azure_v1_sqldatabase.yaml `
`$ kubectl apply -f azure-votes-sql/manifests/azure_v1_sqlserver.yaml`

in the above example  - the sqlserver.yaml be before sqldatabase.yml? Please add the documentation label.

**Comment by babbageclunk** [comment]
No, this order will work fine. You're right that the database obviously can't be created before the server, but the  nice thing about the way the operator works is that you can just say "please create these objects" and the operator's reconciliation loop will work on creating both the database and the server. Initially provisioning the database will fail, but once the server is provisioned the database will be created. You don't need to manually manage those dependencies.

**Comment by VenkatGowrishankar** [comment]
Awesome, i wasnt sure that operator managed those dependencies. Thanks for the explanation.
