### ISSUE TITLE
Bug: External changes to resources are not reconciled with the operator

### ISSUE THREAD

**Issue by sakthi-vetrivel** [Azure/azure-service-operator#1263]
**Describe the bug**
When I change properties of a resource directly through the Azure Portal or CLI, the operator is not aware of these changes, and does not reconcile the resource to update to the desired state.

**To Reproduce**
1. Create a CosmosDB instance through Azure Service Operator
2. Enable/disable multi-region writes for the CosmosDB in Azure Portal

**Expected behavior**
I expected the controller to notice the change to the resource and update the CosmosDB to reflect the initial definition.

**Comment by matthchr** [comment]
Closing as a duplicate - we need to do diffs, tracked by #1491
