### ISSUE TITLE
Improve documentation around diagnosability, debuggability and logging

### ISSUE THREAD

**Issue by matthchr** [Azure/azure-service-operator#1264]
**Describe the current behavior**
We don't have much documentation about diagnosability/debuggability of the operator.

**Describe the improvement**
We should have some basic documentation explaining how to investigate issues with the operator and what to do if things go wrong. We should certainly at least point out that without a cluster-wide logging aggregator, issues may be difficult to diagnose given the Kube pod log defaults.

**Comment by lwindolf** [comment]
Documentation is still missing
