### ISSUE TITLE
Feature: Support Traffic Manager Profiles and Traffic Manager Endpoints

### ISSUE THREAD

**Issue by vidarw** [Azure/azure-service-operator#1265]
Added support for Traffic Manager Profiles, Traffic Manager Endpoints and DNS zone CNAME records would be great.
This way the service operator would be able to operate it's cluster in a "self sustained" load balanced environment (ie. failover clusters, load multi-region deployments and similar scenarios) and act as a replacement for the ExternalDNS component often used for single cluster installations.

As the traffic manager profiles obviously will be shared with other Kubernetes clusters (and/or other webserveres) this needs to be taken into consideration during provisioning. We could easily get a situation where multiple clusters (with their own operators) might try to create/update the same profile. The same applys to the DNS CNAME record which would point to a single traffic manager profile.

Each cluster should have it's own endpoint configuration - pointing to the ingress IP of choice. Being able to automatically fetch this from a reference to a namespace+ingress would be a huge time saver in terms of usability and generalization.

**Comment by matthchr** [comment]
We're still interested in doing this

**Comment by asos-tommycouzens** [comment]
This would be great!

**Comment by netanel-sayada** [comment]
We are in a muli cluster env and this is a must for us

**Comment by super-harsh** [comment]
`Microsoft.network/DnsZone` and `Microsoft.network/DnsZone/recordSets` were added via #2918.

**Comment by EppO** [comment]
Azure public DNS is implemented but Traffic Manager profile is still in the backlog. Would be interested for it too

**Comment by eskaufel** [comment]
We also need TM
