### ISSUE TITLE
Feature: Add MariaDB option to service operator

### ISSUE THREAD

**Issue by michael-niemand** [Azure/azure-service-operator#1268]
Right now, there is no way to deploy a MariaDB DBMS and DB using Azure Service Operator, even though an according Azure service exists.

I think there should be the option to also deploy a MariaDB DBMS as well as databases using the Azure Service Operator.

**Comment by sakthi-vetrivel** [comment]
Hi @michael-niemand, we're looking at supporting a larger number of Azure resource by using code generation to create the CRDs (#1192). Support for MariaDB will likely be a part of that effort.

**Comment by theunrepentantgeek** [comment]
At first inspection this requires support for the `microsoft.dbformariadb` resource.

See this ARM resource template example - https://docs.microsoft.com/en-us/azure/mariadb/quickstart-create-mariadb-server-database-arm-template?tabs=azure-portal

**Comment by matthchr** [comment]
We still need to do this, moving it to beta.1 milestone
