### ISSUE TITLE
Makefile should hardcode tool versions for consistency

### ISSUE THREAD

**Issue by matthchr** [Azure/azure-service-operator#1271]
**Describe the current behavior**
Versions of tools run by the makefile (Kustomize and the like) can vary, causing differences in generated output, especially in the Helm charts.

**Describe the improvement**
The Makefile should hard code these like it does in k8s-infra.

**Comment by matthchr** [comment]
We should try running the v1 build in the v2 devcontainer possibly

**Comment by Porges** [comment]
Not going to work on improving the v1 pipeline as it is in maintenance mode.
