### ISSUE TITLE
Support Managed Identity for more resources

### ISSUE THREAD

**Issue by matthchr** [Azure/azure-service-operator#1289]
**Describe the current behavior**
Some resources can be managed with Managed Identity rather than a service principal, but many cannot.

**Describe the improvement**
We should have a consistent experience where all resources can be managed with a managed identity.

**Comment by kyschouv** [comment]
This is especially important to my group (managed identity support for running ASO, instead of service principal). We've hit the AD service principal limit already, so we're using managed identities wherever possible.

**Comment by matthchr** [comment]
This actually works, my previous tests were flawed. The documentation explaining _how_ to configure this was poor, but I have a PR coming out that resolves that. Closing this.
