### ISSUE TITLE
Consider using a different UUID library

### ISSUE THREAD

**Issue by matthchr** [Azure/azure-service-operator#1291]
**Describe the current behavior**
We're using github.com/satori/go.uuid which hasnt been updated in a while.

**Describe the improvement**
Move to a different library. Overall usage is quite small.

**Comment by matthchr** [comment]
There's an API compatible version that's been updated more recently: https://github.com/gofrs/uuid

**Comment by Porges** [comment]
This is currently not possible as `azure-sdk-for-go` has [a direct dependency on the bad package](https://github.com/Azure/azure-sdk-for-go/issues/3158#issuecomment-717569512).

**Comment by Porges** [comment]
Maybe I can use `go.mod` rewrites…

**Comment by matthchr** [comment]
@porges did you do this?

**Comment by Porges** [comment]
@matthchr waiting for https://github.com/Azure/autorest.go/pull/520 to land in autorest, then we can update our dependencies.
