### ISSUE TITLE
Add autocreation of access policy for ASO identity during key vault interaction

### ISSUE THREAD

**Issue by r-t-m** [Azure/azure-service-operator#1294]
**Describe the current behavior**
Currently access policy should be added for ASO service identity when you deploy key vault so that it could be used to store secrets there. This will imply research about identity used by ASO and necessary rights to do that + the fact that identity won't be changed as otherwise the latter needs to be done again.

**Describe the improvement**
Please add additional field to the spec like `grantCurrentASOIdentityRights=true` which will be taken into account by controller to grant ASO identity minimum set of rights to use key vault for storing the secrets.

**Comment by r-t-m** [comment]
Still needed.

**Comment by matthchr** [comment]
This is still something we need to think about

**Comment by matthchr** [comment]
This issue applies to ASOv1, which is in maintenance mode. As such, it's unlikely this behavior will be changed for ASOv1.

In ASOv2, we don't currently support writing secrets to KeyVault. It's on the roadmap, and when it's added this can be accomplished using the standard `RoleAssignment` CRD. It's unlikely we'll do it automatically in ASOv2, especially given the work we're doing on multitenancy, which makes choosing which identity to give this permission to tricky. It's better for the user to configure it themselves so they have the most flexibility in using what identities they want.

Closing this, given the above.
