### ISSUE TITLE
Feature: AKS Nodepool CRD

### ISSUE THREAD

**Issue by droopy4096** [Azure/azure-service-operator#1300]
Currently it is impossible to control nodepools from ASO. Our usecase is having GPU-bound kubernetes workloads. Thus whenever we attempt to deploy app into the cluster we need to provision more GPU nodes, inclusing scaling up/down the app.

**Comment by sakthi-vetrivel** [comment]
@droopy4096 This is interesting. We don't consider ASO as a method of managing the kubernetes cluster itself, but to attach other services to the cluster. Is there a reason why you'd prefer to use ASO to do this instead of cluster autoscaler?

**Comment by CecileRobertMichon** [comment]
@droopy4096 have you considered https://capz.sigs.k8s.io/topics/managedcluster.html ?

**Comment by matthchr** [comment]
We have support for this (and AKS managed cluster) in [v2.0.0-alpha.1](https://github.com/Azure/azure-service-operator/releases/tag/v2.0.0-alpha.1), feel free to give it a try - the examples are [here](https://github.com/Azure/azure-service-operator/tree/master/v2/config/samples/microsoft.containerservice).
