### ISSUE TITLE
Feature: Azure Event Grid support

### ISSUE THREAD

**Issue by kyschouv** [Azure/azure-service-operator#1303]
We have a project in development that plans to use Azure Service Bus and Azure Event Grid. We'd love to deploy these through ASO, but need support added.

**Comment by matthchr** [comment]
Editing this to just request Azure Event Grid, as we already have a request for Service Bus here: #1175

**Comment by kyschouv** [comment]
Is there any update you could share on either this request or the service bus request?

**Comment by matthchr** [comment]
I believe we're planning on both of them with the autogenerated work which is proceeding. We're expecting an alpha to become available for those resources sometime this quarter.

**Comment by Porges** [comment]
Support for Domains, Topics, and Subscriptions has been added to the latest v2 version. A release supporting these will be out soon.
