### ISSUE TITLE
Feature: Support Application Insights availability tests, alert rules

### ISSUE THREAD

**Issue by kyschouv** [Azure/azure-service-operator#1305]
We maintain ARM templates for Application Insights availability tests and alert rules, which are deployed on top of an application's Application Insights deployment. It'd be nice to deploy these through ASO as well, so we don't have an extra set of application-specific infrastructure to manage that's not represented in Kubernetes.

**Comment by matthchr** [comment]
I discussed this some with @kyschouv and we determined that the following resources were required for this:

* microsoft.insights/webtests
* microsoft.insights/actiongroups
* microsoft.insights/autoscalesettings
* microsoft.insights/metricalerts
* microsoft.insights/scheduledqueryrules
* microsoft.insights/components

The last one (`microsoft.insights/components`) is also affiliated with `microsoft.operationalinsights/workspace`, so we should probably do that as well.

**Comment by matthchr** [comment]
Only `microsoft.insights/components`, `microsoft.operationalinsights/workspace`, and `microsoft.insights/webtests` were done in #2000

**Comment by matthchr** [comment]
Moving this to beta-0 as not all types were added in alpha-4

**Comment by matthchr** [comment]
Note that metricalerts requires #2004

**Comment by matthchr** [comment]
Will split this out into a few items (one for each resource)

**Comment by matthchr** [comment]
We still want to do this, but makes sense to wait until the #2323 change is merged

**Comment by matthchr** [comment]
We can now do this since Swagger has merged, we should look into doing it
