### ISSUE TITLE
Bug: SQL Users whose spec is updated to change assigned roles do not update roles in the backing DB

### ISSUE THREAD

**Issue by matthchr** [Azure/azure-service-operator#1311]
**Describe the bug**
SQL Users whose spec is updated to change assigned roles do not update roles in the backing DB. I believe that this applies to all SQL users we currently support, but need to reproduce to be sure.

**To Reproduce**
Create user, specify some roles, remove 1 and update user, check DB to see if that role was removed for that user.

**Expected behavior**
The user is no longer a member of that role (as if it has been removed via `EXEC sp_droprolemember 'Role', 'userName';`)

**Comment by matthchr** [comment]
This shouldn't have been resolved #1317 as that only solves this problem for MySQL.

**Comment by theunrepentantgeek** [comment]
ASO v1 is in maintenance mode and we won't be making changes there.

We intent to support users in v2 for each supported database type; leaving this issue open to remind ourselves to ensure this works properly.

**Comment by matthchr** [comment]
This works properly in ASOv1 MySQL and ASOv2 MySQL (which is the only DB user we currently support). We already have #2125 tracking general support for other SQL users and when they are added they will follow the pattern set up by MySQL in ASOv2, which means this will work for them too.

Given all of that, I am closing this.
