### ISSUE TITLE
Support for Private Link

### ISSUE THREAD

**Issue by Mahesh-MSFT** [Azure/azure-service-operator#1313]
Azure services such as Azure Database for PostgreSQL, MySQL, SQL support private link.
Using private links enables AKS to connect to these database services using private ip addresses.
It appears that ASO doesn't provide a way to create services with private endpoint.

Can ASO create Azure services with private endpoint?

This will help to Partners who are building their IP solutions for deployments across multiple clouds. In Azure context, they can use private link support to avoid use of public ip addresses and improve security posture.

**Comment by gowrisankar22** [comment]
We are also looking for the same. Private link enabled service also add a private link to the already existing services. 

1. https://github.com/Azure/azure-sdk-for-go/blob/master/services/network/mgmt/2020-06-01/network/privateendpoints.go
2. https://github.com/Azure/azure-sdk-for-go/tree/master/services/network/mgmt/2020-06-01/network
3. https://github.com/Azure/azure-rest-api-specs/blob/master/specification/network/resource-manager/readme.go.md
4. https://github.com/Azure/azure-rest-api-specs/tree/master/specification/network/resource-manager/Microsoft.Network/stable/2020-07-01

**Comment by matthchr** [comment]
Have also had a customer request PrivateEndpoint for ServiceBus.

**Comment by matthchr** [comment]
We're still interested in doing this

**Comment by matthchr** [comment]
This is still a priority for us, but it's stuck behind #2323 for now. We're hoping to make progress on this in the near future.

**Comment by ZinebElMoutia** [comment]
Do we have a timeline for this feature? Thanks

**Comment by theunrepentantgeek** [comment]
It's a priority for our `beta.4` release, which should be coming soon. We don't have an exact date for that, however. 

As noted above, this is blocked behind #2323 which we're making good progress on resolving.
