### ISSUE TITLE
refactoring: clarify meaning of bool returns from resourcemanager.ARMClient.Ensure + Delete

### ISSUE THREAD

**Issue by babbageclunk** [Azure/azure-service-operator#1347]
At the moment `ARMClient.Ensure` and `.Delete` both return `(bool, error)` - the meaning of the boolean return isn't documented on the interface and it's often unclear what they mean in the implementations for each resource. The only way to understand what each means is by reading the AsyncReconciler source. 

In the case of `Ensure` a true return indicates that the resource is finished and doesn't need re-reconciling. 

For `Delete` true indicates that the resource was found (although it may have been deleted in this pass), so the resource will need another reconcile pass to check that it was removed.

(That these senses are opposed is also confusing.)

Change the methods to return enum values that more clearly indicate what the return value will mean when reading a particular ARMClient implementation.

**Comment by matthchr** [comment]
Closing this as v1 is in maintenance mode.
