### ISSUE TITLE
Bug: resource status doesn't get updated if there's an error deleting it

### ISSUE THREAD

**Issue by babbageclunk** [Azure/azure-service-operator#1350]
As an example, if an AzureSQLUser has some tables in their schema and then we attempt to delete the k8s resource , the deletion will fail. The error message indicating that their schema isn't empty will appear in the logs, but not on the status of the resource, so from the user's perspective the resource is just hanging around - if they don't have access to the logs there isn't any way for them to see why.

**To Reproduce**
* Create a user in an AzureSqlDatabase
* Create some tables with that user
* Delete the user
* Watch the operator logs - errors will be logged as the operator fails to delete the user.
* The user resource just hangs around with no indication of what's wrong.

**Expected behavior**
The resource status should include the error that's preventing us from deleting the resource.

**Comment by babbageclunk** [comment]
This will be addressed in v2 when the SQL users etc are ported from v1.

**Comment by matthchr** [comment]
This is fixed in v2 (in that this class of error isn't really possible there), BUT we don't support users yet there so leaving this open until we actually do.

**Comment by matthchr** [comment]
This can't happen in ASOv2, but we don't support AzureSQL there yet. See #2318 tracking that. I'm closing this as this problem wont happen in ASOv2. We can use the other issue to track AzureSQL support.
