### ISSUE TITLE
Bug: Parallel CI builds can delete each others resources

### ISSUE THREAD

**Issue by matthchr** [Azure/azure-service-operator#1354]
**Describe the bug**
Due to the makefile `test-cleanup-azure-resources` target not having any time or other filters, parallel CI runs can collide and cause issues.

**To Reproduce**
Run two CI builds at once, one will intermittently fail because of cleanup triggered by the other.

**Expected behavior**
Both CI builds succeed.

**Comment by Porges** [comment]
This is about the Pipelines run I think, but we should also do the same for Github Actions that touch live resources, with: https://github.blog/changelog/2021-04-19-github-actions-limit-workflow-run-or-job-concurrency/

**Comment by matthchr** [comment]
We don't release v1 very often, and even when we were this was only a minor issue. Leaving this open to document it for now, and will close it as v1 moves out of support.

**Comment by matthchr** [comment]
Closing this as it's no longer an issue
