### ISSUE TITLE
Bug: Generated Kubernetes secret names don't match documentation

### ISSUE THREAD

**Issue by kyschouv** [Azure/azure-service-operator#1360]
**Describe the bug**
The [documentation](https://github.com/Azure/azure-service-operator/blob/master/docs/howto/secrets.md) describes Kubernetes secret names as being the same as the resource's metadata.name. However, it appears that the actual name ends up being `{type}.{group}.{resource-name}`.

**Comment by matthchr** [comment]
I have a PR out that should fix this I think: #1358 - it would be good to confirm which specific resource you were looking at though.

**Comment by kyschouv** [comment]
Both AppInsights and StorageAccount.

**Comment by matthchr** [comment]
Ah you're right, I had missed those. I will update my PR to fix them as well.
