### ISSUE TITLE
Feature: Add pod annotations to aso helm charts

### ISSUE THREAD

**Issue by AdheipSingh** [Azure/azure-service-operator#1367]
<Describe the feature request>

- the current helm charts don't support the ability to add pod annotations.
- ex: pod annotations are useful where we want our aso creds to be accessed from vault etc.

**Comment by matthchr** [comment]
Can you expand a bit on the scenario where this would be useful?

**Comment by matthchr** [comment]
You mention: "pod annotations are useful where we want our aso creds to be accessed from vault", but AFAIK ASO takes creds specified as a Kubernetes secret, and configuring ASO to use keyvault is done through that Kubernetes secret. Are you wanting to use some sort of operator that relies on pod annotations to proxy KeyVault secrets to Kuberentes secrets or something?

We're not sure how to progress on this without more information.  We are cognizant of the fact that it took us 8 months to respond to this issue though, so we're going to leave this open for a while to give you a chance to respond.

**Comment by AdheipSingh** [comment]
@matthchr 

vault webhooks ( we have a mutating webhook ) injects init containers onto pods if pods's have certain vault specific annotations. This was my case. So i need to make sure those specific annotations are present in pods so vault configures all the env's.

If you are willing to accept this, id be wanting to submit a PR.

Thanks

**Comment by matthchr** [comment]
This is something we'll solve for the ASOv2 Helm chart
