### ISSUE TITLE
Feature: Support for PostgreSQL flexibleServers

### ISSUE THREAD

**Issue by johgoe** [Azure/azure-service-operator#1382]
PostgreSQLServer, PostgreSQLDatabase, PostgreSQLUser etc. currently just support `PostgreSQL Microsoft.DBforPostgreSQL/servers` but not `Microsoft.DBforPostgreSQL/flexibleServers` which seems to be a very similar  to each other.

**Comment by matthchr** [comment]
This is supported in ASO v2 alpha-3, which will be released later today. You can try it out once that release lands.

[Sample](https://github.com/Azure/azure-service-operator/blob/main/v2/config/samples/microsoft.dbforpostgresql/v1alpha1api20210601_flexibleserver.yaml)
[Guided example](https://github.com/Azure-Samples/azure-service-operator-samples/tree/master/azure-votes-postgresql)

Note that this resource is lacking great secrets support, which we are aware of and tracking: #1471. We know that without this the resource is usable in _theory_ but not in production. Solving this secrets problem is high on our list of priorities.
