### ISSUE TITLE
Improve logging and telemetry

### ISSUE THREAD

**Issue by matthchr** [Azure/azure-service-operator#1387]
We would like to make a number of logging improvements to ASO, both to improve customer diagnosability as well as our visibility into how things are working.

Here is a subset of the topics we'd like to improve:
- Pass logging context deeper into reconciliation methods to allow for more fine-grained logging (primarily when higher verbosity is enabled)
- Consider adding optional ability to egress logs to us directly (via application insights or some similar experience)
- Improve telemetry gathered by ASO. This could be used to for example track how long resources take us to provision (see #710)

**Comment by theunrepentantgeek** [comment]
Closing as duplicate-of/closely-related-to #1464
