### ISSUE TITLE
Feature: Creating privateIPAddress resource-type

### ISSUE THREAD

**Issue by parasharsingh8086** [Azure/azure-service-operator#1389]
Currently, if we create a Network Interface using this Operator, then it must be using publicIPAddress. There's no option to create Network Interface with Private IP VNET. In many cases, when oraganization doesn't want to expose the Virtual Machine to Internet, but only to it's Internal Network, then we are unable to create such VMs due to Network Interface issue.

---
apiVersion: azure.microsoft.com/v1alpha1
kind: AzureVirtualMachine
metadata:
  name: hpfvmrhel
  namespace: azure
spec:
  adminUserName: azureuser
  location: centralus
  networkInterfaceName: nic-sample-01
  osType: Linux
  platformImageURN: 'RedHat:RHEL:7-LVM:latest'
  resourceGroup: resourcegroup-azure-operators-k8
  sshPublicKeyData: >-
    {{ ssh-rsa }}
    
  vmSize: Standard_DS1_v2

In above YAML definition for AzureVirtualMachine, the networkInterfaceName: nic-sample-01

---
apiVersion: azure.microsoft.com/v1alpha1
kind: AzureNetworkInterface
metadata:
  name: nic-sample-01
  namespace: azure
spec:
  location: centralus
  publicIPAddressName: nic-pip-sample-01
  resourceGroup: resourcegroup-azure-operators-k8
  subnetName: test1
  vnetName: vnet-sample-01

However, I would like to NOT use publicIPAddressName, rather want to use privateIPAllocationMethod.

Can you please advise, how to create how to create AzureNetworkInterface using privateIPAllocationMethod?

**Comment by matthchr** [comment]
This is planned alongside our code generation work: #1192

**Comment by babbageclunk** [comment]
NetworkInterface with IP configuration including private IP addresses is now supported in ASO v2, although that version hasn't been released yet.

**Comment by matthchr** [comment]
ASOv2 beta.0 has been released, closing this as this is supported there.
