### ISSUE TITLE
Request: Openshift Operator Hub still using an old version of operator

### ISSUE THREAD

**Issue by lgmorand** [Azure/azure-service-operator#1392]
**Describe the bug**
Operator Hub offers version 0.37 of ASO. Can someone update it to a more recent version of the operator like a 1.x ?

**To Reproduce**
OpenShift > open Operator Hub

![operator-hub](https://user-images.githubusercontent.com/6757079/111494031-69578e80-873e-11eb-9590-2f4bbf95b5e5.png)

**Comment by babbageclunk** [comment]
Yes - I'm working on this right now.

**Comment by babbageclunk** [comment]
PRs for the updated bundle in the OpenShift and operatorhub stores.

https://github.com/operator-framework/community-operators/pull/4174
https://github.com/operator-framework/community-operators/pull/4175

**Comment by matthchr** [comment]
Closing this as the above PRs have been merged
