### ISSUE TITLE
Feature: Azure Cache for Redis,  Enterprise Tiers support

### ISSUE THREAD

**Issue by dashaun** [Azure/azure-service-operator#1400]
Basic, Standard and Premium are currently supported.  Redis Enterprise tiers were public preview October 2020, and GA in March 2021.

The enterprise tiers are represented as:
```      "type": "Microsoft.Cache/redisEnterprise"```

Active-Active feature is currently in public preview.

**Comment by matthchr** [comment]
We'll make sure to add this to our roadmap for codegenerated resources (see #1192).
