### ISSUE TITLE
Bug: Cannot log into MySQL as MySQLAADUser representing a group

### ISSUE THREAD

**Issue by matthchr** [Azure/azure-service-operator#1401]
**Describe the bug**
MySQLAADUser representing an AAD Group cannot be logged in as on the MySQL server.

**To Reproduce**
1. Create a `MySQLAADUser`  for a group. Specify the group name as the `Username` and the group object ID as the `AADID`.
2. Observe that the user reconciles successfully.
3. Attempt to log in to the user in MySQL, following [the instructions](https://docs.microsoft.com/en-us/azure/mysql/howto-configure-sign-in-azure-ad-authentication#creating-azure-ad-groups-in-azure-database-for-mysql). Specifically: "When logging in, members of the group will use their personal access tokens, but sign with the group name specified as the username."

**Expected behavior**
I am able to log in as the user.

**Comment by matthchr** [comment]
Flexible server is adding support for this sometime later this year (~Nov timeframe). Until then we have to live with this issue as we can't work around it.

**Comment by theunrepentantgeek** [comment]
We believe flexible support has been delayed, and are trying to find out the new estimate.

**Comment by matthchr** [comment]
It sounds like this was delayed until ~Sept 2022

**Comment by matthchr** [comment]
Still waiting on this from the product team AFAIK

**Comment by matthchr** [comment]
The product team has recently release support for this for MySQL Flexible Server. We now need to implement support for it in ASO.

**Comment by matthchr** [comment]
I'm currently working on support for this in MySQL FlexibleServer
