### ISSUE TITLE
Add option to specify name of resource in azure or add namespace to azure name

### ISSUE THREAD

**Issue by bjartek** [Azure/azure-service-operator#1405]
**Describe the current behavior**

Given the following resource as an example:

```apiVersion: azure.microsoft.com/v1alpha1
kind: StorageAccount
metadata:
  name: sgapplication
  namespace: dev
spec:
  location: norwayeast
  resourceGroup: rg-application-dev
  sku:
    name: Standard_LRS
  kind: StorageV2
  accessTier: Hot
  supportsHttpsTrafficOnly: true
```

The name for the storageaccount in azure will be sgapplication. However what if I then want to add the same storageaccount in another namespace with the config

```apiVersion: azure.microsoft.com/v1alpha1
kind: StorageAccount
metadata:
  name: sgapplication
  namespace: test
spec:
  location: norwayeast
  resourceGroup: rg-application-test
  sku:
    name: Standard_LRS
  kind: StorageV2
  accessTier: Hot
  supportsHttpsTrafficOnly: true
 ```

Then that will not work since it will use the same storageaccount name in Azure. 

**Describe the improvement**
Add option to prefix the name used for the resource in azure with namespace, or to override the name of the azure resource. 
This should apply to all aso resources that are namespaced, not just StorageAccount.

**Additional context**
Why?
When you want to compose configuration across environments with say kustomize/helm you want to use standard kubernetes names across namespaces. It makes composing things so much easier.

**Comment by bjartek** [comment]
This looks like it is a duplicate of https://github.com/Azure/azure-service-operator/issues/1262

**Comment by matthchr** [comment]
ASOv2 beta.0 has been released, closing this as this is supported there.
