### ISSUE TITLE
Feature: Make json-schema files available

### ISSUE THREAD

**Issue by bjartek** [Azure/azure-service-operator#1411]
We are using https://kubeval.instrumenta.dev/ to validate kubernetes manifests against their schema. Currently we are skipping kinds that does not have a schema since we do not have access to the AZO schema files. Can you make them available in the release in github or in some other way?

**Comment by matthchr** [comment]
@bjartek - I'm not super familiar with kubeval, but their [documentation on CRDs](https://kubeval.instrumenta.dev/#crds) says:
> Currently kubeval relies on schemas generated from the Kubernetes API. This means it's not possible to validate resources using CRDs.

Since all ASO resources are CRDs, it seems validating them using kubeval isn't supported?

The schemas for the CRDs are the CRDs themselves, which are really OpenAPI schemas and should adhere to the [Kubernetes structural schema](https://kubernetes.io/blog/2019/06/20/crd-structural-schema/).

**Comment by bjartek** [comment]
That documentation is wrong. I will get them to fix it.

Here is how the flux ppl do it https://github.com/fluxcd/flux2-kustomize-helm-example/blob/main/scripts/validate.sh

**Comment by matthchr** [comment]
I see, and they generate those schemas by [running an action](https://github.com/fluxcd/flux2/blob/40ce3d50c2e3566ab67beae044e3fd8f9f3cb927/.github/workflows/release.yaml#L59) which you can see defined [here](https://github.com/fluxcd/pkg/tree/main/actions/crdjsonschema). Specifically they seem to be executing this [python script](https://github.com/fluxcd/pkg/blob/main/actions/crdjsonschema/openapi2jsonschema.py) to extract the JSON schema from the OpenAPI specification.

To workaround our lack of schemas right now you can just transform the CRD YAMLs into JSON schemas yourself by using that same script/Dockerfile. The YAMLs are in included in the ASO release in the `setup.yaml` file.

I'm a bit surprised that Kubeval doesn't just understand how to do that itself though - it seems awkward to require CRD authors to do what amounts to some simple transformations on the CRDs they're publishing. Kubeval could just as easily do those transforms on their side and it'd work for every CRD out of the box. Actually I see that even others have pointed this out in [this issue](https://github.com/instrumenta/kubeval/issues/47) (this issue also has some docs around how to do the conversions).

**Comment by bjartek** [comment]
Awesome research! I will look into this :)

**Comment by theunrepentantgeek** [comment]
Should we close this issue now?
