### ISSUE TITLE
Operator bundle readme should be editable as a markdown file

### ISSUE THREAD

**Issue by babbageclunk** [Azure/azure-service-operator#1417]
**Describe the current behavior**
The installation instructions for the operator bundle are embedded in `config/operator-bundle/bases/azure-service-operator.clusterserviceversion.yaml` at the moment. That makes them hard to maintain and makes it more likely that they get out of sync with our regular installation instructions.

**Describe the improvement**
After the generation changes in #1416, the installation instructions should be inserted into the generated yaml from a regular markdown file under the docs directory.

**Comment by babbageclunk** [comment]
From discussion on #1410

**Comment by matthchr** [comment]
We still want to do this

**Comment by matthchr** [comment]
We still want to do this

**Comment by matthchr** [comment]
This is related to #1967 - we want to do it

**Comment by matthchr** [comment]
We still want to do this but it's blocked on the operator bundle (#2929) size issues

**Comment by matthchr** [comment]
We still want to do this but it's blocked on the operator bundle (#2929) size issues

**Comment by matthchr** [comment]
This was tracking the ASOv1 operator bundle, which has since been deprecated. Closing
