### ISSUE TITLE
Feature: Support importing an entire graph of resources

### ISSUE THREAD

**Issue by matthchr** [Azure/azure-service-operator#1422]
Rather than painstakingly importing resources 1 by 1, we should consider somehow allowing an entire graph of resources to be imported. One way that was suggested is by having a higher level CRD that you could point at an ARM resource and it would then import that resource and everything it owned.

Options such as "do we manage the imported resources or just mirror them" might be settable on the higher level CRD and then could apply to all of the matched imported resources.

There are some obvious open questions such as what the higher level CRD would mean _after_ the import was done - we might need to make it like a `Job` that "runs" and then finishes?

**Comment by cdmurph32** [comment]
A couple ideas:

- The instance of the CRD should probably self-delete at the end of the import.
- Something like, `importNested` should be included in the spec. I think a good early candidate for such a feature would be to import everything within a resource group.
- By default all imported objects should be annotated with `skipreconcile: true`.

**Comment by matthchr** [comment]
Closing in favor of #1238
