### ISSUE TITLE
Bug: CI doesn't catch broken patches

### ISSUE THREAD

**Issue by babbageclunk** [Azure/azure-service-operator#1429]
**Describe the bug**
As highlighted in #1428, the CI pipeline doesn't `kustomize build` the CRDs unless the master branch is built (which I think only happens when we are doing a release). There's a task to deploy the helm chart, but that's the built contents of the CRDs at the last release, so problems with the patches won't be found.

Add a task that's similar to the Helm Deploy one but which creates the settings secret manually and then uses `make deploy IMG=...` to check that it deploys successfully. Also it might be worth adding cleanup tasks that delete the CRDs each time as well?

**Comment by matthchr** [comment]
Closing this as v1 is in maintenance mode. While it would ideally be great to get this fixed, the focus is on v2 right now and in v2 we already have tests that run on PR that cover this situation.
