### ISSUE TITLE
Design: Determine how major generator changes will be handled

### ISSUE THREAD

**Issue by matthchr** [Azure/azure-service-operator#1435]
We should have a discussion about what generator changes look like in the future: when we need to change the generator drastically, how does it impact the existing resources? Does the generator need to understand how to create both the old and the new shapes? If the change is nonbreaking (say an addition of a property on all resources) is there any work required or can we just make changes on existing resource versions?

**Comment by matthchr** [comment]
related to #2107. @theunrepentantgeek will look at this and possibly close as a duplicate.

**Comment by theunrepentantgeek** [comment]
The design in #2107 handles most of the cases we want to consider. Adding new fields to resources is non-breaking as long as they're optional or have sensible defaults. 

Worst case, if we have a breaking change, something like #1238 would make manual migration to the new version of ASO practical.
