### ISSUE TITLE
Outstanding controller productionization issues

### ISSUE THREAD

**Issue by Porges** [Azure/azure-service-operator#1436]
Sticking this here (from @matthchr) so it doesn't get lost:

> * We need to drop the hash-generation and storage on the spec and just do a diff with Azure (see my PR here in ASO for what I think the pattern should basically look like): https://github.com/Azure/azure-service-operator/pull/1361
> * Look at status types and how we're updating them. Do we want to do something like Crossplane does with forProvider/atProvider to separate "state from the operator" vs "state from Azure"? As part of this look at moving some of the stuff that I put into annotations onto status instead.
> * Probably need some testing of failure-modes with simulated errors. Do we tolerate things like DeploymentAlreadyExists, etc well and continue reconciling?
> * Are we providing enough information to the user when something goes wrong? Do we have clear "states" - i.e. are we reconciling a thing vs not?
> * Logging + eventing improvements
> * Some tests where you deploy things backwards would maybe be worth it too: Like create SQL server, then wait a bit and create the RG and ensure they both make it to steady.

**Comment by matthchr** [comment]
Moving this to alpha-1 as a good bit of it we've done and others should maybe become their own dedicated issue (if they aren't already?)

**Comment by matthchr** [comment]
I've split this out into multiple issues for the bits we haven't already done.

Here's the breakdown:
1. Drop hash-generation and do a diff with Azure instead: #1491
2. ForProvider/AtProvider - this is covered by our [object structure](https://github.com/Azure/azure-service-operator/blob/master/docs/design/clarifying-object-structure.md) design.
3. Test improvements: #1726
4. "Clear states for user" is finished now via the Conditions work.
5. Improve logging: #1387
6. Tests where we deploy things backwards have been added in `edge_case_test.go`
