### ISSUE TITLE
Tests need retries to avoid flakiness

### ISSUE THREAD

**Issue by Porges** [Azure/azure-service-operator#1437]
At the moment checks like HEADing deleted resources are not retried. We should do so.

**Comment by matthchr** [comment]
Check with @porges if he's still experiencing pain here.

**Comment by Porges** [comment]
This hasn't caused any issues so far, but I'll add support for it.

**Comment by Porges** [comment]
Actually, dug into the `azure-sdk-for-go` internals and there is a default retry policy applied. Closing.
