### ISSUE TITLE
The GoJSONSchema library doesn't handle missing schema references well

### ISSUE THREAD

**Issue by theunrepentantgeek** [Azure/azure-service-operator#1444]
If a schema reference is missing, the library returns an error:
```
error loading schema from 'https://schema.management.azure.com/schemas/2015-01-01/deploymentTemplate.json'
(error loading schema from 'https://schema.management.azure.com/schemas/2015-01-01/deploymentTemplate.json' 
 (Object has no key 'servers_backupLongTermRetentionVaults'))
```

For our purposes, we'd like to have the option to ignore missing references so that we can do code generation for unaffected resources - we don't want a problem with the ARM Schemas to block us completely.

@babbageclunk and myself independently had the same idea - to contribute an up-stream change that allows this to be specified as optional behaviour. 

We might also roll up the change by @devigned to warn on invalid regular expressions.

For both behaviours, we would probably want to be able to specify `Fatal` (stops and returns an error), `Warn` (logs a message and keeps going), and `Ignore` (just keep going).

**Comment by Porges** [comment]
This shouldn’t be such a problem any more now that we load the schemas from submodules instead of live.

**Comment by matthchr** [comment]
We don't have remote schemas now!
