### ISSUE TITLE
How do upgrades of the Service Operator work?

### ISSUE THREAD

**Issue by theunrepentantgeek** [Azure/azure-service-operator#1446]
A bunch of issues to consider here, including:

* How do we recover from a failed upgrade? Do we try the upgrade again or can we revert to an earlier verison of the operator?
* How does the Operator Lifecycle Manager play into this? Can it prevent upgrades that won't work?
* When do the web-hooks for upgrades trigger? 
* Is an upgrade triggered all at once or JIT? If JIT, how do we roll back if it fails?

**Comment by matthchr** [comment]
Can Porter help us here?
