### ISSUE TITLE
Should Status contain all fields, or only fields which are not already in Spec?

### ISSUE THREAD

**Issue by matthchr** [Azure/azure-service-operator#1449]
It's a slightly foreign pattern to duplicate information like we're currently doing in Kubernetes, but the disadvantage of not duplicating is that there's no way for customers to realize that their resource doesn't match the spec without going outside of the context of the operator.

**Comment by Porges** [comment]
@matthchr I think we can count this as resolved now?

**Comment by matthchr** [comment]
Agree - closing this
