### ISSUE TITLE
Investigate improvements to the pluralization pipeline stage

### ISSUE THREAD

**Issue by matthchr** [Azure/azure-service-operator#1459]
1. Consider performing the pluralization improvements step for `spec` and `status` of resources too.
2. Add a golden test for pluralization?

**Comment by matthchr** [comment]
Putting this in alpha-1 right now as I believe it's just changing type names which we're not too concerned about for initial alpha.

**Comment by theunrepentantgeek** [comment]
Closing in favour of #1591
