### ISSUE TITLE
Enhance filtering to allow for multiple matches

### ISSUE THREAD

**Issue by theunrepentantgeek** [Azure/azure-service-operator#1461]
Currently the filters allow only specifying a single wildcard match; this doesn't seem to be sufficiently powerful, so I suggest we extend them by allowing multiple comma-separated wildcard matches to be included.

For example, we could specify multiple versions in this way:

```
  - action: exclude
    group: microsoft.automation
    version: v20150601, v20151031, v20170418
    because: it generates types containing AnyType
```

* Leading/trailing space should be ignored
* Semantics are **or** (`||`) based - the filter matches if _any_ of the wildcards match

**Comment by Porges** [comment]
We could allow setting `versionRegex` directly and then write `versionRegex: v20150601|v20151031|v20170418`

**Comment by theunrepentantgeek** [comment]
No longer required.
