### ISSUE TITLE
Enable metrics and tracing

### ISSUE THREAD

**Issue by devigned** [Azure/azure-service-operator#1464]
Wire up OpenCensus metrics and tracing.

- Main should take in parameters for configuring / exposing / relaying metrics and traces.
- Zips and the Azure SDK for Go should be wired up as well (Azure SDK for Go has tracing / metrics support)

Reasoning:
- Provide insight to where time is spent
- Help to diagnose optimal time for deployment polling / requeue
- Enable better debugging

**Comment by theunrepentantgeek** [comment]
_Combining with #1387 :_

> We would like to make a number of logging improvements to ASO, both to improve customer diagnosability as well as our visibility into how things are working.
> 
> Here is a subset of the topics we'd like to improve:
> 
> Pass logging context deeper into reconciliation methods to allow for more fine-grained logging (primarily when higher verbosity is enabled)
> Consider adding optional ability to egress logs to us directly (via application insights or some similar experience)
Improve telemetry gathered by ASO. This could be used to for example track how long resources take us to provision (see Task: Investigate ways to start storing metrics about service provisioning times #710)
