### ISSUE TITLE
Enable bring your own resource

### ISSUE THREAD

**Issue by devigned** [Azure/azure-service-operator#1465]
A user should be able to create a K8s resource of any kind. If that resource already exists, then the resource should be owned by the user, not by the controller. Ownership of a resource implies the owner is responsible for the lifecycle of the resource. For example, an owner of a resource is responsible for deletion of the resource, and if a user brings their own resource, the controller should not delete the Azure resource when the K8s resource is deleted.

Transitively, a resource group should not be deleted if it contains resources which are not owned by the owner of the resource group. These resources need not be represented by K8s resources, but do exist in Azure. This implies that there may need to be a mechanism for a K8s resource to check in Azure for child resources owned by other entities.

**Comment by matthchr** [comment]
See the above linked adoption design.

**Comment by theunrepentantgeek** [comment]
We need to finish the adoption design and make this possible.

**Comment by matthchr** [comment]
The adoption design mentioned above still covers this, although technically it's doable today with `reconcile-policy: skip` already.

**Comment by matthchr** [comment]
We're still working on this, we're tracking this through the Adoption PR so closing this
