### ISSUE TITLE
Discussion: API Versioning

### ISSUE THREAD

**Issue by theunrepentantgeek** [Azure/azure-service-operator#1466]
One approach to providing support across multiple versions of the ARM schema is to generate a synthetic "superset" version of a type from any one service by simply merging together all the properties of all of the versions.

This will likely work well for >90% of cases where the changes between versions are just adding new properties for new capabilities:

``` go
// Person, v2015-01-01
type Person struct {
    FirstName string
    LastName  string
}

// Person, v2017-01-01
type Person struct {
    FirstName string
    LastName  string
    Age       int
}
```

We can easily create a superset Person type that is capable of handling all of the information required for either version:

``` go
// Person, hub version
type Person struct {
    FirstName string
    LastName  string
    Age       int
}
```

As long as we store/recall the same version of a Person, full fidelity is retained. Further, if the version being retrieved has a strict subset of properties, everything will likely still work (modulo semantic issues).

However, this approach has limitations when the version we want to retrieve has different properties to the one we originally stored.

There are multiple different scenarios to consider:

* Renaming of a single property - e.g. if `LastName` was changed to `FamilyName`.

* Replacement of properties to capture the same information in a different way - e.g. if `FirstName` and `LastName` were replaced by `FamilyName`, `GivenNames` and `KnownAs`

A variation of replacement would be when only the type of the property has changed - e.g. if `Gender` was changed from a single character to a full string.

### Outstanding questions

How do we extend the code generation process for these situations?

How much flexibility do we need in a solution?

How much can we infer automatically?

**Comment by matthchr** [comment]
@theunrepentantgeek - wondering how much of this we've already done? Maybe this can be closed in favor of the various other issues tracking API + Storage versioning?

Sticking this in alpha-0 for now as well because certainly we have to at least have had the discussion about API versioning before then =)

**Comment by matthchr** [comment]
This has actually been superseded by other work.
