### ISSUE TITLE
Handle apiVersion property specially

### ISSUE THREAD

**Issue by matthchr** [Azure/azure-service-operator#1468]
The desired state is as follows (I think):

1. `APIVersion` exists only on the storage type. We need it here because we need to remember what version the customer created the CRD with so that we can use that version to submit it to ARM.
2. `APIVersion` doesn't exist on customer visible types: It's already set in `metav1.TypeInfo` on each resource, so we don't need it again inside each resource, it's duplicate information appearing at what looks like a weird level in the CRD.
3. `APIVersion` _is_ included in the JSON payload to ARM, because it's required to inform ARM about the specific APIVersion requested to create the resource.

**Comment by theunrepentantgeek** [comment]
We need a way to convert from what we have (the hub storage version) to the appropriate API version (as specified by a `APIVersion` property) so that we can generate the right ARM types.

I ran into this problem while working on [PR#455](https://github.com/Azure/k8s-infra/pull/455) and made the following comments in Teams:

> Thanks for the help Matthew - here's an update for everyone else ...
> We didn't see the problem before because the Storage Variants of resources were incorrectly referencing the API types for Spec and Status - and I've got that fixed in my PR.
> The Storage Variants (correctly) don't implement the conversion functions to ARM types, so the reconcile loop is failing
> Long term the fix is to allow the hub storage version to convert to the appropriate API type and use that to create the ARM type to submit, but this is a non-trivial piece of work
> For Alpha we can fake something up that will work, as long as our alpha only supports a single API type - but this has a prerequisite that the full storage conversion functions are available (my current PR is just storage helpers)
> For my current PR, I'll change it to flag the latest API version as the hub version (not the storage version we really want), bypassing the problem for now, unblocking the PR
