### ISSUE TITLE
Review use of Format Specifiers for potential information leakage

### ISSUE THREAD

**Issue by theunrepentantgeek** [Azure/azure-service-operator#1470]
The Go format specifier `%v` (and variations) can dump an entire struct into a log message, potentially resulting in information leakage (e.g. if the struct contains an API key or other secret).

We should identify which format specifiers might cause this kind of leakage and ensure we're only using them where it's safe and there's no alternative.

**Comment by matthchr** [comment]
Pulling this into milestone alpha-0 for the codegen as it feels easy to do and probably important.

**Comment by matthchr** [comment]
Decided to look through generic controller and libraries used code to ensure that we aren't doing any of this logging.
Can we do some sort of linter to prevent future use?
