### ISSUE TITLE
Change comment generation to put a space after `//`

### ISSUE THREAD

**Issue by theunrepentantgeek** [Azure/azure-service-operator#1472]
Our comments should include a space after `//` for readability.

Before we can make this change, we need our tooling to be fixed so that the leading space is not included in the generated CRDs.

- [x] Create an upstream PR for this fix
- [ ]  Merge the upstream PR
- [ ] Fix our comment generation

**Comment by Porges** [comment]
Should be fixed once we update to a newer `controller-tools`.

**Comment by matthchr** [comment]
We can now fix this.
