### ISSUE TITLE
Fix handling of "empty" types

### ISSUE THREAD

**Issue by matthchr** [Azure/azure-service-operator#1474]
There are a number of these that are due to conversion from Swagger where all of the fields of a type are read-only:

For example:
1. https://schema.management.azure.com/schemas/2019-03-01/Microsoft.Compute.Galleries.json 
    - GalleryProperties.Identifier
2. https://schema.management.azure.com/schemas/2019-07-01/Microsoft.Compute.json 
    - VirtualMachineIdentity.UserAssignedIdentities
Both of the above are types that are entirely readonly

This causes at least a few errors when controller-gen runs that come out looking like this:
```
/home/matthchr/work/github/k8s-infra/hack/generator/apis/microsoft.compute.galleries/v20180601/galleries_types.go:75:15: unsupported AST kind *ast.InterfaceType
```

**Comment by theunrepentantgeek** [comment]
Moving to `codegen-beta-0` milestone as we have a good-enough workaround for now (excluding the property); this may bite us later on though, so we still need to fix the issue.

**Comment by matthchr** [comment]
Can we close this in favor of #2084 @Porges?

**Comment by matthchr** [comment]
We still need to confirm that #2084 fixes this. I think it should but will leave this open until we can confirm.
