### ISSUE TITLE
Bug: Description of property 'storageAutogrow' is wrong

### ISSUE THREAD

**Issue by maggiexian** [Azure/azure-service-operator#1483]
**Describe the bug**
The description of property 'storageAutogrow' is wrong. 
https://github.com/Azure/azure-service-operator/blob/master/charts/azure-service-operator/crds/apiextensions.k8s.io_v1beta1_customresourcedefinition_mysqlservers.azure.microsoft.com.yaml#L216 
When I set the value to ''StorageAutogrowEnabled'' as the description suggested, the deploy failed with "Original Error: Code=\"InvalidStorageAutoGrow\" Message=\"Invalid Storage AutoGrow Value\" "

**Expected behavior**
It turns out the allowed values are "Enabled" and "Disabled". Please fix the property definition.

**Comment by theunrepentantgeek** [comment]
Thanks for the bug report @maggiexian.
