### ISSUE TITLE
Mysqluser Failure

### ISSUE THREAD

**Issue by 8572032049** [Azure/azure-service-operator#1487]
![image](https://user-images.githubusercontent.com/68789502/118697608-56a41900-b7c4-11eb-8990-e6775097aea0.png)
Im getting similar error. Tried to create a resource Mysqluser through Azure service operators and im getting the above error. Database and server is provisioned already.

**Comment by matthchr** [comment]
Hi @8572032049 - Can you gather the ASO manager container logs by running `kubectl logs` on the operator pod? The command should be something like:
`kubectl logs -n azureoperator-system azureoperator-controller-manager-7b4749bd7b-fsdcv manager`

There may be quite a lot of logs so you may want to redirect the logs to a file for easier sharing.

It would also help if you could show us the result of:
1. `kubectl get mysqluser -n monitoring kizy-breathless-devops-monitoring -o  yaml`
2. The `ownerReferences` section of `kubectl get secrets -n monitoring kizy-breathless-devops-monitoring -o yaml` - **please take care to not share the actual contents of the secret itself**, I just want to see the secret `metadata` about `ownerReferences`

**Comment by matthchr** [comment]
Closing this as there was no response. Feel free to reopen.
