### ISSUE TITLE
Ensure that the types we're generating are actually the latest version

### ISSUE THREAD

**Issue by matthchr** [Azure/azure-service-operator#1488]
The ARM JSON schemas don't necessarily have the latest API version types exposed via the `2015-05-01` specification which is what we're relying on today. We should ensure that we're actually generating the latest APIVersion for each type we're interested in, which may require use updating to use a newer "rollup version" of the JSON schema.

**Comment by Porges** [comment]
Something that might be useful would be a `latest` version specifier in the config YAML.
