### ISSUE TITLE
controller-gen doesn't support deeply nested maps

### ISSUE THREAD

**Issue by matthchr** [Azure/azure-service-operator#1489]
This comes up for example here:
`microsoft.machinelearning/v20170101/ExampleRequest` the `Inputs` field which has the type `map[string][][]map[string]v1.JSON` (after the pipeline stage that replaces AnyTypes).

**Comment by matthchr** [comment]
There's a PR out to support this [here](https://github.com/kubernetes-sigs/controller-tools/pull/569), which I think is based on @porges PR [here](https://github.com/kubernetes-sigs/controller-tools/pull/518)

**Comment by Porges** [comment]
My PR probably won’t fix this particular case: maps containing arrays are currently only allowed to have arrays of strings, which is a different restriction to the one that I am lifting.

**Comment by Porges** [comment]
Done!
