### ISSUE TITLE
Create a tool to perform old handcrafted ASO to new generated CRD conversion

### ISSUE THREAD

**Issue by matthchr** [Azure/azure-service-operator#1519]
Since CRDs will be in different groups, standard Kubernetes conversions won't work, but we don't want customers to have to manually mirror all of their resources.

This probably will be a run-once workflow something like:
1. Mark existing ASO resource as not reconciled (using existing tag we support whose name I forget).
2. Create a new ASO (generated) resource.
3. Delete old ASO resource.

We will need to be _really_ sure that deleting the old ASO resource (marked with no-reconcile) doesn't actually delete the underlying Azure resource.

**Comment by matthchr** [comment]
This is related to #1238 as well

**Comment by matthchr** [comment]
and #2119

**Comment by theunrepentantgeek** [comment]
We're going to create a tool that allows existing Azure resources to be imported as ASO custom resources - see #1238 and #2596 for details. Retaining this issue open until the tool is complete.

**Comment by theunrepentantgeek** [comment]
Closing in favour of #1238.
