### ISSUE TITLE
Improve ASO v2 documentation

### ISSUE THREAD

**Issue by matthchr** [Azure/azure-service-operator#1528]
There are various documentation failings that should be addressed early on in the codegen alpha process.

- [x] Combine README's in the repo. Today there are at least 3 (one at the root and 2 in `hack/`).
   - As long as the v2 install is separate, we should have an example of how to do it.
- [ ] What does the future hold? Migration from v1 to v2? What are our commitments to v2 alpha?
- [x] Add CONTRIBUTING.md for v2 and code generator
   - How to add resources?
   - How to run tests?
- [x] Add samples for all supported resource types.
   - Consider autogenerating these? Or auto-validating them against generated types?
- [ ] Explain the differences between v1 and v2
   - How versioning is done.
   - Resource suffix.
   - Single generic controller vs many handcrafted controllers.
- [ ] Provide documentation on each type/field for supported CRDs. Maybe via GitHub pages or something?
- [x] A list of supported resources in v2 (this is done but manually - we want automation for it eventually)
- [ ] Warning in the v1 resources that these are not the resources you're looking for

**Comment by harm-smits** [comment]
Hey @matthchr, perhaps consider adding a single definition file like ElasticSearch does as well (as this provides some very useful autocomplete for IDEs): https://download.elastic.co/downloads/eck/1.0.0/all-in-one.yaml

**Comment by matthchr** [comment]
@harm-smits we actually have this already I believe in the [ASO v2.0.0-alpha.0 release](https://github.com/Azure/azure-service-operator/releases/tag/v2.0.0-alpha.0) - take a look at `azureserviceoperator_v2.0.0-alpha.0.yaml`

**Comment by matthchr** [comment]
Closing this in favor of separate issues tracking each of the individual remaining items:
#1715 - "Provide documentation on each type/field for supported CRDs. Maybe via GitHub pages or something?"
#2062 - "What does the future hold? Migration from v1 to v2"
#2066 - "Warning in the v1 resources that these are not the resources you're looking for"
