### ISSUE TITLE
Feature: Add ability to expose eventHubNamespace secret 

### ISSUE THREAD

**Issue by bjartek** [Azure/azure-service-operator#1542]
In the guide https://docs.microsoft.com/en-us/java/api/overview/azure/spring-integration-eventhubs-readme?view=azure-java-stable they refer to the connection string for the namespace. Currently it is only possible to expose a secret for each eventhub. 

Request:
 - make it possible to expose a secret that has the connection string for the entire namespace

**Comment by theunrepentantgeek** [comment]
Thanks. We'll review this when planning our beta.

**Comment by matthchr** [comment]
@bjartek - Do you want access to the RootManageSharedAccessKey connection string, or to a connection string for a custom AuthorizationRule?

**Comment by matthchr** [comment]
Still curious as to the question above. This is planned but since EventHub recommends using managed identity I want to learn more about the requirements if possible before exposing this.

**Comment by bjartek** [comment]
Sorry for not following up, but I left my old job back in december and no longer work on this.

**Comment by nikawang** [comment]
> Still curious as to the question above. This is planned but since EventHub recommends using managed identity I want to learn more about the requirements if possible before exposing this.

Actually while using azure function, we always use connection string to the Azure PaaS.

**Comment by matthchr** [comment]
This is something we haven't gotten to yet but it sounds like it's worth doing based on the above comments.

**Comment by matthchr** [comment]
No change from above. I think this is actually also related to ASOv1 deprecation.
