### ISSUE TITLE
Add Support for frontdoor configuration

### ISSUE THREAD

**Issue by alexl2012** [Azure/azure-service-operator#1553]
I have only just come across this project and what a fantastic project this is, we had built there operators for ourselves as we needed them for frontdoor configuration and also api managment. it would be great if MS could support the frontdoor resource for this as well then we could use this and not have to worry about maintaining our application.;

**Comment by theunrepentantgeek** [comment]
Good idea. Added to our roadmap in #1192.

**Comment by matthchr** [comment]
We'd still like to do this

**Comment by theunrepentantgeek** [comment]
Relevant resources seem to be:

In `Microsoft.Network`:

* [FrontDoor](https://learn.microsoft.com/en-us/azure/templates/microsoft.network/frontdoors?pivots=deployment-language-arm-template)
* [FrontDoorWebApplicationFirewallPolicy](https://learn.microsoft.com/en-us/azure/templates/microsoft.network/frontdoorwebapplicationfirewallpolicies?pivots=deployment-language-arm-template)

In `Microosft.ApiManagement`: 

* [Service](https://learn.microsoft.com/en-us/azure/templates/microsoft.apimanagement/service?pivots=deployment-language-arm-template)

Plus a large number of subsidary resources.

**Comment by comptonad** [comment]
+1 for this. We have a strong interest in managing FrontDoor and ApiManagement resources.

**Comment by comptonad** [comment]
@matthchr Is there any estimate to when these resources might be addressed? Specifically the `FrontDoor` and its sub resources.

**Comment by matthchr** [comment]
This is done now (in 2.6.0) for Frontdoor standard, see [samples](https://github.com/Azure/azure-service-operator/blob/main/v2/samples/cdn/v1api20230501/v1api20230501_profile.yaml) (and the other files in that folder).

Closing this upon the assumption that AFD Standard is what you want. If you actually want AFD classic (Microsoft.network/frontdoor) please feel free to reopen.

**Comment by alexl2012** [comment]
Excellent thanks Matthew!

**Comment by matthchr** [comment]
Do note that 2.6.0 is not actually fully out yet (Helm chart yet to be merged, had an issue with image publishing last night which we are fixing today), so you may need to wait a day before you can actually use 2.6.0
