### ISSUE TITLE
Bug: Cannot install ASO in cluster that contains Windows nodes

### ISSUE THREAD

**Issue by morsik** [Azure/azure-service-operator#1560]
**Describe the bug**
Missing `nodeSelector` in Helm Chart: https://github.com/Azure/azure-service-operator/blob/master/charts/azure-service-operator/templates/generated/apps_v1_deployment_azureoperator-controller-manager.yaml

**To Reproduce**
Try to install ASO using Helm in cluster that contains Windows nodes. Have bad luck so Kubernetes deploys pod into Windows node and you cannot run ASO then.

**Expected behavior**
ASO should run correctly only on Linux nodes.

**Screenshots**
```
Events:
  Type     Reason       Age                   From               Message
  ----     ------       ----                  ----               -------
  Normal   Scheduled    27m                   default-scheduler  Successfully assigned azure-service-operator/azureoperator-controller-manager-5dbd9b9bbd-fvqcr to akswin000002
  Warning  FailedMount  24m                   kubelet            Unable to attach or mount volumes: unmounted volumes=[cert], unattached volumes=[cert default-token-dwgj9]: timed out waiting for the condition
  Warning  FailedMount  6m33s (x18 over 27m)  kubelet            MountVolume.SetUp failed for volume "cert" : secret "webhook-server-cert" not found
  Warning  FailedMount  4m35s (x9 over 22m)   kubelet            Unable to attach or mount volumes: unmounted volumes=[cert], unattached volumes=[default-token-dwgj9 cert]: timed out waiting for the condition
  Normal   Pulling      4m22s                 kubelet            Pulling image "gcr.io/kubebuilder/kube-rbac-proxy:v0.5.0"
  Warning  Failed       110s (x9 over 4m20s)  kubelet            Error: ImagePullBackOff
```

I can create PR for that, but I am not sure where since those YAMLs are generated(?) from somewhere else?

**Comment by matthchr** [comment]
Thanks for this bug report. This is definitely an issue. 

I _think_ the fix is to update the `kubebuilder` patch that is applied to the ASO `Deployment`, located [here](https://github.com/Azure/azure-service-operator/blob/master/config/default/manager_image_patch.yaml)

If you want to give that a shot, feel free. Otherwise we'll do that for the next release
