### ISSUE TITLE
Bug: PostgreSqlUser opens more and more connections

### ISSUE THREAD

**Issue by johgoe** [Azure/azure-service-operator#1576]
**Describe the bug**
User is created and permissions are granted. PGSqlConnection idles. During time more and more connections are created and all idles. It takes some time but then the database accepts no more connection because of 100 idle connections

**To Reproduce**
Create a PostgreSqlUser CR and wait for provisioned and a little bit more.

**Expected behavior**
User is created and permissions are granted. PGSqlConnection is closed.

**Screenshots**
![grafik](https://user-images.githubusercontent.com/1584475/122584143-49e04280-d05a-11eb-9667-0e93e4338bed.png)

**Additional context**
I guess the connections are from this part:

https://github.com/Azure/azure-service-operator/blob/master/pkg/resourcemanager/psql/psqluser/psqluser_reconcile.go

There are just a view users

![grafik](https://user-images.githubusercontent.com/1584475/122584188-58c6f500-d05a-11eb-81f7-719415ec5758.png)

**Comment by matthchr** [comment]
Thanks for the bug report @johgoe - this is a pretty bad bug. It also seems to impact more than just PostgreSQLUser (I think it also impacts the MySQL and AzureSQL flavors).

We'll be looking to get this fixed for the next release of ASO.
