### ISSUE TITLE
Improve generated typenames 

### ISSUE THREAD

**Issue by Porges** [Azure/azure-service-operator#1591]
**Describe the current behavior**
See: https://github.com/Azure/azure-service-operator/pull/1548#discussion_r647855845

Includes depluralization of parent type names when creating type names for subresources.

**Comment by Porges** [comment]
Marking as `alpha-1` since the generated names do not affect CRDs, only the intermediate/internal go code.

**Comment by theunrepentantgeek** [comment]
From #1459:

Consider performing the pluralization improvements step for spec and status of resources too.
Add a golden test for pluralization?

**Comment by theunrepentantgeek** [comment]
Whether we still need to do this depends on the results of #1758.

**Comment by matthchr** [comment]
Still need to do this, but not critical because we don't give code-dependency guarantees right now
