### ISSUE TITLE
Implement planned object structure improvements "operatorSpec"/"operatorStatus"

### ISSUE THREAD

**Issue by matthchr** [Azure/azure-service-operator#1612]
**Describe the current behavior**
We haven't implemented a stage for the spec described in #1504

**Describe the improvement**
Implement the spec described in #1504

**Comment by theunrepentantgeek** [comment]
Needs to be landed at the same time as #1471

**Comment by matthchr** [comment]
As part of this, we could possibly move the `PollerResumeID` and `PollerResumeToken` annotations to Status instead.
