### ISSUE TITLE
Feature: Allow configuration of json log format

### ISSUE THREAD

**Issue by cpflaume** [Azure/azure-service-operator#1620]
Currently all logs are written as plain text, e.g. 

`2021-07-05T01:54:16.492Z        INFO    controller-runtime.controller   Starting Controller     {"controller": "postgresqldatabase"}`

As logs will be processed most likely by a log processor like fluent bit and will be parsed and stored in a tool like Elasticsearch, it would be good to be able to log in json format. This makes it easier to integrate the logs in such a logging stack.

**Comment by theunrepentantgeek** [comment]
Good idea. We'll investigate this for beta.

**Comment by Porges** [comment]
We are already using `klog` so this should be easy: https://kubernetes.io/blog/2020/09/04/kubernetes-1-19-introducing-structured-logs/

**Comment by matthchr** [comment]
See @Porges comment as well

> Something I noticed for the logger is that there’s already a ctrl.ForContext that supposedly fills out some controller-specific values. Perhaps we should be invoking this to be more “standard” with what is contained in the structured logs.

**Comment by matthchr** [comment]
We still want to do this but haven't had a chance yet.

**Comment by theunrepentantgeek** [comment]
Still something we want to do.

**Comment by matthchr** [comment]
Still interested in this.
