### ISSUE TITLE
Bug: APIMgmt does not update existing APIs

### ISSUE THREAD

**Issue by huyffs** [Azure/azure-service-operator#1645]
**Describe the bug**
APIMgmt ignores changes in the spec if API already exits

**To Reproduce**
* Create an API
* Change the spec properties
* Run ASO again

**Expected behavior**
Expected changed properties to be applied

**Screenshots**
| <img width="719" alt="Screenshot 2021-07-13 at 21 34 42" src="https://user-images.githubusercontent.com/1257494/125461932-458650d1-7d7d-4399-a8da-7d83723adb37.png"> |
|:--:|
|This screenshot shows live manifest in ArgoCD, which is not reflective of the actual data in APIM|

**Additional context**
This bit of logic prevents execution of `apimanagement. CreateOrUpdate`  if the API already exists [/pkg/resourcemanager/apim/apimgmt/apimgmt.go](https://github.com/Azure/azure-service-operator/blob/master/pkg/resourcemanager/apim/apimgmt/apimgmt.go#L133)

**Comment by matthchr** [comment]
This is a known issue. ASOv1 is in maintenance mode so it's unlikely that this gets fixed unless there's a significant outcry for it.
We will leave this open for tracking for now.
