### ISSUE TITLE
Bug: Setting PostgreSQLServer sku size (storage) has no effect

### ISSUE THREAD

**Issue by cpflaume** [Azure/azure-service-operator#1647]
**Describe the bug**
Using the sample [here](https://github.com/Azure/azure-service-operator/blob/master/config/samples/azure_v1alpha1_postgresqlserver.yaml) a postgresql server can be deployed with the defined parameters.

When I try it with another sku size, it does not have any affect.

**To Reproduce**
1. Use the sample and change the storage size to 102400. I tried 10240 as well, as this is what it is shown in the JSON definition in the Azure Portal.
2. Apply the sample yaml.
3. A postgresql server with 5GB storage is provisioned.

**Expected behavior**
A postgresql server witth 10GB is provisioned.

Looking at the Json definition in the azure portal is wonder, if sku is the right place to define the storage size:
```
  "sku": {
    "name": "GP_Gen5_4",
    "tier": "GeneralPurpose",
    "family": "Gen5",
    "capacity": 4
  },
  "properties": {
    "administratorLogin": "XXXXX",
    "storageProfile": {
      "storageMB": 5120,
      "backupRetentionDays": 7,
      "geoRedundantBackup": "Disabled",
      "storageAutogrow": "Disabled"
    },
```

**Comment by matthchr** [comment]
`sku.size` (which is what is set in the example you linked) is for `sku.size`, which I don't think is about capacity.

`StorageProfile.storageMB` (in v1alpha2) is what configures how much storage the server has. Use v1alpha2 and set that property to change the storage size in the server.

See the example [here](https://github.com/Azure/azure-service-operator/blob/main/config/samples/azure_v1alpha2_postgresqlserver.yaml).
