### ISSUE TITLE
The problem that we are experiencing is with version 1.18.14 in our pre-prod environment

### ISSUE THREAD

**Issue by ssbandari1** [Azure/azure-service-operator#1668]
Azureoperator is successfully installed in both Sandbox and Production subscriptions.  However, we have struggled for the last 4 days with getting the azureoperator pods to run successfully in the pre-prod environment on version 1.18.14.  
We have upgrade to 1.18.19 with the hopes of resolving the issue in the pre-prod environment.  However, the same issue remains!

Is it possible to get assistance from someone with expertise in this area to help with the issue we are facing?

**Comment by babbageclunk** [comment]
After an email conversation it seems like this might have been a problem with the API server - the user had torn down the cluster to recreate so we couldn't do any more investigation. Closing this for now.
