### ISSUE TITLE
Bug: Deleting and recreating resource while KeyVault soft delete is enabled causes an error

### ISSUE THREAD

**Issue by matthchr** [Azure/azure-service-operator#1686]
**Describe the bug**
If ASO is configured to store secrets in KeyVault, and that KeyVault has SoftDelete enabled, then when an ASO resource is deleted and recreated with the same name an error will occur because the newly created resource is unable to create a secret with the same name as a currently soft-deleted secret.

**To Reproduce**
1. Use KeyVault for secret storage.
2. Enable soft delete in the KeyVault.
3. Create any resource with a secret (AzureSQLServer for example).
4. Delete that resource
5. Create the same resource again
6. Observe the error

**Expected behavior**
The recreation of a previously deleted resource works.

**Comment by qike-ms** [comment]
This is a known issue due to long deletion latency after soft deletion. AKS had a sev1 outage due to that. You need to 1) issue purge after deletion; 2) before creation, check key status.

**Comment by matthchr** [comment]
@qike-ms - Yep, I'm adding two options to the operator, one to Purge after delete, and one to Recover if create fails with the "KeyIsSoftDeleted" error. Users can choose which one to use (some users don't want to give the operator purge permissions)
