### ISSUE TITLE
Bug: Status types don't understand Swagger discriminator and so are missing fields

### ISSUE THREAD

**Issue by matthchr** [Azure/azure-service-operator#1722]
**Describe the bug**
When the Swagger specification has a type which is modelling inheritance, such as [Cosmos DB BackupPolicy](https://github.com/Azure/azure-rest-api-specs/blob/main/specification/cosmos-db/resource-manager/Microsoft.DocumentDB/stable/2021-05-15/cosmos-db.json#L8392), the Status types don't realize this and end up generating a type that looks like:
```go
//Generated from:
type BackupPolicy_Status struct {
	// +kubebuilder:validation:Required
	Type BackupPolicyType_Status `json:"type"`
}
```

**Expected behavior**
These types should probably be modelled in k8s as a [Kubernetes union type](https://github.com/kubernetes/enhancements/blob/master/keps/sig-api-machinery/1027-api-unions/README.md), which is basically a type with a discriminator and N mutually exclusive properties.

**Comment by matthchr** [comment]
This is the "Status side" of #1721

**Comment by matthchr** [comment]
@porges did your PR #1912 solve this?

**Comment by matthchr** [comment]
@porges Can you confirm if this is actually still an issue?

**Comment by theunrepentantgeek** [comment]
Resolving as fixed. In the current Swagger WIP branch, `BackupPolicy` is correctly turned into a union type as we want.

In `api\documentdb\v1beta20210515\database_account_types_gen.go` we have:

``` go
type BackupPolicy struct {
	// Continuous: Mutually exclusive with all other properties
	Continuous *ContinuousModeBackupPolicy `json:"continuous,omitempty"`

	// Periodic: Mutually exclusive with all other properties
	Periodic *PeriodicModeBackupPolicy `json:"periodic,omitempty"`
}
```

Matching this, in `api\documentdb\v1beta20210515\database_account_spec_arm_types_gen.go` we have:

``` go
type BackupPolicy_ARM struct {
	// Continuous: Mutually exclusive with all other properties
	Continuous *ContinuousModeBackupPolicy_ARM `json:"continuous,omitempty"`

	// Periodic: Mutually exclusive with all other properties
	Periodic *PeriodicModeBackupPolicy_ARM `json:"periodic,omitempty"`
}
```

which in turn has the desired `MarshalJSON` and `UnmarshalJSON` methods:

``` go
// MarshalJSON defers JSON marshaling to the first non-nil property, because BackupPolicy_ARM represents a discriminated union (JSON OneOf)
func (policy BackupPolicy_ARM) MarshalJSON() ([]byte, error) {
	if policy.Continuous != nil {
		return json.Marshal(policy.Continuous)
	}
	if policy.Periodic != nil {
		return json.Marshal(policy.Periodic)
	}
	return nil, nil
}

// UnmarshalJSON unmarshals the BackupPolicy_ARM
func (policy *BackupPolicy_ARM) UnmarshalJSON(data []byte) error {
	var rawJson map[string]interface{}
	err := json.Unmarshal(data, &rawJson)
	if err != nil {
		return err
	}
	discriminator := rawJson["type"]
	if discriminator == "Continuous" {
		policy.Continuous = &ContinuousModeBackupPolicy_ARM{}
		return json.Unmarshal(data, policy.Continuous)
	}
	if discriminator == "Periodic" {
		policy.Periodic = &PeriodicModeBackupPolicy_ARM{}
		return json.Unmarshal(data, policy.Periodic)
	}

	// No error
	return nil
}
```
