### ISSUE TITLE
Tests need support for simulated errors

### ISSUE THREAD

**Issue by matthchr** [Azure/azure-service-operator#1726]
We should cover various corner cases being able to inject certain failures. Some of this should be achievable using our existing envtest + recording framework and some may need some additional framework updates.

Ideas:
- [ ] ~DeploymentAlreadyExists when we attempt to create it?~
- [ ] ~InternalServerError for a period of time from a service.~
- [ ] ~"Create" a resource that the operator doesn't know about but which already exists.~
- [x] Deployment is rejected due to 4xx level error.
- [x] Deployment is accepted but fails later due to 4xx level error.
- [ ] ~Deployment fails after some polling due to 5xx error.~
- [ ] ~Throttling from a service.~
- [ ] ~Simulated errors saving changes to spec or status (kube-apiserver instability)~
- [ ] ~Simulated loss of entire status~

Remaining issues moved to #2164

**Comment by sakthi-vetrivel** [comment]
Need to split into multiple issues across milestones

**Comment by theunrepentantgeek** [comment]
Closing to keep a record of completed tests; see #2164 for remaining work.
