### ISSUE TITLE
Not all resources implement ResourceBase

### ISSUE THREAD

**Issue by matthchr** [Azure/azure-service-operator#1730]
**Describe the current behavior**
The resource manager schema implies that all resources implement `resourceBase`, which has `tags` and a few other properties. This is not correct though, there are multiple "kinds" of ARM resources and some of the (Proxy) don't have to support `tags`. See [this](https://armwiki.azurewebsites.net/rp_onboarding/tracked_vs_proxy_resources.html) for details.

**Describe the improvement**
The Swagger specifications seem to correctly encode this information, see for example the [ASK AgentPool](https://github.com/Azure/azure-rest-api-specs/blob/main/specification/containerservice/resource-manager/Microsoft.ContainerService/stable/2021-07-01/managedClusters.json#L2593) resource which doesn't support `tags` according to Swagger, but which incorrectly is marked as supporting `tags` according to the resource manager schema JSON document.

We should stop forcing all types to inherit these `ResourceBase` properties, as not all of them do.

**Comment by matthchr** [comment]
See https://github.com/Azure/azure-resource-manager-schemas/issues/1850

**Comment by matthchr** [comment]
This is fixed by #2084, probably we can close this

**Comment by theunrepentantgeek** [comment]
Verified as fixed in #2323
