### ISSUE TITLE
Consider using gopter arbitary to simplify generated generators

### ISSUE THREAD

**Issue by theunrepentantgeek** [Azure/azure-service-operator#1743]
**Describe the current behavior**

We are currently explicitly emitting a generator for each property for use in our property tests.

**Describe the improvement**

We may be able to dramatically simplify the generated code by using the support for arbitrary generators, which use reflection to identify the properties. 

**Additional context**

Suggested by @matthchr during a review of PR #1727

**Comment by matthchr** [comment]
This is something we'd like to look into at some point, but not really any rush on it

**Comment by matthchr** [comment]
No status change from above -- nice to have

**Comment by matthchr** [comment]
Closing this in favor of https://github.com/Azure/azure-service-operator/issues/3839
