### ISSUE TITLE
Bug: Status types with properties overlapping with ResourceBase (name, type, etc) seem to have nondeterministic comments

### ISSUE THREAD

**Issue by matthchr** [Azure/azure-service-operator#1757]
I _think_ this only applies to Status types but I'm not 100% sure. An example was:
![image](https://user-images.githubusercontent.com/8798850/131194282-57a08178-39d8-40ee-a070-3dd5daa973ed.png)

**Comment by Porges** [comment]
We probably need to handle this in the `allof` merging, we must be picking one side at the moment.

**Comment by matthchr** [comment]
Reopening this as it seems there is at least something causing thsi still

**Comment by Porges** [comment]
Fixed by #1841
