### ISSUE TITLE
Add fullyQualifiedUsername to MySQLUser secret

### ISSUE THREAD

**Issue by kyschouv** [Azure/azure-service-operator#1771]
**Describe the current behavior**
`MySQLServer` secrets include a `fullyQualifiedUsername` value. `MySQLUser` secrets do not, and the value must be created by combining the `username` with the `mySqlServerName`. It would be nice to not have to do that, especially as it can be difficult to compose and apply depending on the usage (e.g. a Helm chart may not be set up to define environment variables for username and server name and then later combine them into a fully qualified user name).

**Describe the improvement**
Add `fullyQualifiedUsername` to the secret generated for a `MySQLUser`.

**Comment by theunrepentantgeek** [comment]
v1 is in maintenance mode, so we won't be making a change there.

However, we need to be aware of this issue for v2, as we need to avoid replicating the problem there.

**Comment by matthchr** [comment]
Somewhat related to #2555

**Comment by matthchr** [comment]
Closing this in favor of the more generic #2555. That issue may not be solved for a little while yet (we need to think about it), so if there's an explicit need for this field or one like it on an ASOv2 resource feel free to open a new issue for that and we may be able to action that specific one.
