### ISSUE TITLE
Add a test that installs a newly-built helm chart

### ISSUE THREAD

**Issue by babbageclunk** [Azure/azure-service-operator#1772]
**Describe the current behavior**
The current helm-install test installs the built tgz chart. This is useful for cases where someone has forgotten to run `make helm-chart-manifests` after changing the chart files (I did this yesterday), but it means that if there's an error in one of the templates in the chart they'll only be found when someone updates the helm chart after a release.

**Describe the improvement**
We need another test that builds and installs the chart from the current chart files so that errors in templates can be found in that PR, rather than potentially much later.

**Comment by matthchr** [comment]
ASOv1 is in maintenance mode and so we will not be doing this for it. Taking this issue over to track the same problem in v2
