### ISSUE TITLE
Code generation for Cosmos DB SQL database resource failed

### ISSUE THREAD

**Issue by abhirockzz** [Azure/azure-service-operator#1780]
**Describe the bug**

Followed [these steps](https://github.com/Azure/azure-service-operator/blob/master/docs/v2/adding-new-codegenerated-resource.md) to add support for Cosmos DB SQL database resource. It failed with the following message:

```
[controller:generate-types] E0903 19:30:00.201110   59339 gen_kustomize.go:71] Error during code generation:
[controller:generate-types] failed during pipeline stage 22/46: Replace cross-resource references with genruntime.ResourceReference: "github.com/Azure/azure-service-operator/hack/generated/apis/microsoft.documentdb/v1alpha1api20210515/SqlDatabaseResource.Id" looks like a resource reference but was not labelled as one. It might need to be manually added to `newKnownReferencesMap`
task: Failed to run task "controller:quick-checks": task: Failed to run task "controller:generate-types": exit status 1
```

**To Reproduce**

- finished developer setup as per https://github.com/Azure/azure-service-operator/blob/master/hack/CONTRIBUTING.md#developer-setup-with-vs-code
- added following entry to `hack/generator/azure-arm.yaml`

```
  - action: include-transitive
    group: microsoft.documentdb
    version: v*api20210515
    name: DatabaseAccountsSqlDatabase
    because: "including Cosmos DB SQL DB resource"
```

- Run `task` to generate resource

**Expected behavior**
New resource should have been added in the `apis` directory i.e. `/hack/generated/apis/microsoft.documentdb/v1alpha1api20210515/`

**Screenshots**
NA

**Additional context**

ARM template JSON schema - https://schema.management.azure.com/schemas/2021-05-15/Microsoft.DocumentDB.json

**Comment by theunrepentantgeek** [comment]
@matthchr Can you confirm that adding the required property to `newKnownReferencesMap` is the only required change?

**Comment by matthchr** [comment]
Yes, I believe you need to follow the instructions (which I've just added) in #1788. Sorry about that!

Excited to see people interested in trying this. Let us know if you have any other issues.

**Comment by matthchr** [comment]
I'm going to go ahead and close this because I believe the above should solve your issue - feel free to reopen this (or file a new issue if you run into another problem).
