### ISSUE TITLE
Unable to run the operator locally

### ISSUE THREAD

**Issue by abhirockzz** [Azure/azure-service-operator#1820]
**Describe the bug**
Unable to run the operator locally using `kind`

**To Reproduce**

- git clone https://github.com/Azure/azure-service-operator/
- opened the project using VS Code (devcontainers) as per - https://github.com/Azure/azure-service-operator/blob/master/hack/CONTRIBUTING.md#developer-setup-with-vs-code
- tried to run it locally as per - https://github.com/Azure/azure-service-operator/blob/master/hack/CONTRIBUTING.md#running-the-operator-locally
- `task controller:kind-create` failed. see details below

```
task: [controller:kind-create] export KIND_CLUSTER_NAME=asov2 && ./scripts/kind-with-registry.sh
[controller:kind-create] Creating cluster "asov2" ...
[controller:kind-create]  • Ensuring node image (kindest/node:v1.21.1) 🖼  ...
[controller:kind-create]  ✓ Ensuring node image (kindest/node:v1.21.1) 🖼
[controller:kind-create]  • Preparing nodes 📦   ...
[controller:kind-create]  ✓ Preparing nodes 📦 
[controller:kind-create]  • Writing configuration 📜  ...
[controller:kind-create]  ✓ Writing configuration 📜
[controller:kind-create]  • Starting control-plane 🕹️  ...
[controller:kind-create]  ✗ Starting control-plane 🕹️
[controller:kind-create] ERROR: failed to create cluster: failed to remove master taint: command "docker exec --privileged asov2-control-plane kubectl --kubeconfig=/etc/kubernetes/admin.conf taint nodes --all node-role.kubernetes.io/master-" failed with error: exit status 1
[controller:kind-create] 
[controller:kind-create] Command Output: error: stat /etc/kubernetes/admin.conf: no such file or directory
task: Failed to run task "controller:kind-create": exit status 1
```

**Expected behavior**
Expected `task controller:kind-create` to create a `kind` cluster and local Docker registry

**Screenshots**
NA

**Additional context**
NA

**Comment by matthchr** [comment]
Can you share more details about your environment? Are you running in WSL2? I believe @porges mentioned he also gets this issue, so I'm thinking it might have something to do with the environment the container is being hosted in. It works for me in a full Ubuntu VM, but if you're in WSL that doesn't help.

**Comment by matthchr** [comment]
@babbageclunk is going to take a look at this some more

**Comment by matthchr** [comment]
Our automated tests that use `kind` can be run locally. Possibly this was something with an old set of dependencies not working, or some other problem that has since been resolved. Closing this for now. If you see it again please reopen or file a fresh issue.
