### ISSUE TITLE
Allow customization of the user agent

### ISSUE THREAD

**Issue by theunrepentantgeek** [Azure/azure-service-operator#1827]
Provide the ability to add segments to the user-agent via command line args in the controller.

Originally suggested by @devigned in #1469

**Comment by matthchr** [comment]
This still seems interesting - adding to beta.2

**Comment by matthchr** [comment]
Users wanted to be able to tell which of multiple ASO's in the cluster was triggering calls. Probably worth keeping and investigating.

**Comment by matthchr** [comment]
This would be nice to have but not critical for the 2.0.0 release.

**Comment by theunrepentantgeek** [comment]
Still would be good to have.

**Comment by matthchr** [comment]
Pulled forward to 2.4.0. Might be nice to have for tracking CAPZ vs ASO native usage

**Comment by nojnhuh** [comment]
I can take this one.
