### ISSUE TITLE
Bug: No Azure SQL secret in k8s after created SQL server

### ISSUE THREAD

**Issue by holooloo** [Azure/azure-service-operator#1919]
**Describe the bug**
You wrote: 
Along with creating the SQL server, this operator also generates the admin username and password for the SQL server and stores it in a kube secret with the same name as the SQL server.

I dont see any secrets in k8s except in Azure Vault

**To Reproduce**
https://github.com/Azure/azure-service-operator/blob/master/docs/v1/services/azuresql/azuresql.md#azure-sql-server

**Expected behavior**
I have to see secrets of Azure SQL Server in kubernetes

**Screenshots**

**Additional context**

**Comment by matthchr** [comment]
ASOv1 is in maintenance mode and this is fixed in ASOv2, so closing this issue. ASOv2 also has a clearer secrets model so it should be more obviously where the secret is coming from (in the case of SQL you must specify it rather than ASO generating it).
