### ISSUE TITLE
Consider renaming our annotations to match `prefix/name`

### ISSUE THREAD

**Issue by babbageclunk** [Azure/azure-service-operator#1970]
**Describe the current behavior**
At the moment the v2 operator uses three annotations:
* `poller-resume-token.azure.com`
* `resource-id.azure.com`
* `azure.microsoft.com/operator-namespace`

**Describe the improvement**
The [Kubernetes docs](https://kubernetes.io/docs/concepts/overview/working-with-objects/annotations/#syntax-and-character-set) say annotation names should be `prefix/name` - we should probably make ours match that. The current names for poller-resume-token and resource-id work fine, but conceivably if someone is using a tool that looks at annotations in their cluster the fact that some of ours don't seem to have a name might cause some confusion.

Maybe make all of them `azure.com/name`?

**Comment by matthchr** [comment]
`serviceoperator.azure.com` is what we were using for our finalizer. I think that's good as it distinguishes us from some other `azure.com` project.
