### ISSUE TITLE
Consider removing `microsoft.` prefix from v2 resource API groups

### ISSUE THREAD

**Issue by babbageclunk** [Azure/azure-service-operator#1971]
**Describe the current behavior**
The generated resources have API groups like `microsoft.documentdb.azure.com` or `microsoft.compute.azure.com` - these come from the generated golang package name for the resources. The `microsoft.` prefix makes sense in the package, but not really in the API group. It also reads a bit awkwardly because the most-specific element is the second - if we keep it it should be `compute.microsoft.azure.com`.

**Describe the improvement**
We could remove `microsoft.`. Are we planning on supporting `Sendgrid.Email`? If we do we could still keep the `sendgrid.` prefix in that case, although there's no `Microsoft.Email`.

**Comment by babbageclunk** [comment]
Adding this here since it has backwards compatibility impact - would be much easier to do now than later.

**Comment by babbageclunk** [comment]
Sorry about all the weird churn on this issue, I'm having a confused afternoon - started typing a comment, then decided I didn't need to and hit "Close issue" thinking of it like "Cancel" on a review comment. It is different.

**Comment by matthchr** [comment]
We agree that this is something we should do. This is a breaking change though so we will need to make sure that it's documented well (that's why we've picked beta-0 as the milestone as well)
