### ISSUE TITLE
Specify administrator username for the Postgresql server

### ISSUE THREAD

**Issue by hmi12** [Azure/azure-service-operator#1987]
**Describe the current behavior**
With ASO,  the default admin username for PostgreSQL is randomly generated.

**Describe the improvement**
For ASO, Can we specify the admin username for PostgreSQL?  Wth OSBA, we can specify the username by set the string: **adminAccountSettings.adminUsername** 

**Additional context**
Add any other context about the suggested improvement.

**Comment by babbageclunk** [comment]
We're currently designing how secrets will be handled in the v2 operator - see #1989 for details.

**Comment by matthchr** [comment]
This will be fixed in beta-0 of ASOv2. We aren't currently planning on backporting the ability to do this into ASOv1.

**Comment by matthchr** [comment]
ASOv2 beta.0 has been released, closing this as this is supported there.
