### ISSUE TITLE
Feature: ASOv2 should support per resource type error handling overrides

### ISSUE THREAD

**Issue by matthchr** [Azure/azure-service-operator#1997]
There are some error codes returned from Azure that have somewhat ambiguous meaning. One of them is `BadRequest`. It often means that a request is fatally formed and cannot ever succeed, but there are certain services where it doesn't always mean that, for example in CosmosDB that code is returned when attempting to create a database at the same time as the parent DatabaseAccount, which _should_ be retried.

The solution is to have customizable error handling for these special cases.

**Comment by matthchr** [comment]
Related to #1978 maybe?

**Comment by super-harsh** [comment]
Does #2064 solve this?

**Comment by matthchr** [comment]
It does @super-harsh, but I believe @theunrepentantgeek mentioned something about actually adding a specific extension for that case and dealing with the particular resources we've found that need the extension. We might want to leave this open to track that.
