### ISSUE TITLE
Is ASOv2 generally available?

### ISSUE THREAD

**Issue by yusaito04** [Azure/azure-service-operator#2005]
Hello everyone,

I read [this article](https://azure.microsoft.com/ja-jp/updates/azure-service-operator-v2-release-is-now-generally-available/) and according to it, ASO v2 is generally available now.
However, when I checked the release page, I found that only alpha-releases are available and it states that this version is not supported.
I want to know what this means. Does it mean that the alpha releases are available as GA?

**Comment by matthchr** [comment]
No @yusaito04 it's not really generally available, the article you see used incorrect language. Thank you for asking, we will be correcting that article shortly.

ASO v2 is currently in alpha and as mentioned on our readme we follow the [Kubernetes definition of alpha](https://kubernetes.io/docs/reference/command-line-tools-reference/feature-gates/#feature-stages). Our current plan is to move to beta sometime early next year. Once that happens, we consider:
> The feature is well tested. Enabling the feature is considered safe.
> Support for the overall feature will not be dropped, though details may change.

Which means it will be suited for many production scenarios. While technically this is also true for beta features:

> The schema and/or semantics of objects may change in incompatible ways in a subsequent beta or stable release. When this happens, we will provide instructions for migrating to the next version. This may require deleting, editing, and re-creating API objects. The editing process may require some thought. This may require downtime for applications that rely on the feature.

we will be striving hard to avoid such changes once in beta.

**Comment by yusaito04** [comment]
Thank you for your reply, and I understood for it.

> Our current plan is to move to beta sometime early next year. 
My colleagues and I are looking forward to it very much.
