### ISSUE TITLE
Determine v1 to v2 migration plan

### ISSUE THREAD

**Issue by matthchr** [Azure/azure-service-operator#2062]
We've talked about creating a way to automatically export/import V1 resources to V2 resources. A number of customers have asked for a way to bulk import a whole hierarchy of Azure resources as well. These two things seem to be possibly related.

Once we have a story for v1 -> v2, we also need to document it well so that customers can follow it.

**Comment by sakthi-vetrivel** [comment]
Should be solved by import resources #1238
