### ISSUE TITLE
Deprecate CRDs when Azure offerings deprecations are announced

### ISSUE THREAD

**Issue by sakthi-vetrivel** [Azure/azure-service-operator#2070]
Today, there's no change to the support for an Azure Service Operator CRD when the underlying Azure service/offering is being deprecated. How should we communicate these deprecations and what timelines should we follow? How will we keep our catalog up to date?

**Comment by theunrepentantgeek** [comment]
We may not be able to automate this, but it's a good idea to do something.

**Comment by matthchr** [comment]
This is still in our backlog, but not high priority because services aren't deprecated regularly.

**Comment by matthchr** [comment]
Still in our backlog. We also need documentation on what exactly our policy is here.
