### ISSUE TITLE
Error on unexpected configuration

### ISSUE THREAD

**Issue by theunrepentantgeek** [Azure/azure-service-operator#2081]
**Describe the current behavior**

Extra values in our configuration files are currently silently ignored, which may result in confusion when users add new details that end up having no effect.

Discovered when @theunrepentantgeek removed support for `ExportFilters` in PR #2071 and no error was triggered when reading configuration.

**Describe the improvement**

We should abort with an error if our configuration file contains any sections or values that we don't recognise.

**Comment by matthchr** [comment]
There is an option in json deserialization to specifically check for this and error if fields are specified that don't actually exist on the underlying object. Maybe there's the same for YAML?
