### ISSUE TITLE
Improve documentation for when submodule references are stale

### ISSUE THREAD

**Issue by theunrepentantgeek** [Azure/azure-service-operator#2091]
**Describe the current behavior**

A common error is to fail to update our git submodules after doing a pull, which can result in the local working folder being stale. This in turn can result in errors like this one when the generator is run:

```
E0211 14:19:54.561995   27841 gen_kustomize.go:111] Error during code generation:
failed during pipeline stage 23/57: 
Verify there are no ErroredType's containing errors: 
"github.com/Azure/azure-service-operator/v2/api/network/v1alpha1api20180901/PrivateDnsZone" has property "Status" with errors:
"missing status information for github.com/Azure/azure-service-operator/v2/api/network/v1alpha1api20180901/PrivateDnsZones"
```
(Message has been formatted for readability.)

Even if this particular message isn't caused by stale submodule references, this has happened frequently in the past.

**Describe the improvement**

We need to improve our documentation so that someone searching our repo for this error can find guidance.

**Comment by theunrepentantgeek** [comment]
We should still do this.

**Comment by matthchr** [comment]
Probably should still do this
