### ISSUE TITLE
Bug: example rediscache deployment fails

### ISSUE THREAD

**Issue by paulczar** [Azure/azure-service-operator#2097]
**Version of Azure Service Operator**

deployed from operatorhub - mcr.microsoft.com/k8s/azureserviceoperator:1.0.28631

**Describe the bug**

[Deploy the example resource](https://github.com/Azure/azure-service-operator/blob/main/examples/demo/azure-vote-app-redis.yaml#L42-L47), it spins up the redis server, but the secret does not contain the required field `redisCacheName`.

**To Reproduce**

deploy the above example

**Expected behavior**

it should work.

**Comment by theunrepentantgeek** [comment]
For ASO v2 we are looking to automatically test our samples as a part of CI to ensure they work properly; however, ASO v1 is in maintenance mode only, so we won't be updating its samples.
