### ISSUE TITLE
QUESTION Secrets

### ISSUE THREAD

**Issue by jiwanovski87** [Azure/azure-service-operator#2158]
Since the `Azure Service Operator` is designed to support GitOps I am wondering how we can retrieve `secrets` which are generated.

**Example:** 
We are publishing a service which needs a redis `cache` and we need to put the information into a `secret` / `configmap` and mount these as volumes into the `deployment` of our service. In our config file we need to put in a `CacheKey` to access the redis `cache`.

So we have following resources defined in helm (a bit simplyfied):
- ConfigMap which represents the config file for our service
- Cache CRD
- Deployment with a mountVolume referencing the ConfigMap

As far as I have seen in the [documentation](https://azure.github.io/azure-service-operator/design/secrets/) we need to call the `ListKeys` endpoit and need to develope an own hook... Is there any more detailed example or description?

**Comment by matthchr** [comment]
This is a good reminder for me though, before beta0 comes out I'll write up better user-facing documentation for this, as it's not explained well at all.

**Comment by jiwanovski87** [comment]
@matthchr this sounds good :)
Do you already have an estimated date for `ASO beta-0`?

**Comment by matthchr** [comment]
Of course, it took longer than 2 weeks... but beta.0 is out now! Closing this as this is supported there. See [how to retrieve secrets created by Azure](https://azure.github.io/azure-service-operator/introduction/secrets/#how-to-retrieve-secrets-created-by-azure)

I have an example for `cache` in PR #2236.
