### ISSUE TITLE
Auto-create PR for ASOv2 helm chart and API docs

### ISSUE THREAD

**Issue by super-harsh** [Azure/azure-service-operator#2160]
**Describe the current behavior**

Currently we have to manually generate helm chart and API docs and create a PR for them for each release. 

**Describe the improvement**

To improve the above issue we can automate the process to generate helm manifest and API docs, then get a PR created. We have a few options below to tackle this:

1. Create a new workflow for above which runs after create-release workflow
2. Add a step in create-release workflow to automate above.
3. Create a new scheduled workflow to update the above weekly
4. 1 AND 3
5. 2 AND 3

**Comment by matthchr** [comment]
Seems like option 1 makes the most sense based on discussion
