### ISSUE TITLE
Bug: Incorrect code generated for object conversion with shared sub-objects

### ISSUE THREAD

**Issue by theunrepentantgeek** [Azure/azure-service-operator#2193]
**Describe the bug**

We're generating incorrect code when a shared object is present across more versions than the resource being handled.

To illustrate, consider the following:

![adr-2022-02-shared-resources-initial dot](https://user-images.githubusercontent.com/1272094/160306701-3dbe4520-f346-44f1-ba67-405f3083ffb4.png)

While the resource `Person` exists in only versions **v1** and **v3**, the shared object `Location` _also_ exists in **v2**.

When generating the `AssignTo()` and `AssignFrom()` methods for `v1.Person` we correctly use `v3.Person` as the destination and source, allowing the conversion to work. (Issue #2185 documents the problems we encountered when conversions wouldn't jump unused versions).

However, those conversions are currently assuming that the `AssignTo()` and `AssignFrom()` methods on `v1.Location` should be passed the `Residence` from `v3.Person` - but that's a `v3.Location`.

The generated code doesn't compile, because the `AssignTo()` and `AssignFrom()` methods on `v1.Location` expect a `v2.Location`, not a `v3.Location`.

This was discovered when generating code for both `Redis` and `RedisEnterprise` from the `cache` group.

Another way to look at this is that we're currently assuming that both `Person` and `Location` have the same set of versions in their conversion graph. When this isn't the case, incorrect code is generated.

**Expected behavior**

Conversion between `v1.Location` and `v3.Location` should happen via the intermediate type `v2.Location`.

**Comment by matthchr** [comment]
> This was discovered when generating code for both Redis and RedisEnterprise from the cache group.

Do you recall the particular properties that were causing this? I'm just curious because it's a bit surprising/strange and I wanted to take a look at their spec directly to understand what it is they are doing that causes this pattern.
