### ISSUE TITLE
Encryption at rest support for PostgreSQL database

### ISSUE THREAD

**Issue by sakthi-vetrivel** [Azure/azure-service-operator#2206]
Support ability to enable encryption at rest for a PostgreSQL database through Azure Service Operator.

**Comment by matthchr** [comment]
I think this is just an option in their REST API? We need to make sure you can do this in the initial PUT

**Comment by theunrepentantgeek** [comment]
According [this blog post on Azure PostgreSQL](https://azure.microsoft.com/en-us/blog/securing-azure-database-for-mysql-and-azure-database-for-postgresql/), data is always encrypted at rest - unencrypted data is not an option.

> All data stored by the service is secured via the [Azure Storage Service](https://docs.microsoft.com/en-us/azure/storage/common/storage-service-encryption) through 256 bit AES encryption that is always on and cannot be turned off.

This is also documented in the article [_Security in Azure Database for PostgreSQL - Single Server_](https://docs.microsoft.com/en-us/azure/postgresql/single-server/concepts-security):

> The Azure Database for PostgreSQL service uses the FIPS 140-2 validated cryptographic module for storage encryption of data at-rest. Data, including backups, are encrypted on disk, including the temporary files created while running queries. The service uses the AES 256-bit cipher included in Azure storage encryption, and the keys are system managed. **Storage encryption is always on and can't be disabled**.

(Emphasis added)
