### ISSUE TITLE
Feature: Support resources needed by CAPZ

### ISSUE THREAD

**Issue by matthchr** [Azure/azure-service-operator#2237]
The list of resources we are currently lacking for CAPZ is:
- [ ] VM extensions (https://github.com/Azure/azure-service-operator/issues/2891)
- [ ] VMSS extensions (https://github.com/Azure/azure-service-operator/issues/2891)
- [x] Azure Bastions (https://github.com/Azure/azure-service-operator/issues/2892)
- [x] NAT Gateways (https://github.com/Azure/azure-service-operator/issues/2893)
- [ ] Inbound NAT rules (https://github.com/Azure/azure-service-operator/issues/2894)
- [ ] Availability Sets (https://github.com/Azure/azure-service-operator/issues/1930)
- [x] Private DNS (private zones, vnetlinks, and recordsets) (#2086 is a PR for this but not merged yet).
- [x] RouteTable (#2284)
- [x] Virtual Network Peerings

The full list of in-use services can be found here: https://github.com/kubernetes-sigs/cluster-api-provider-azure/tree/master/azure/services

**Comment by matthchr** [comment]
I just realized that we already support Peerings. Updated the list to reflect that

**Comment by nojnhuh** [comment]
Resource health also falls into this category: #2762

CAPZ also uses `privatdns.VirtualNetworkLinks` and `privatedns.RecordSets` and I can't quite tell if those are supported in ASO? I see `PrivateDnsZonesVirtualNetworkLink` and the record types listed here: https://azure.github.io/azure-service-operator/reference/. But there's no sample YAML and I don't see them listed anywhere on this page: https://azure.github.io/azure-service-operator/reference/network/v1beta20180901/.

Otherwise I took another look through the list and everything looks up to date 👍

**Comment by matthchr** [comment]
Yes we support `RecordSets` and `VirtualNetworkLinks`. IIRC both of these were added for the upcoming v2.0.0 release and they aren't on the full website yet because that release hasn't gone out yet, but they will be there shortly.

**Comment by dtzar** [comment]
@matthchr - can you please reflect the latest status with the checklist of items at the top of this description?  I can see it hasn't been updated since April 2022.

**Comment by mboersma** [comment]
Assuming [this list](https://github.com/kubernetes-sigs/cluster-api-provider-azure/tree/master/azure/services) represents services currently implemented, I don't see any delta with https://github.com/kubernetes-sigs/cluster-api-provider-azure/tree/main/azure/services.

@mattchr are there still gaps here?

**Comment by matthchr** [comment]
Yes there are definitely some gaps here.

ASO has a list of supported resources here: https://azure.github.io/azure-service-operator/reference/

I believe the checklist above is correct. We do not currently have support for:

- [ ] VM extensions
- [ ] VMSS extensions
- [ ] Azure Bastions
- [ ] NAT Gateways
- [ ] Inbound NAT rules
- [ ] Availability Sets (https://github.com/Azure/azure-service-operator/issues/1930)
- [ ] VirutalMachineImages (not 100% sure what this is actually?)
- [ ] ScaleSetVMs (I think from looking at CAPZ code this is related to VMSS Flex?)

The rest of the resources CAPZ uses I believe we have support for already.

**Comment by mboersma** [comment]
> I believe the checklist above is correct.

Excellent, thank you for the confirmation @matthchr! I'll use this list to try to fill in the gaps for CAPZ with SDK v2 until these resources are implemented in ASO.

**Comment by matthchr** [comment]
Rather than tracking this as a block, I've broken out individual items for the above. I edited them in to my post above and the original issue.

I'll close this in favor of those once we get clarity on what these two things actually are:
- [ ] VirutalMachineImages (not 100% sure what this is actually?)
- [ ] ScaleSetVMs (I think from looking at CAPZ code this is related to VMSS Flex, since with uniform you dont provision VMs you just edit the parent VMSS?)

Which ARM resources do these refer to?

**Comment by matthchr** [comment]
I've added a CAPZ label for now to track this work too: https://github.com/Azure/azure-service-operator/labels/capz

**Comment by matthchr** [comment]
Ah, VirtualMachineImages is just LIST for CAPZ: https://github.com/kubernetes-sigs/cluster-api-provider-azure/blob/main/azure/services/virtualmachineimages/client.go

**Comment by matthchr** [comment]
and here's ScaleSet VMs issue: https://github.com/Azure/azure-service-operator/issues/2895

It's also not a real resource but it seems a reasonable ask for there to be a way to manage individual VMs through the ASO API.

**Comment by matthchr** [comment]
I'm closing this in favor of all of the linked issues above that can track things at a more granular level. Use the https://github.com/Azure/azure-service-operator/labels/capz label for an aggregate view of what more needs to be done.
