### ISSUE TITLE
GA Release Date

### ISSUE THREAD

**Issue by ranadeb-pramanick** [Azure/azure-service-operator#2244]
When is the ASO v2 expected to be GA ? I still see this is Beta release. Any ballpark timeline?

**Comment by matthchr** [comment]
You are correct that ASO v2 is still in beta. In fact it was in alpha until 10 days ago when beta.0 came out. We're still quite a ways from GA. The timeline will be impacted significantly by customer feedback and interest, but it's unlikely ASO v2 will GA before the end of 2022.

With that said, we have confidence in the quality of the beta and there are no critical missing features like there were in the earlier alphas. You can run ASOv2 beta in production. We will respond to issues promptly. 

The main reason for the beta label is we may need to change the shape of the resources in a breaking way. These changes would likely be small (not impacting all users) and infrequent (based on user feedback). If they did happen, we would provide migration instructions.

**Comment by matthchr** [comment]
Closing this as the question was answered
