### ISSUE TITLE
How to use status fields?

### ISSUE THREAD

**Issue by Sbou** [Azure/azure-service-operator#2271]
Hello,

My question is about using ASO with other resources.

I use PostgreSQL server with the `FlexibleServer.dbforpostgresql.azure.com`.
I would like to reference the `status.fullyQualifiedDomainName` as environment variable for an application deployment.
How can we use the **status fields** in other Kubernetes resources?

Thank you

**Comment by matthchr** [comment]
You can't import status fields into environment variables AFAIK. We support this instead by exporting that variable as a secret. It looks like [this for Redis](https://github.com/Azure/azure-service-operator/blob/main/v2/config/samples/cache/v1beta20201201_redis.yaml#L22), for example.

Unfortunately it looks like we've missed exposing this for both `postgresql` and `mysql`. I have filed #2272 tracking this

**Comment by Sbou** [comment]
Thank you for your answer.

More generally, it would be interesting to have a generic system where all the fields would be exposable in a configMap or Secret (with a 'sensitive' attribute).

On this [page ](https://azure.github.io/azure-service-operator/introduction/secrets/) there is `operatorSpec` field to expose some info in Secrets.
With automatic generation from OpenAPIs, defining exportable fields is not going to be easy. If all the fields were selectable this would not be a problem.

Thank you
