### ISSUE TITLE
Bug: Code generator doesn't clean up doc.go files

### ISSUE THREAD

**Issue by theunrepentantgeek** [Azure/azure-service-operator#2298]
**Version of Azure Service Operator**

Code generator as of v2.0.0.beta.0

**Describe the bug**

As a part of regenerating all the code, our code generator deletes all the code that we previously generated, to ensure we have a clear field for writing new files.

The generator writes `doc.go` files that don't get cleaned up.

**To Reproduce**

* Comment out the final few stages of the pipeline in `code_generator.go` so that no files are written
  * pipeline.ExportPackages
  * pipeline.ExportControllerResourceRegistrations
  * pipeline.ReportResourceVersions
* Rebuild the generator
* Generate resources

**Expected behavior**

The output folders should contain only handwritten code, if any.

**Comment by theunrepentantgeek** [comment]
Question: Why is the file called `doc.go` - is that a reserved name, or could we rename it to `doc_gen.go`?

**Comment by matthchr** [comment]
I think it's a reserved name
