### ISSUE TITLE
Kubeconfig to connect ManagedCluster

### ISSUE THREAD

**Issue by a1tan** [Azure/azure-service-operator#2311]
When an AKS cluster is run with ManagedCluster resource, the connection information for new cluster is not created on host as of containerservice.v1beta20210501. Maybe I am missing some configuration.

Connection information(e.g. kubeconfig) for new ManagedCluster should be created on the same namespace as a secret. By using this secret GitOps controllers installed on host, can manage new cluster.

**Comment by theunrepentantgeek** [comment]
We should add `$azureGeneratedSecrets` configuration for ManagedCluster to pull out the necessary details.
