### ISSUE TITLE
Feature: Support for KubernetesConfiguration/fluxConfigurations

### ISSUE THREAD

**Issue by a1tan** [Azure/azure-service-operator#2312]
Support to apply Microsoft.KubernetesConfiguration/fluxConfigurations is needed.

**Comment by theunrepentantgeek** [comment]
Looks like `fluxConfiguration` is an extension resource but should be achievable.

**Comment by matthchr** [comment]
Still something we're interested in doing. We do need to reconcile how this would play with the existing ARC integrations to k8s.

**Comment by matthchr** [comment]
No change from above. Haven't seen a ton of user clamor for this either.
