### ISSUE TITLE
Feature: Export clientId from UserAssignedIdentity

### ISSUE THREAD

**Issue by Sbou** [Azure/azure-service-operator#2317]
Hello,

To be able to use the Pod identity feature in a AKS clsuter, it could be great to have the **resource Id** and the **client Id** of the generated managed identity in a ConfigMap or Secret.

Thanks

**Comment by theunrepentantgeek** [comment]
This may be possible by adding `$azureGeneratedSecrets`. We'll add this to our backlog - given it's a simple change, we'd also accept a PR.

**Comment by matthchr** [comment]
We were just talking about this in #2489 and #2435. This is something that we want to do.
