### ISSUE TITLE
Include handwritten Custom Resources in our resource list

### ISSUE THREAD

**Issue by theunrepentantgeek** [Azure/azure-service-operator#2337]
We are starting to introduce selected handwritten custom resources, ones that can't be generated as they are not ARM resources; these don't currently show up in our generated documentation of supported resources.

For example, PR #2328 introduces support for MySQLUser.

**Comment by theunrepentantgeek** [comment]
Suggested approach:

* Add a new section to our YAML configuration file listing the manually written resources
* Read that section and include those resources when generating the report on supported resources

**Comment by matthchr** [comment]
We have fragments now but not yet support for entire resources. Still something we should do.

**Comment by theunrepentantgeek** [comment]
Duplicated by #3054
Closed by #3055
