### ISSUE TITLE
Feature: Add support for backup vault for storage accounts

### ISSUE THREAD

**Issue by masterphenix** [Azure/azure-service-operator#2345]
It would be nice to be able to manage backup vaults with ASO, and be able to configure backup for storageAccount within that backup vault.

**Comment by matthchr** [comment]
We're still interested in doing this. I think that this is `Microsoft.RecoveryServices/vaults`, although there's also `Microsoft.DataProtection/backupVaults`.

**Comment by matthchr** [comment]
Still interested in doing this

**Comment by super-harsh** [comment]
We already support `Microsoft.DataProtection/backupvaults`. Although to backup a resource we need [Microsoft.DataProtection backupVaults/backupInstances](https://learn.microsoft.com/en-us/azure/templates/microsoft.dataprotection/backupvaults/backupinstances?pivots=deployment-language-bicep).
