### ISSUE TITLE
Feature: Export configuration from status

### ISSUE THREAD

**Issue by theunrepentantgeek** [Azure/azure-service-operator#2350]
For some resources it would be useful to make key properties available via a config map for consumption elsewhere in the cluster.

Examples include
| Service | Property Path |
| -- | -- |
| Application Insights | Component.Status.ConnectionString |
| Batch | BatchAccount.Status.AccountEndpoint |
| CosmosDB | DatabaseAccount.Status.DocumentEndpoint |
| Service Bus | SBNamespace.Status.ServiceBusEndpoint |

Similar to the existing `AzureGeneratedSecrets` configuration employed by the generator, one approach to solving this would be to also support `AzureGeneratedConfig`, with matching injection points for retrieving and publishing the configuration.

**Comment by matthchr** [comment]
This is supported now. See #2541 for an example of how it's used.
