### ISSUE TITLE
Bug: Bad link on website

### ISSUE THREAD

**Issue by plwhite** [Azure/azure-service-operator#2364]
**Describe the bug**
At the website page <https://azure.github.io/azure-service-operator/>, source code in `v2/README.md`, there is a line:

    See the list of supported resources [here](https://azure.github.io/azure-service-operator/introduction/resources/).

That should read:

    See the list of supported resources [here](https://azure.github.io/azure-service-operator/reference/).

Presumably the website has been rearranged, and the link broken.

**To Reproduce**
Go to the website, check the link.

**Expected behavior**
Link should work.

**Comment by theunrepentantgeek** [comment]
Thanks for letting us know @plwhite, I've merged @matthchr's fix.
