### ISSUE TITLE
Add ability to delete osDisk when VMs are deleted

### ISSUE THREAD

**Issue by Jimbwlah** [Azure/azure-service-operator#2368]
**Describe the current behavior**

The imageReference property on a virtualMachine allows a VM to be created with a specific image and OS disk. 

**Describe the improvement**

VMs support having their osDisk deleted when they themselves are deleted. The property is deleteOption under osDisk - https://docs.microsoft.com/en-us/azure/virtual-machines/delete?tabs=portal2%2Cportal3%2Cportal4.

Please can this be supported. Thanks

**Comment by matthchr** [comment]
This property was added in the `2021-03-01` compute API, we're using the `2020-12-01` API. We should probably just update to the latest compute API (`2022-03-01`)

**Comment by matthchr** [comment]
We need to fix this, so reopening. The above was just a note on what we need to do to fix this.
