### ISSUE TITLE
Bug: CI Builds omit logs

### ISSUE THREAD

**Issue by theunrepentantgeek** [Azure/azure-service-operator#2412]
**Describe the bug**

When our CI builds timeout, we end up with logs missing!

Each invocation of `go test` includes redirection of output into a `json` file, which is then post-processed to produce a summary file with test results.

If the test run is interrupted by a timeout, the container is killed and the final `json` file is omitted from the test results.

In a [recent test run](https://github.com/Azure/azure-service-operator/actions/runs/2716248151), the summary shows two result files with all the tests passing.

If you look at the detailed logs for the `test-generator` step, you can see the final step, writing to `controller-integration-tests.json` was interrupted during execution and no output generated. Unfortunately, this means we have completely lost the results of that step.

**To Reproduce**

1. Run a build that times out. (This might be a challenge.)

**Expected behavior**

* We should always get all test output
* Out tests should not time out

**Comment by matthchr** [comment]
Also note that we can increase our CI timeout, the limit we have was set by us I think

**Comment by matthchr** [comment]
This is still theoretically an issue, although timeouts don't happen often

**Comment by theunrepentantgeek** [comment]
This is no longer happening regularly; once #2875 has been completed (which should just about eliminate timeouts) we can close this.
