### ISSUE TITLE
Check `fqdn` for `databases`

### ISSUE THREAD

**Issue by jiwanovski87** [Azure/azure-service-operator#2428]
**Describe the current behavior**
When creating a `flexible server` (e.g. pg) it is not checked if this server name / fqdn is already existing.
Since the server name must be unique over multiple subscriptions / customers to get the fqdn wit `*.postgres.database.azure.com`..

Currently we are not getting any good feedback / error to solve this.

**Describe the improvement**
Check if the name is free. If not sent a good error message.

**Comment by super-harsh** [comment]
Hey, thanks for raising this. We had a look at this one and the error we get here is from ARM. We have raised the issue internally with the `FlexibleServer` team and they are working on fixing this.

**Comment by matthchr** [comment]
This has been improved, it now shows:
> Specified server name is already used.: PUT https://management.azure.com/subscriptions/4ef44fef-c51d-4d7c-a6ff-8635c02848b1/resourceGroups/asotest-rg-mvhpcy/providers/Microsoft.DBforMySQL/flexibleServers/matthchrmysql
