### ISSUE TITLE
documentation on adding azure mysql server parameters in yaml 

### ISSUE THREAD

**Issue by nickelodean** [Azure/azure-service-operator#2434]
**Describe the current behavior**
As a part of security , we want to tune mysql server variables and want to be specified in yaml file.
documentation/examples dosent show a way to specify server parameters for mysql Ex:

`apiVersion: azure.microsoft.com/v1alpha1
kind: MySQLDatabase
metadata:
  name: mysqldatabase-sample2
spec:
  resourceGroup: resourcegroup-azure-operators
  server: mysqlserver-sample2`

  
**Describe the improvement**

`apiVersion: azure.microsoft.com/v1alpha1
kind: MySQLDatabase
metadata:
  name: mysqldatabase-sample2
spec:
  resourceGroup: resourcegroup-azure-operators
  server: mysqlserver-sample2
  **sql_mode: STRICT_ALL_TABLES
  local_infile: OFF**`

**Additional context**

we currently use azure portal or GUI , after deploy to change these variables, but goal is to specify in yaml if possible while deploying

**Comment by matthchr** [comment]
It looks like you're using Azure Service Operator v1, which is in maintenance mode. I don't believe that we support setting MySQL variables in ASOv1, and given where it currently is in its lifecycle it's not very likely that we will.

We only support `FlexibleServer` in ASOv2, but that resource could support `Configurations` similar to how PostgreSQL [already does](https://github.com/Azure/azure-service-operator/blob/main/v2/config/samples/dbforpostgresql/v1beta/v1beta20210601_flexibleserversconfiguration.yaml).

Would that solve your problem?

**Comment by nickelodean** [comment]
good to know they are supported in ASOv2, and the flexible server. however, azure.extensions for postgresql are more of built in feature usage than configuring basic server parameters while deploying initially. I am looking for configuring parameters mentioned in "server parameters" section in GUI into the yaml. attached screen shot for your reference for azure mysql server parameter section and azure postgresql server parameter section.Can you please show some examples if it is already supported.

<img width="920" alt="image" src="https://user-images.githubusercontent.com/14946752/183704584-d2e06d30-633d-4781-b0a7-a58d0eb8f15c.png">

<img width="839" alt="image" src="https://user-images.githubusercontent.com/14946752/183704824-175db98e-a9c8-4425-bb07-517db6339369.png">

Yaml Example:
`apiVersion: azure.microsoft.com/v1alpha1 kind: MySQLDatabase metadata: name: mysqldatabase-sample2 spec: resourceGroup: resourcegroup-azure-operators server: mysqlserver-sample2 **connect_timeout:10 lock_wait_timeout: 240 sql_mode: STRICT_ALL_TABLES local_infile: OFF**`

**Comment by matthchr** [comment]
This issue will be closed when the linked PR #2987 merges, as that will add support for Configuration for MySQLFlexibleServer.

We're not planning on adding support for MySQL single server to ASOv2 as it's being phased out.
