### ISSUE TITLE
Bug: Does ASO v2 support Managed Identity to use to authenticate with Azure ?

### ISSUE THREAD

**Issue by yuyamizo** [Azure/azure-service-operator#2481]
**Version of Azure Service Operator**

```
kubectl get deployment -n azureserviceoperator-system azureserviceoperator-controller-manager -o wide
NAME                                      READY   UP-TO-DATE   AVAILABLE   AGE    CONTAINERS                IMAGES                                                                                                SELECTOR
azureserviceoperator-controller-manager   1/1     1            1           116m   manager,kube-rbac-proxy   mcr.microsoft.com/k8s/azureserviceoperator:v2.0.0-beta.2,gcr.io/kubebuilder/kube-rbac-proxy:v0.13.0   control-plane=controller-manager
```

and cert-manager is `v1.7.3`.
```
kubectl get pods -n cert-manager
NAME                                                    READY   STATUS    RESTARTS   AGE
cert-manager-cert-manager-7589f99cf8-94htd              1/1     Running   0          6h11m
cert-manager-cert-manager-cainjector-6955d8dc7f-dn9qv   1/1     Running   0          6h11m
cert-manager-cert-manager-webhook-67d59768c4-bwdjd      1/1     Running   0          6h11m
```

**Describe the bug, To Reproduce**
1. I set these Values to ASO v2 Helm Chart: azureTenantID, azureSubscriptionID, azureClientID (Managed Identity Client ID)
according to [this values file](https://github.com/Azure/azure-service-operator/blob/b1b96f2dac95c59609060359c5b720a3085f7804/v2/charts/azure-service-operator/values.yaml).
1. I applied this manifest to my AKS cluster according to [this usage](https://github.com/Azure/azure-service-operator/tree/main/v2#usage).
```
apiVersion: resources.azure.com/v1alpha1api20200601
kind: ResourceGroup
metadata:
  name: aso-sample-rg
  namespace: default
spec:
  location: westcentralus
```

3. then, the following errors occured
```
k describe resourcegroup.resources.azure.com aso-sample-rg -n default
Events:
  Type     Reason                     Age                 From                     Message
  ----     ------                     ----                ----                     -------
  Warning  CreateOrUpdateActionError  47m (x21 over 63m)  ResourceGroupController  DefaultAzureCredential: failed to acquire a token.
Attempted credentials:
           EnvironmentCredential: incomplete environment variable configuration. Only AZURE_TENANT_ID and AZURE_CLIENT_ID are set
           ManagedIdentityCredential: IMDS token request timed out
           AzureCLICredential: fork/exec /bin/sh: no such file or directory
  Warning  CreateOrUpdateActionError  28s (x51 over 46m)  ResourceGroupController  DefaultAzureCredential: failed to acquire a token.
Attempted credentials:
  EnvironmentCredential: incomplete environment variable configuration. Only AZURE_TENANT_ID and AZURE_CLIENT_ID are set
  ManagedIdentityCredential: IMDS token request timed out
  AzureCLICredential: fork/exec /bin/sh: no such file or directory

```

```
k logs azureserviceoperator-controller-manager-cf88df49d-bhz5k -n azureserviceoperator-system
E0901 08:23:00.127910       1 generic_controller.go:231] controllers/ResourceGroupController "msg"="error during reconcile" "error"="DefaultAzureCredential: failed to acquire a token.\nAttempted credentials:\n\tEnvironmentCredential: incomplete environment variable configuration. Only AZURE_TENANT_ID and AZURE_CLIENT_ID are set\n\tManagedIdentityCredential: IMDS token request timed out\n\tAzureCLICredential: fork/exec /bin/sh: no such file or directory" "name"="aso-sample-rg" "namespace"="default"
E0901 08:23:00.127951       1 controller.go:317] controllers/controller/resourcegroup "msg"="Reconciler error" "error"="DefaultAzureCredential: failed to acquire a token.\nAttempted credentials:\n\tEnvironmentCredential: incomplete environment variable configuration. Only AZURE_TENANT_ID and AZURE_CLIENT_ID are set\n\tManagedIdentityCredential: IMDS token request timed out\n\tAzureCLICredential: fork/exec /bin/sh: no such file or directory" "name"="aso-sample-rg" "namespace"="default" "reconciler group"="resources.azure.com" "reconciler kind"="ResourceGroup"
```

When I use ASO v1, I can create azure resources with azureTenantID, azureSubscriptionID, azureClientID and azureUseMI according to [this values file](https://github.com/Azure/azure-service-operator/blob/main/charts/azure-service-operator/values.yaml).

Does ASO v2 support Managed Identity to use to authenticate with Azure ?
Is [this comment](https://github.com/Azure/azure-service-operator/blob/b1b96f2dac95c59609060359c5b720a3085f7804/v2/charts/azure-service-operator/values.yaml#L9) a copy error from ASO v1 ?

**Comment by matthchr** [comment]
We support Managed Identity to authenticate. For both ASOv1 and ASOv2, you must provide some way for the managed identity to be accessible by the ASO operator pod in order for this mechanism to work. In ASOv1 this was described [here](https://github.com/Azure/azure-service-operator/blob/main/docs/v1/howto/deploy.md#managed-identity-authentication) in the section on AAD Pod Identity.

In ASOv2, we support AAD Pod Identity as well, as documented [here](https://azure.github.io/azure-service-operator/introduction/authentication/#managed-identity-aad-pod-identity). Do note that AAD Pod Identity is deprecated and Workload Identity is meant to replace it. There's a PR (see #2464)  that describes the process for using workload identity + managed identity in ASOv2, but still will be a few days before it's merged.

Based on the above error message, I'm thinking you haven't installed AAD Pod Identity on this cluster?

**Comment by yuyamizo** [comment]
Thank you for answer to my question! my ASO v2 worked well.

I didn't notice that AAD Pod Identity selector name had changed.
ASO v1: `aso_manager_binding` -> ASO v2: `aso-manager-binding`
When I re-created AzureIdentityBinding resource, my ASO v2 worked well.
