### ISSUE TITLE
Documentation - broken links

### ISSUE THREAD

**Issue by masterphenix** [Azure/azure-service-operator#2496]
Hello, not sure this is the right place to report this, but I have come across many broken links while reading about latest releases:

- On https://github.com/Azure/azure-service-operator/releases/tag/v2.0.0-beta.1 , the "supported resources" link (https://azure.github.io/azure-service-operator/introduction/resources/) leads to 404
- On https://azure.github.io/azure-service-operator/ ; "[the latest v2+ Helm chart](https://azure.github.io/v2/charts)" also leads to a 404
- On https://azure.github.io/azure-service-operator/#how-to-contribute, the "[contributing guide](https://azure.github.io/azure-service-operator/contributing/contributing/)." link also leads to 404.

**Comment by matthchr** [comment]
This _is_ the right place to report that, and thank you! We recently move some of these pages around and it looks like we missed updating some links. 

@super-harsh recently made a markdown link-checker for the website to try to avoid this (#2455), but I think it just checks the markdown links. We'll fix this shortly.
