### ISSUE TITLE
Incorrectly named cross resource references

### ISSUE THREAD

**Issue by matthchr** [Azure/azure-service-operator#2501]
We've mistakenly missed a few properties which should have been marked as ARM ID references. We instead left them as strings. The fix for this is easy, but it would be breaking... We need to decide what we can do here to evolve in a positive direction, either by breaking prior to going GA or fixing this in a newer version of the service.

Can look through the repo for `TODO[breaking]` to find some examples of this.

**Comment by matthchr** [comment]
We could maybe use the yaml deserialization trick here to allow putting a string straight into `ARMID` field (this would make this a nonbreaking change, so worth considering).

**Comment by matthchr** [comment]
Another aspect of this is that we don't name properties correctly as we're case-sensitive to the `Id` suffix

**Comment by theunrepentantgeek** [comment]
Deferred to `beta.5` in the hope we can make this non-breaking.
