### ISSUE TITLE
RPs are not registered for first use

### ISSUE THREAD

**Issue by uday31in** [Azure/azure-service-operator#2513]
**Describe the current behavior**
A description of how things are today.

For the new subscription, RPs are not registered by default when used via REST for the first time. As a result, provisioning of the resources will fail until it is manually registered and resources are stuck/time out in reconcile error.

```
"error"="The subscription is not registered to use namespace 'Microsoft.DocumentDB'
```

**Describe the improvement**
How should things be changed or improved?

Check on RP registration HTTP 409 "MissingSubscriptionRegistration" error and retry the operation with exponential back off

**Additional context**
Add any other context about the suggested improvement.

```
{
    "code": "MissingSubscriptionRegistration",
    "message": "The subscription is not registered to use namespace 'Microsoft.DocumentDB'. See https://aka.ms/rps-not-found for how to register subscriptions.",
    "details": [
      {
        "code": "MissingSubscriptionRegistration",
        "target": "Microsoft.DocumentDB",
        "message": "The subscription is not registered to use namespace 'Microsoft.DocumentDB'. See https://aka.ms/rps-not-found for how to register subscriptions."
      }
    ]
  }
}
```

**Comment by matthchr** [comment]
Agree.

Will fix for next release. Should be relatively easy as this is baked into the Go SDK and we've just got it turned off because it can produce really long waits. I think we can instead just configure it to not wait, which will allow the operator to naturally retry.
