### ISSUE TITLE
Feature: Create RoleDefinitions

### ISSUE THREAD

**Issue by matthchr** [Azure/azure-service-operator#2570]
The resource is `Microsoft.Authorization/roleDefinitions`.

An example ARM template is here: https://learn.microsoft.com/en-us/azure/role-based-access-control/custom-roles-template

**Comment by matthchr** [comment]
We still want to do this

**Comment by ashetonh-ad** [comment]
We do as well

**Comment by matthchr** [comment]
Still interested in doing this - it should be pretty easy as well if anybody external wants to contribute it.
