### ISSUE TITLE
15m default re-reconcile interval is probably too aggressive

### ISSUE THREAD

**Issue by matthchr** [Azure/azure-service-operator#2577]
**Describe the current behavior**
We re-reconcile resources every 15m. This is configurable with the `AZURE_SYNC_PERIOD` variable in `aso-controller-settings`.

**Describe the improvement**
We should reduce this to by default 1h. It could be increased later if we implement #1491, although even diffing will produce Azure load so individual users may need to tune this time.

We should also consider the following:
- an annotation to allow this to be configured for specific resources
- A way to control this per resource type

**Comment by ryanzhang-oss** [comment]
just curious, I wonder why 15m is too aggressive, is that we hit the ARM limit?

**Comment by matthchr** [comment]
Yeah it just means it's easier to hit the ARM limit. Right now, choosing this value is a bit of a balance between: "How fast do you want problems detected" and "how many requests do you want sent to Azure". For small-medium clusters 15m is probably fine.
For large clusters (lots of resources), 15m is probably too fast.

It's possible that 1h is too slow. I think it's OK if large cluster users need to change this default, but IMO we want a default that scales at least into medium clusters with a good number of resources without issue.
