### ISSUE TITLE
aso v2.0.0 doesn't support 'Some zone' High availability mode for postgresql flexible server

### ISSUE THREAD

**Issue by Gan-Jun** [Azure/azure-service-operator#2579]
we are testing postgresql flexible server in azure China north3 region using aso v2.0.0-beta.2 version, this new region currently only supports 'Same zone' HA, and 'Zone redundant' feature is not ready in azure china. I want to enable 'Same zone' HA setting via aso, currently this setting can be updated in azure portal, but it seems aso v2.0.0-beta.2 and v2.0.0-beta.3 still don't support 'Same zone' HA for postgresql flexible server. from file apiextensions.k8s.io_v1_customresourcedefinition_flexibleservers.dbforpostgresql.azure.com.yaml I cannot find keyword 'SameZone', but from apiextensions.k8s.io_v1_customresourcedefinition_flexibleservers.dbformysql.azure.com.yaml file I can find highAvailability.mode has enum value SameZone, see screenshot attached.
![aso1](https://user-images.githubusercontent.com/48749989/199423848-dfac0fba-c56d-4ac3-aa90-cebd9af47f51.png)
![aso2](https://user-images.githubusercontent.com/48749989/199423906-cbc0f9c9-71d4-4d73-b3dc-22f8222c3f78.png)
![aso3](https://user-images.githubusercontent.com/48749989/199423926-74d694b7-1cd6-49d2-b1e8-dcd9a2f8f361.jpg)

**Comment by matthchr** [comment]
It looks like `SameZone` was not added for Postgres until `2022-03-01-preview` API version, whereas `SameZone` for MySQL DB was added in `2021-05-01` (GA) API version.

To support this, it looks like we need to move to the newer preview API for FlexibleServer.
