### ISSUE TITLE
Configurable max backoff for ASO polling

### ISSUE THREAD

**Issue by matthchr** [Azure/azure-service-operator#2584]
**Describe the current behavior**
The polling speeds are hardcoded in ASO.

**Describe the improvement**
The polling speed _could_ be configurable, either at a per-resource level using annotations or at the whole operator level via an option in the `aso-controller-settings` secret.

**Comment by matthchr** [comment]
We're not 100% sure we actually want to expose this as a configuration because it feels like something that people might shoot themselves in the foot with. We'll leave this item open for now and if/when we revisit this in a few months if there's desire for this we may do it, but if there's not we may close it.

**Comment by StephanSalas** [comment]
Perhaps polling speed could be configurable _to a _limit__ so that folks can't shoot themselves in the foot without compiling golang code. That would be an interesting compromise.

**Comment by matthchr** [comment]
We're still thinking about this

**Comment by matthchr** [comment]
No change from above. Some polling is already configurable (the `AZURE_SYNC_PERIOD`). We've had much fewer issues with throttling since the improvements we've made so currently not planning on implementing this unless a new need arises.

**Comment by matthchr** [comment]
Closing this as it seems that the current backoffs we have are working well, we haven't seen throttling issues in ages and we'd prefer if the defaults "just worked" rather than requiring the users to tune them.
