### ISSUE TITLE
Bug: ExpiredAuthenticationToken Error On Azure Resource Deletion

### ISSUE THREAD

**Issue by StephanSalas** [Azure/azure-service-operator#2587]
**Version of Azure Service Operator**
mcr.microsoft.com/k8s/azureserviceoperator:v2.0.0-beta.3

**Describe the bug**
I keep getting error: 
```
RESPONSE 401: 401 Unauthorized
ERROR CODE: ExpiredAuthenticationToken
--------------------------------------------------------------------------------
{
  "error": {
    "code": "ExpiredAuthenticationToken",
    "message": "The access token expiry UTC time '11/10/2022 9:09:43 PM' is earlier than current UTC time '11/10/2022 10:04:12 PM'."
  }
}
```

The resource does eventually start deleting, but after some time (30 minutes I counted for one particular incidence).

**To Reproduce**
Steps to reproduce the behavior: Delete any object once created.

**Expected behavior**
The object should delete immediately without this error.

**Screenshots**

**Additional context**
I suspect this might be a clock skew issue? However this keeps occurring to me while using the operator. If the error log is to be trusted, this would indicate that the auth token generated by secret "aso-controller-settings" never refreshes. I do not get the same error on Azure Resource Creation in any instance.

**Comment by matthchr** [comment]
Which form of auth are you using with ASO?

1. Service Principal based (`AZURE_CLIENT_SECRET` will be set in your `aso-controller-settings`.
2. AAD Pod Identity (You'll have installed https://github.com/Azure/aad-pod-identity)
3. Azure workload identity

>  I do not get the same error on Azure Resource Creation in any instance.

Just confirming that this means you can create resources just fine without any access error, but you cannot delete resources (or at least, that one resource) due to the auth error.

**Comment by matthchr** [comment]
We use the same set of credentials for creation and deletion, so it's unexpected that you're getting through for one but not the other. More information about what authentication mechanism you're using, and any logs from the operator would be appreciated.

If we don't hear back in a couple more days we may close this issue until an update is provided - thanks!

**Comment by StephanSalas** [comment]
Hi, I will need a few days to get back to my laptop, and will share more details. Thanks!

**Comment by StephanSalas** [comment]
Hello @matthchr, I am using this option with my azure app:
> * Service Principal based (`AZURE_CLIENT_SECRET` will be set in your `aso-controller-settings`).

I also just wanted to clarify that the resource does *eventually delete, however it takes a while, and I do see the aforementioned error message. My minikube environment somehow died one me so will have to reinstall the ASO to replicate. Will reply once I can get more logs.

**Comment by matthchr** [comment]
Closing this as there hasn't been activity. Feel free to reopen if you've got more details.
