### ISSUE TITLE
Possible bug: Incorrect property types

### ISSUE THREAD

**Issue by theunrepentantgeek** [Azure/azure-service-operator#2606]
**Describe the bug**

Comparing resource structures between main and the Swagger branch in #2323, identified three properties that seem to have the wrong type.

```
github.com/Azure/azure-service-operator/v2/api/containerservice/v1beta20210501
├── ManagedCluster: Resource
│   ├── Spec: Object (30 properties)
│   │   ├── ...
│   │   ├── AddonProfiles: *v1.JSON
│   │   ├── AgentPoolProfiles: Object (34 properties)
│   │   │   ├── ...
│   │   │   ├── OsDiskSizeGB: Validated<int> (2 rules)
│   │   │   │   ├── Rule 0: {Maximum 2048}
│   │   │   │   └── Rule 1: {Minimum 0}
│   │   │   ├── ...
│   │   │   ├── ProximityPlacementGroupID: Validated<string> (0 rules)
│
```

In the `main` branch, `AddonProfiles` has structure:

```
│   │   ├── AddonProfiles: Object (2 properties)
│   │   │   ├── Config: map[string]string
│   │   │   └── Enabled: *bool
```

while both `OsDiskSizeGB` and `ProximityPlacementGroupID` seem to have lost their optionality.

```
│   │   │   ├── OsDiskSizeGB: Validated<*int> (2 rules)
│   │   │   │   ├── Rule 0: {Maximum 2048}
│   │   │   │   └── Rule 1: {Minimum 0}
│   │   │   ├── ...
│   │   │   ├── ProximityPlacementGroupID: Validated<*string> (0 rules)
```

Expected behaviour: the properties should have their types from `main`.

**Comment by matthchr** [comment]
**For `AddonProfiles`:** 

The Swagger definition is [here](https://github.com/Azure/azure-rest-api-specs/blob/main/specification/containerservice/resource-manager/Microsoft.ContainerService/stable/2021-05-01/managedClusters.json#L3328).
```
        "addonProfiles": {
          "additionalProperties": {
            "$ref": "#/definitions/ManagedClusterAddonProfile"
          },
          "description": "The profile of managed cluster add-on."
        },
```

Which should generate a `map[string]*ManagedClusterAddonProfile`, but is not. So likely there's something about map types that's not working quite right.

Agree the loss of optionality looks wrong too.

There's also another map type issue lower down with `IdentityProfile` which seems to have the same problem as above.

Finally, `AzureName: string` seems to have lost its validation in the Swagger branch,

**Comment by matthchr** [comment]
I have a fix for the `AddonProfiles` issue and the `IdentityProfile` issue locally.

I believe that the issues with `OsDiskSizeGB` and `ProximityPlacementGroupID` are actually issues in the report generator, because from looking at the structure.txt it implies that ManagedCluster.Spec.AgentPoolProfiles.OSDiskSizeGB is a `Validated<int>`, but in reality you can see that [it's a Validated<*int>](https://github.com/Azure/azure-service-operator/blob/sswwaaggggeerr/v2/api/containerservice/v1beta20210501/managed_cluster_types_gen.go#L4360). I think there's an issue with Swagger ending up with a `*Validated<int>` vs a `Validated<*int>` and one isn't rendering right in the structure.txt diffs I don't think. Can you take a look @theunrepentantgeek?

I haven't had a chance to dig into the AzureName loss of validation yet.

**Comment by matthchr** [comment]
I see the issue with `AzureName` as well and am working on a fix for that too.

**Comment by matthchr** [comment]
Between #2610 and #2609 I believe this issue has been resolved.

**Comment by theunrepentantgeek** [comment]
We're close, but not quite there.

`AddonProfiles` now has the same structure in both branches:
```
│   │   ├── AddonProfiles: map[string]Object (2 properties)
│   │   │   ├── Config: map[string]string
│   │   │   └── Enabled: *bool
```

Remembering that the `structure.txt` files inline types (to elide type _names_), I checked the actual type, and it looks correct:

``` go
// AddonProfiles: The profile of managed cluster add-on.
AddonProfiles map[string]ManagedClusterAddonProfile `json:"addonProfiles,omitempty"`
```

For both `OsDiskSizeGB` and `ProximityPlacementGroupID`, the optionality has migrated outside the ValidatedType:

On main:
```
│   │   │   ├── OsDiskSizeGB: Validated<*int> (2 rules)
│   │   │   ├── ProximityPlacementGroupID: Validated<*string> (0 rules)
```

compared with the Swagger branch:
```
│   │   │   ├── OsDiskSizeGB: *Validated<int> (2 rules)
│   │   │   ├── ProximityPlacementGroupID: *Validated<string> (0 rules)
```

This difference is resulting in validation being lost.

On main:
```
	// +kubebuilder:validation:Maximum=2048
	// +kubebuilder:validation:Minimum=0
	// OsDiskSizeGB: OS Disk Size in GB to be used to specify the disk size for every machine in the master/agent pool. If you
	// specify 0, it will apply the default osDisk size according to the vmSize specified.
	OsDiskSizeGB *int                                       `json:"osDiskSizeGB,omitempty"`
```

On the Swagger branch:
``` go
	OsDiskSizeGB        *ContainerServiceOSDisk `json:"osDiskSizeGB,omitempty"`
```

Interestingly, we're losing the comments as well.

**Comment by matthchr** [comment]
Hmm, good catch. Not sure why that is, will need to dig in more.

**Comment by theunrepentantgeek** [comment]
Looks like we're seeing a difference between the Swagger specs and the JSON schema.

Looking at the appropriate version of the Swagger, the property has no description:

```
    "ManagedClusterAgentPoolProfileProperties": {
      "properties": {
      ...
        "osDiskSizeGB": {
          "$ref": "#/definitions/ContainerServiceOSDisk"
        },
```

The referenced type does have both valildation and description though:

```
    "ContainerServiceOSDisk": {
      "type": "integer",
      "format": "int32",
      "maximum": 2048,
      "minimum": 0,
      "description": "OS Disk Size in GB to be used to specify the disk size for every machine in the master/agent pool. If you specify 0, it will apply the default osDisk size according to the vmSize specified."
    },
```

I'll investigate whether we can easily pull that information to the property.

**Comment by matthchr** [comment]
The description and validation should both be on the linked type `ContainerServiceOSDisk`, right? That type is an alias for `int` AFAIK.

**Comment by theunrepentantgeek** [comment]
In `main`, the `OsDiskSizeGB` property is directly declared:

```
├── OsDiskSizeGB: Validated<*int> (2 rules)
│   ├── Rule 0: {Maximum 2048}
│   └── Rule 1: {Minimum 0}
```

but in the Swagger branch, the validation is on a separate type:

```
├── OsDiskSizeGB: *ContainerServiceOSDisk

ContainerServiceOSDisk: Validated<int> (2 rules)
├── Rule 0: {Maximum 2048}
└── Rule 1: {Minimum 0}
```

These are equivalent, so there's no issue with this change.

I've created #2615 to improve the documentation, but that needs to wait until #2323 is merged.
