### ISSUE TITLE
Supporting creating overlay managed cluster

### ISSUE THREAD

**Issue by ZhiminXiang** [Azure/azure-service-operator#2620]
To create an overlay cluster, we need to set field `networkPluginMode` to overlay (see [doc](https://learn.microsoft.com/en-us/python/api/azure-mgmt-containerservice/azure.mgmt.containerservice.v2022_06_02_preview.models.containerservicenetworkprofile?view=azure-python#variables)). Currently the field `networkPluginMode` is not exposed within the CRD of managedCluster.

**Comment by matthchr** [comment]
Looks like we need to use a newer version of the `Microsoft.ContainerService` API, something like `2022-05-02-preview`.
