### ISSUE TITLE
Perform careful beta.3 -> beta.4 upgrade testing

### ISSUE THREAD

**Issue by matthchr** [Azure/azure-service-operator#2628]
Given the large changes between these two releases, we need to do very careful upgrade testing to ensure that everything works correctly.

At least the following scenarios should be tested:

1. Resource without breaking changes created w/ beta.3, then upgrade to beta.4, resource can be modified
2. Resource with simple breaking changes (such as removal of `Location` property which wasn't used) created w/ beta.3, then upgrade to beta.4 and ensure resource works.
3. Resource with complex breaking change (such as rename of properties) created w/ beta.3, then upgrade to beta.4 and see what happens (I think resource deserialization will not work, or possibly it'll work but then end up clearing a property on the deserialized object that it should not have?). Then follow mitigation to delete resource and recreate.

**Comment by super-harsh** [comment]
Did perform some manual testing for the above: 

1. Resource without breaking changes created w/ beta.3, then upgrade to beta.4, the resource can be modified
- Passed
2. Resource with simple breaking changes (such as removal of Location property which wasn't used) created w/ beta.3, then upgrade to beta.4 and ensure the resource works.
- Passed
3. Resource with complex breaking change (such as rename of properties) created w/ beta.3, then upgrade to beta.4 and see what happens (I think resource deserialization will not work, or possibly it'll work but then end up clearing a property on the deserialized object that it should not have?). Then follow mitigation to delete resource and recreate.
- Did get the deserialisation error on this one, however adding `serviceoperator.azure.com/reconcile-policy: skip` annotation, deleting the resource, upgrading and apply with `breaking` changes does the job. 

Resources tested: 
- dbformariadb/server [Discriminator]
- eventhub/namespace [Status Only]
- eventhub/namespaceseventhub [Unused]
- eventgrid/domain [Discriminator]
- eventgrid/eventsubscription [Inlined & Unused]
- authorization/roleassignment [Unused]
- web/site [Status Only]
