### ISSUE TITLE
Add support for latest version of Network

### ISSUE THREAD

**Issue by theunrepentantgeek** [Azure/azure-service-operator#2631]
In ASO `beta.4` we lost the `HyperNet` option for `GatewayType` on `VirtualNetworkGateway` as it's not listed in the Swagger spec for API version 2020-11-01.

We anticipate that adding support for the latest version of Network would bring this back.

**Comment by matthchr** [comment]
This is something we should probably consider doing for 2.2.0

**Comment by theunrepentantgeek** [comment]
I now believe the `HyperNet` option is gone permanently, as it doesn't appear in any of the recent stable versions of the Network apis. Suggest we close this issue.

**Comment by theunrepentantgeek** [comment]
Closing as suggested.
