### ISSUE TITLE
Bug: v2.0.0-beta.3 -> v2.0.0-beta.4: FlexibleServersDatabase unknown field "tags"

### ISSUE THREAD

**Issue by mehighlow** [Azure/azure-service-operator#2671]
**Version of Azure Service Operator**
ASOv2 beta.3: mcr.microsoft.com/k8s/azureserviceoperator:v2.0.0-beta.3,gcr.io/kubebuilder/kube-rbac-proxy:v0.13.0
ASOv2 beta.4: mcr.microsoft.com/k8s/azureserviceoperator:v2.0.0-beta.4,gcr.io/kubebuilder/kube-rbac-proxy:v0.13.0

**Describe the bug**
After v2.0.0-beta.3 -> v2.0.0-beta.4 upgrade, `FlexibleServersDatabase` doesn't recognize field "tags"

**To Reproduce**

- Steps to reproduce the behavior:
- install ASOv2 beta.3
- create `FlexibleServer` and `FlexibleServersDatabase` with `spec.tags` (helm-based deployment) 
- update ASOv2 to beta.4
- re-apply the same `FlexibleServersDatabase` helm chart
- observe ```Error: UPGRADE FAILED: error validating "": error validating data: ValidationError(FlexibleServersDatabase.spec): unknown field "tags" in com.azure.dbformysql.v1beta20210501.FlexibleServersDatabase.spec```

**Expected behavior**
v2.0.0-beta.3 -> v2.0.0-beta.4 upgrade works seamlessly for existing objects

**Screenshots**
N/A

**Additional context**
None

**Comment by theunrepentantgeek** [comment]
As mentioned in the `beta.4` [release notes](https://github.com/Azure/azure-service-operator/releases/tag/v2.0.0-beta.4), the release includes some breaking changes, resulting from our switch to using the Azure ARM Swagger API definitions as our sole source of truth (previously we were using both JSON schema AND Swagger API definitions).

The `tags` field of `FlexibleServersDatabase` has been [removed](https://azure.github.io/azure-service-operator/introduction/breaking-changes/#flexibleserversdatabase). According to the Swagger API specs, the `FlexibleServersDatabase` ARM resource doesn't support tags.

Our [breaking changes](https://azure.github.io/azure-service-operator/introduction/breaking-changes) documentation lists the steps required to upgrade existing resources.

**Comment by mehighlow** [comment]
Thanks @theunrepentantgeek . I should have ~~better~~ read the release notes.

**Comment by theunrepentantgeek** [comment]
It's easy to do. FWIW, we considered long and hard before reluctantly accepting the breaking changes.
