### ISSUE TITLE
Task: Implement usage of CSI driver 

### ISSUE THREAD

**Issue by jananivMS** [Azure/azure-service-operator#268]
Implement the operator to use the CSI driver to store secrets instead of flex volumes

This also came from the feedback from the AKS upstream team.

**Done criteria **
This is the "done" criteria for this task

- [ ] Secrets from the operator should be stored using CSI driver for the app to use

**User story reference***

#266

**Comment by matthchr** [comment]
ASO v1 is in maintenance mode - closing this as it is not a critical bug.
