### ISSUE TITLE
Add kube-rbac-proxy to MCR

### ISSUE THREAD

**Issue by rguptar** [Azure/azure-service-operator#2684]
**Describe the current behavior**
ASO references `gcr.io/kubebuilder/kube-rbac-proxy`.

**Describe the improvement**
Add `gcr.io/kubebuilder/kube-rbac-proxy` to MCR. It is common for popular open source images to be mirrored here. Search for "oss/kubernetes" in https://mcr.microsoft.com/v2/_catalog for some examples. Note that this does not require a change to the helm charts. Those who want to use a different registry, such as MCR, can override it during chart installation.

**Additional context**
In certain situations, access to MCR is available but not to GCR. Adding kube-rbac-proxy to MCR obviates the need for the developer to vendor the image in a private image registry.

Related to #715

**Comment by matthchr** [comment]
I see that there is `oss/kubernetes/kube-rbac-proxy` already in MCR - but I don't know what versions it supports or how it is maintained. We can look into that and if it will work for our use-case document it.

We'll also need to decide if we want to switch to use the MCR image by default or continue using the GCR one.

**Comment by matthchr** [comment]
@super-harsh pointed out that you can actually already do this with `--image.kubeRBACProxy=mcr.microsoft.com/oss/kubernetes/kube-rbac-proxy:v0.13.0`. 

Let us know if you need anything more than that.
