### ISSUE TITLE
update golang to fix cves

### ISSUE THREAD

**Issue by runzexia** [Azure/azure-service-operator#2723]
<img width="1018" alt="image" src="https://user-images.githubusercontent.com/31230341/218363947-7532b430-358f-4b83-a35b-ea4d09150f14.png">

**Comment by theunrepentantgeek** [comment]
@runzexia Would you be able to provide more information? 

A screenshot of a tool doesn't provide us with much to go on - for example, we have no way to know if our actions have resolved the issue or not.

**Comment by runzexia** [comment]
Upload the scanned repo, there are cves for k8s-azureserviceoperator:1.0.45297 images, the issues is in the golang
[k8s-azureserviceoperator1045297-2023-02-10-024016.pdf](https://github.com/Azure/azure-service-operator/files/10718967/k8s-azureserviceoperator1045297-2023-02-10-024016.pdf)

**Comment by runzexia** [comment]
hi @theunrepentantgeek is the pdf report help, do you need others information

**Comment by theunrepentantgeek** [comment]
The PDF is some help, yes. Thanks for supplying it.

**Comment by runzexia** [comment]
thanks for your reply, i have one question about that when would the fix version would be published, as we are running the security validation, requires us to fix this issue in recent days.

**Comment by theunrepentantgeek** [comment]
Do you have an explicit list of CVEs? Neither your screenshot nor the uploaded PDF actually list those.

**Comment by runzexia** [comment]
[k8s-azureserviceoperator1045297-vulnerabilities.csv](https://github.com/Azure/azure-service-operator/files/10751690/k8s-azureserviceoperator1045297-vulnerabilities.csv)
The list of cves
