### ISSUE TITLE
Bug: Documentation site not updating

### ISSUE THREAD

**Issue by theunrepentantgeek** [Azure/azure-service-operator#2783]
**Describe the bug**

Updates to our documentation site aren't being published due to stale credentials.

Failure log reads:
```
/usr/bin/git commit -m Deploying to gh-pages from @ Azure/azure-service-operator@c98253e80795b9a2e41daf32bc23d9405efe9377 🚀 --quiet --no-verify
/usr/bin/git push --force ***github.com/Azure/azure-service-operator.git github-pages-deploy-action/x3ooak50x:gh-pages
remote: Invalid username or password.
fatal: Authentication failed for 'https://github.com/Azure/azure-service-operator.git/'
```

**To Reproduce**

Look at our [deploy-site](https://github.com/Azure/azure-service-operator/actions/workflows/deploy-site.yml) action and review any failing run.

**Expected behavior**

Docs site should be updated shortly after each PR merges.

**Comment by theunrepentantgeek** [comment]
After updating the configured secret used by the action, this seems to be working. Can be closed at our next triage meeting.

**Comment by matthchr** [comment]
Closing this as it is fixed.
