### ISSUE TITLE
Improve coverage of Markdown linter

### ISSUE THREAD

**Issue by theunrepentantgeek** [Azure/azure-service-operator#2810]
**Describe the current behavior**

Currently we're using a Markdown Link checker, but it's not checking as much as it could, mostly due to the way Hugo renders our documentation website.

Essentially, we've hobbled the current checker so it only checks external links (those using the prefix `http` or `https`), but this leaves us vulnerable to errors/link-rot for internal links.

**Describe the improvement**

Improve our checks so we're checking internal links as well.

We may need to resort to absolute links in some cases, though that runs into a chicken-and-the-egg problem:
If we're publishing a new page and references to that page, references to the page on our website will fail because the page doesn't yet exist.

**Additional context**

When Hugo renders `documentation.md` it turns it into a folder containing an `index.html` file so that the URL is _clean_: E.g. "http://site/documentation".

The Markdown lint checker expects that relative paths are rooted from the folder containing `documentation.md` but, due to the way Hugo works, they must be written as though they're in the nested folder. 

End result: Markdown checker insists on `image.png` but we have to write `../image.png` for the browser.

Similar issues apply for document links.

**Comment by matthchr** [comment]
Closed by #2888
