### ISSUE TITLE
Publish raw YAML with just CRDs each release

### ISSUE THREAD

**Issue by matthchr** [Azure/azure-service-operator#2818]
**Describe the current behavior**
As part of making the operator pod manage CRDs (#2769), we removed the CRDs from the published YAML. This means there's no longer any place to get them.

**Describe the improvement**
We should publish a standalone CRD-only YAML for folks who want to manage the CRDs themselves, or who want the raw CRDs for other uses.

**Comment by tyler-adam** [comment]
+1, appreciate the attention on this - To echo what I said elsewhere, I plan to use [k8s-gen](https://github.com/jsonnet-libs/k8s) to generate Jsonnet libraries for these, and having them separate would be a huge help.
