### ISSUE TITLE
Support configuring Microsoft.Storage/storageAccounts/fileservices and tableServices

### ISSUE THREAD

**Issue by danmincu** [Azure/azure-service-operator#2824]
While playing with StorageAccounts in the `apiextensions.k8s.io_v1_customresourcedefinition_storageaccounts.storage.azure.com.yaml` contract we reaslized that there is no way to specify a fileShare soft delete policy on a storage account forcing us to go directly and call an AZ API endpoint to change that value.
This is the missing corresponding AZ property
```
 {
            "name": "[concat(parameters('storageAccountName'), '/default')]",
            "type": "Microsoft.Storage/storageAccounts/fileservices",
            "apiVersion": "2022-05-01",
            "properties": {
                "shareDeleteRetentionPolicy": {
                    "enabled": "[parameters('isShareSoftDeleteEnabled')]"
                }
            },
            "dependsOn": [
                "[concat('Microsoft.Storage/storageAccounts/', parameters('storageAccountName'))]",
                "[concat(concat('Microsoft.Storage/storageAccounts/', parameters('storageAccountName')), '/blobServices/default')]"
            ]
        }
```

Is it possible to somehow extend the schema of a givenCRD so when the operator creates the resource it takes the new property into account?
While searching through the schemas in `apiextensions.k8s.io_v1_customresourcedefinition_storageaccounts.*` namespace almost every one of the them defines `additionalProperties` all over the place? How can one use those properties? Any code examples?

**Comment by matthchr** [comment]
We don't even support the `Microsoft.Storage` `FileServices` resource: see [our list of supported storage resources](https://azure.github.io/azure-service-operator/reference/#storage)

Your goal is to set the `fileServices` `properties.shareDeleteRetentionPolicy`, yes? If so I think your actual ask for us is to support the `StorageAccountsFileService` resource similar to how we support `StorageAccountsQueueService`, or `StorageAccountsBlobService` today, is that right?

**Comment by danmincu** [comment]
the new CRD looks good - it just needs the "days" property on the `shareDeleteRetentionPolicy`

**Comment by matthchr** [comment]
We're also missing tableService, we should add support for that too
