### ISSUE TITLE
Feature: v2 migration path/tool

### ISSUE THREAD

**Issue by poolnitsol** [Azure/azure-service-operator#2828]
Any timeline on migration path/tool to move ASO v1 resources to ASO v2?

**Comment by poolnitsol** [comment]
Thanks, @theunrepentantgeek. Hope you're doing well. I was just wondering if you have any updates on the release date for v2.0.0?

**Comment by theunrepentantgeek** [comment]
All going to the current plan, within the next fortnight - I'll update here when we do so you know as soon as possible.

**Comment by matthchr** [comment]
Closing this in favor of #1238 - we can move discussion/questions over there.
