### ISSUE TITLE
asoctl crd clean should have better version selection logic

### ISSUE THREAD

**Issue by matthchr** [Azure/azure-service-operator#2849]
See [PR](https://github.com/Azure/azure-service-operator/pull/2846#discussion_r1160303245) for more context.

The algorithm I think we actually need is:
1. Use storage version to list all CRs. Extract the OriginalGVK field
2.  Swap v1alpha1 -> v1beta1 (for alpha deprecation) and save that as versionToUse for that CR
3.  Issue GET + PUT with versionToUse

**Comment by theunrepentantgeek** [comment]
Evaluating whether the current logic has the potential to cause loss of data, I found the following version transitions in the `compute` group where I think the current `asoctl` logic (selecting the oldest available storage version) might cause an issue:

| Type                            | Property                      |
| ------------------------------- | ----------------------------- |
| VirtualMachineScaleSet_Spec     | SpotRestorePolicy             |
| AutomaticRepairsPolicy          | RepairAction                  |
| VirtualMachineScaleSetVMProfile | ApplicationProfile            |
|                                 | CapacityReservation           |
|                                 | HardwareProvile               |
|                                 | UserData                      |
| AutomaticOSUpgradePolicy        | UseRollingUpgradePolicy       |
| VirtualMachineScaleSetOSProfile | AllowExtensionOperations      |
| VirtualMachineScaleSetDataDisk  | DeleteOption                  |
| VirtualMachineScaleSetExtension | ProtectedSettingsFromKeyVault |
|                                 | SuppressFailures              |

I think this shows enough hits to justify fixing this before GA. I haven't checked `containerservice` nor `dbforpostgresql`.
