### ISSUE TITLE
Use Merge Queues to merge PRs faster

### ISSUE THREAD

**Issue by theunrepentantgeek** [Azure/azure-service-operator#2890]
**Describe the current behavior**

Currently an approved PR often gets blocked because another PR has landed in `main` and all the builds need to run again.

Merge Queues are one solution to this problem - GH does builds on branches that are pre-merged with PRs ahead of the PR on the queue, allowing merging to occur faster.

**Describe the improvement**

Before enabling Merge Queues again, we need to solve these problems.

Issue #1: License not recognised - the existing `license/cla` check was blocking the queue even though we've all done that ages ago.

![image](https://user-images.githubusercontent.com/1272094/232620240-c450b4d1-58b2-4abe-8560-b6854b6176ed.png)

Issue #2: As it currently stands, we'd end up running all our tests twice. We need to think about partitioning our CI steps into quick-checks that run individually, and more comprehensive checks that run as a part of the queue.

Issue #3: For PRs that originate from branches outside the repo, we currently require approval via an `/ok-to-run` comment before CI runs. This is a security measure so we can review PRs for malicious intent before triggering CI. It's not clear how Merge Queues interact with this requirement.

**Additional context**

Depending on the effect of #2875 (More powerful CI machines), we may not need this.

**Comment by matthchr** [comment]
This seems like it doesn't work with the license/cla check.

**Comment by theunrepentantgeek** [comment]
The license/cla bot was updated, and I updated the workflows to work. Can now close this.
