### ISSUE TITLE
Feature: Workload Identity Federated Credentials

### ISSUE THREAD

**Issue by satrox28** [Azure/azure-service-operator#2898]
<Describe the feature request>

Hi,

We are looking to create azure federated credentials using ASO and based on that we can annotate the k8s service account.

Currently, this task need to be done either through Azure Portal or az cli or terraform, looking to have it as a k8s object.

```

Currently, there are several ways to create and delete a federated identity credential:

## Azure Workload Identity CLI

> NOTE: `azwi` currently only supports Azure AD Applications. If you want to use a user-assigned managed identity, skip this section and follow the steps in the Azure CLI section.
```

To create a federated identity credential:

```
azwi serviceaccount create phase federated-identity \
  --aad-application-name "${APPLICATION_NAME}" \
  --service-account-namespace "${SERVICE_ACCOUNT_NAMESPACE}" \
  --service-account-name "${SERVICE_ACCOUNT_NAME}" \
  --service-account-issuer-url "${SERVICE_ACCOUNT_ISSUER}"

```

**Comment by matthchr** [comment]
This already exists, see: https://github.com/Azure/azure-service-operator/blob/main/v2/samples/managedidentity/v1api/v1api20220131preview_federatedidentitycredential.yaml

**Comment by satrox28** [comment]
Hi @matthchr 

Thanks, we are looking for the same.

```
apiVersion: managedidentity.azure.com/v1beta20220131preview
kind: FederatedIdentityCredential
```

May I know, from which ASO version the CRD is available?.

**Comment by matthchr** [comment]
All of our resources have the version they were added in documented on our [Supported Resources page](https://azure.github.io/azure-service-operator/reference/#managedidentity)

![image](https://user-images.githubusercontent.com/8798850/232882971-7b60b131-d469-40be-ab04-36524694a36b.png)

See the "supported from" column.

**Comment by satrox28** [comment]
Thank you so much😀
