### ISSUE TITLE
Feature: add support for public DNS

### ISSUE THREAD

**Issue by bavarianbidi** [Azure/azure-service-operator#2901]
As `privateDNS` is already supported, i would like to have `publicDNS` supported as well.

https://azure.github.io/azure-service-operator/reference/#network

**Comment by matthchr** [comment]
Agree that this seems like a pretty big gap in our current support.

The actual resource in question is: https://learn.microsoft.com/en-us/azure/templates/microsoft.network/dnsZones, I believe. It has records in it like `privateDNSZone` does.

I've pulled this into our 2.1.0 milestone as it seems like it should be pretty similar to privateDNSZones which we already support.
