### ISSUE TITLE
Add PR workflow to check documentation links

### ISSUE THREAD

**Issue by theunrepentantgeek** [Azure/azure-service-operator#2902]
**Describe the current behavior**

We keep having broken links sneak through as a part of documentation PRs. Now that we've got `markdown-link-check` configured to check (almost) all links, we should routinely run that as a part of our PR validation.

**Describe the improvement**

Add a new workflow, triggered only by changes under `/docs/` that validates the links.

**Additional context**

There's a risk that a PR may be blocked if one of our external links breaks, but that seems an easy thing to address.

**Comment by matthchr** [comment]
This was fixed by #2909
