### ISSUE TITLE
Task: Eliminate old strings.Contains() error checking in favor of type casting style

### ISSUE THREAD

**Issue by aka-msft** [Azure/azure-service-operator#291]
We are currently using two files for handling errors: errhelp.go and errors.go.  Consolidate to using one file for ease of use/reference.

**Done criteria **
This is the "done" criteria for this task

- [ ] For eg. After this task is done, the "errhelp" references in sqlserver_controller.go and sqlaction_controller.go should point to "errors.go" instead.

**User story reference***

User story #149

**Comment by babbageclunk** [comment]
ASO v1 is in maintenance mode at this point, so we're not going to do this.
