### ISSUE TITLE
Bug: Docs page doesn't list new versions of ContainerService API in all locations

### ISSUE THREAD

**Issue by matthchr** [Azure/azure-service-operator#2921]
It's listed here:
https://azure.github.io/azure-service-operator/reference/#containerservice

but not here: https://azure.github.io/azure-service-operator/reference/containerservice/

**Comment by theunrepentantgeek** [comment]
Likely due to errors publishing the API docs that were fixed in #2912; running a manual publish to check.

**Comment by theunrepentantgeek** [comment]
Docs site now updated, but through a manual PR; still need to fix the workflow.
