### ISSUE TITLE
Feature: DiskEncryptionSets Support

### ISSUE THREAD

**Issue by satrox28** [Azure/azure-service-operator#2927]
<Describe the feature request>

Hi,

We would like to provision DiskEncryptionSets through ASO. It's not managable when running through az or arm templates right now for us.

**Comment by theunrepentantgeek** [comment]
We should be able to do this - it looks as though [DiskEncryptionSets](https://learn.microsoft.com/en-us/azure/templates/microsoft.compute/2022-07-02/diskencryptionsets?pivots=deployment-language-arm-template) are regular ARM resources.

We'll triage this into our backlog this week and update this issue with provisional scheduling. 

We would accept a PR with this resource if you're so inclined - we've got the process documented: [Adding a new code generated resource to ASO v2](https://azure.github.io/azure-service-operator/contributing/add-a-new-code-generated-resource/).
