### ISSUE TITLE
Feature: Support for Azure container marketplace offerings (Microsoft.KubernetesConfiguration/extensions)

### ISSUE THREAD

**Issue by dtzar** [Azure/azure-service-operator#2934]
Add ability to install any extension such as [Azure container marketplace offers](https://learn.microsoft.com/en-us/azure/aks/deploy-marketplace) or Arc Extension (e.g. Flux v2) onto AKS clusters.

[Rest API is here](https://github.com/Azure/azure-rest-api-specs/blob/main/specification/kubernetesconfiguration/resource-manager/Microsoft.KubernetesConfiguration/stable/2022-11-01/extensions.json)

**Comment by matthchr** [comment]
Marking this as needs triage so we discuss it in the next weeks meeting
