### ISSUE TITLE
increase test coverage for `set.go`

### ISSUE THREAD

**Issue by khareyash05** [Azure/azure-service-operator#2945]
**Describe the current behavior**
The current unit test coverage is 45% [https://app.codecov.io/gh/Azure/azure-service-operator/tree/master/v2/internal/set](https://app.codecov.io/gh/Azure/azure-service-operator/tree/master/v2/internal/set)

**Describe the improvement**
I would like to increase the test coverage

**Additional context**
NA

**Comment by matthchr** [comment]
If you want to increase coverage for that file, send us PR. I don't think there's much purpose in an issue tracking it though so I'm going to go ahead and close this.

PRs are always welcome.
