### ISSUE TITLE
Use azidentity WorkloadIdentityCredential instead of our version of one

### ISSUE THREAD

**Issue by matthchr** [Azure/azure-service-operator#2951]
**Describe the current behavior**
We adopted azidentity prior to WorkloadIdentityCredential support being fully implemented

**Describe the improvement**
See [this](https://github.com/Azure/azure-sdk-for-go/issues/15615#issuecomment-1350174008) - we can now use the official `azidentity.WorkloadIdentityCredntial` type and delete a bit of our code.

**Comment by super-harsh** [comment]
We should wait for this until azidentity 1.3.0 GA [release](https://pkg.go.dev/github.com/Azure/azure-sdk-for-go/sdk/azidentity?tab=versions).

**Comment by super-harsh** [comment]
Just noticed, azidentity release 1.3.0 is out
