### ISSUE TITLE
PropertyConversion should allow for returning error

### ISSUE THREAD

**Issue by theunrepentantgeek** [Azure/azure-service-operator#2967]
**Describe the current behavior**

The func type `conversions.PropertyConversion` doesn't allow for implementations to return an error.

This forces those implementations to either suppress problems or to panic when they occur.

**Describe the improvement**

We should change the signature to include an error return value and update all implementations to match. This should include conversion of any existing suppressions or panics where appropriate.

**Additional context**

This is one of a set of related improvements to address technical debt before it starts to cause us further issues.

**Comment by khareyash05** [comment]
Can i give it a try? @theunrepentantgeek  @matthchr

**Comment by theunrepentantgeek** [comment]
I've already got this well progressed in a WIP branch locally, so I think you'd be wasting your time. It's also a deceptive change - looks simple on the surface, but has considerable flow on effects.
