### ISSUE TITLE
Support for Application gateway

### ISSUE THREAD

**Issue by vimorra** [Azure/azure-service-operator#2990]
**Describe the current behavior**
Looking at the documentation seems that application gateway is not supported as part of the  Network section

**Describe the improvement**
The desired outcome is to manage application gateway resources via ASO v2

**Additional context**
Add any other context about the suggested improvement.

**Comment by theunrepentantgeek** [comment]
This appears to be a standard ARM resource: [Microsoft.Network/applicationGateways](https://learn.microsoft.com/en-us/azure/templates/microsoft.network/applicationgateways?pivots=deployment-language-arm-template#applicationgatewaypropertiesformat)

**Comment by vimorra** [comment]
> This appears to be a standard ARM resource: [Microsoft.Network/applicationGateways](https://learn.microsoft.com/en-us/azure/templates/microsoft.network/applicationgateways?pivots=deployment-language-arm-template#applicationgatewaypropertiesformat)

Just for my info, I was right to say that is not supported in the current version? I'm checking into this https://azure.github.io/azure-service-operator/reference/network/ and AppGateway is not listed, I'm correct
