### ISSUE TITLE
Provide supported instruction to install the operator withouth the webhook in watchers only mode

### ISSUE THREAD

**Issue by b1zzu** [Azure/azure-service-operator#3005]
**Describe the current behavior**

So there is this option `AZURE_OPERATOR_MODE` that can be set to `watchers` but doing so will not work because CRDs still require the `webhook`, so I would like to understand how is supposed to work in watchers-only mode, and maybe a documentation should be provided for future users.

**Describe the improvement**

Running the operator in watchers-only mode reduces unexpected behavior because, while having automated conversion of CRDs is nice for prototyping, in production I want full control over resources and mature resources that don't have to change every week.

**Additional context**

This is also the first operator that I have seen that takes a so dynamic approach, which again is very good for prototyping but doesn't provide the maturity and stability required to run in a production environment.

**Comment by matthchr** [comment]
There are multiple things here:

**How ASO installs CRDs** is indeed very dynamic. I'm in the process of writing some documentation on the how/why of that, but the basic summary is that we have so many CRDs that they exceed the maximum Helm chart size. So they cannot just be embedded in a Helm chart like most normal operators would. There are other operators that do something similar (Crossplane is one example).

> Running the operator in watchers-only mode reduces unexpected behavior because, while having automated conversion of CRDs is nice for prototyping, in production I want full control over resources and mature resources that don't have to change every week.

Can you expand on this? The webhooks are a critical part of the operator and used for multiple purposes:
1. Mutating webhooks, for performing defaulting. There are a few of these for each resource (for example setting `AzureName`). The operator won't function without these.
2. Validating webhooks, for validating CR shape. While the operator could technically function without these, they put a bunch of guardrails in place to help ensure CRs work. For example, preventing users from changing the owner of a resource once it has been created. You would want these guardrails in production as they protect your users from making mistakes.
3. CRD conversion webhooks. These are also required for the operator to function. They facilitate conversion between different versions of the CRDs (for example `v1beta20220101` to `v1api20220101` requires a call to the CRD conversion webhook. There is no risk associated with these though, the conversions are all round-trippable and ASO always uses the Azure API version corresponding to the most recent PUT on the CR, even if there are newer Azure API versions available

Could you maybe expand on what exactly you're worried about w.r.t. CRD conversion? CRD conversion isn't really "automatic", it happens only if the version of the CR stored in etcd is different than the requested version. As I mentioned above conversion is guaranteed to work and round-trip all properties. You allude to resources having to change every week but the conversion webhooks are exactly what enables your code to _not_ have to change, even if we ship newer versions of a particular resource.

For example, with the conversion webhooks enabled this workflow is fine:
1. You use `v1api20201201` of `Redis`.
2. We ship a new `v1api20230401` version of `Redis` in ASO `v2.2.0`.
3. You upgrade to ASO `v2.2.0`.
4. You can still continue using the older `v1api20201201` API for `Redis` and it will function exactly as before.

**Comment by matthchr** [comment]
I forgot to mention: The reason we have the two modes (webhooks vs watchers) is specifically to cater to certain [multitenancy scenarios](https://azure.github.io/azure-service-operator/guide/authentication/multitenant-deployment/#multiple-operator-multitenancy), where there is a single webhook operator and N watcher operators. This provides a security boundary between different teams, if for some reason you can't allow those teams to run with the same operator.

**Comment by theunrepentantgeek** [comment]
> while having automated conversion of CRDs is nice for prototyping

Automated conversion is _required_ by the Kubernetes contract for Custom Resources as soon as there is more than one version of that particular resource. All custom resources (even those with exactly one version) _must_ have a single nominated _hub_ version which is used internally for persistence to etcd, regardless of the version you use through the Kubernetes API.

The compatibility conversion requirement is that every version of a resource must be losslessly convertible to (and from) this hub version. We have both a [detailed design](https://azure.github.io/azure-service-operator/design/versioning/) and extensive property testing to ensure we meet this contract.

> in production I want full control over resources 

The ASO resource version you specify controls the ARM API version we use to talk to ARM, giving you full control. We work with precisely the version of the resource you specify when you create the resource.

**Comment by b1zzu** [comment]
Thanks for the explanations, and sorry for the ignorance in the field, my understanding at this point is not possible to deploy the operator without webhooks. The reason why I didn't want to have the webhooks is because with webhooks I can't deploy the operator and the resources that the resource in a single deployment.

**Comment by matthchr** [comment]
> I can't deploy the operator and the resources that the resource in a single deployment.

Ah yes, this is a pretty common restriction across many k8s operators AFAIK. You end up needing 2 steps: Cluster setup (where you install the operator) and then operator usage (where you install CRs).

Possibly this might be made easier if you could install the operator as an AKS addon or extension (via Azure when you provisioned your cluster?)
