### ISSUE TITLE
Write how-to guide for ASOv1 to ASOv2 migration

### ISSUE THREAD

**Issue by matthchr** [Azure/azure-service-operator#3006]
Explain how to use asoctl + skip-reconcile (asov1) + reconcile-policy (asov2) to achieve roll-forward/roll-back and safely migrate between the two.

Also mention the side-by-side pattern (v1 + v2 can be installed on the same cluster) and any best practices there.

**Comment by matthchr** [comment]
Copying rough outline from Slack to here:
The general process would be:
1. Use asoctl to export your existing resources from Azure into asov2 format
2. Mark the ASOv1 resources with skip-reconcile annotation, which prevents ASOv1 from doing anything with the resources.
3. Apply the ASOv2 resources exported from asoctl - these will adopt the existing resources in Azure.
4. Ensure things work, if good, delete ASOv1 resources - since they have skip-reconcile set, deletion will not propagate to Azure and instead just delete the resource from Kubernetes while leaving it in Azure being managed by ASOv2
5. If things dont work, can use the ASOv2 reconcile-policy annotation to stop ASOv2 reconciling the resource and remove ASOv1 resources skip-reconcile to roll-back to how you were managing things before.

**Comment by bwiens** [comment]
Thanks @matthchr for the general process. Yes, an official how-to guide for ASOv1 to ASOv2 migration would be super helpful.

**Comment by matthchr** [comment]
may need docs around operatorbundle too, given the fact we don't have one for ASov2

**Comment by waqasraz** [comment]
Does ASOv1 support reconcile-policy annotation?

**Comment by matthchr** [comment]
Yes, it's called: `skipreconcile=true`
