### ISSUE TITLE
Need updated V1 and new V2 ASO in Red Hat OpenShift Operator Hub

### ISSUE THREAD

**Issue by jimseld** [Azure/azure-service-operator#3028]
**Describe the current behavior**
Red Hat OpenShift Operator Hub has a very old ASO V1 28631 from September 2021, and does not have V2 at all.

**Describe the improvement**
Update V1 to the latest version available (59040), and add V2.

**Additional context**
Without updates, ASO has limited usefulness in OpenShift, and probably ARO too (Azure Red Hat OpenShift).

This person seems to be related to the maintenance: Christian Muirhead, aka babbageclunk in github.

**Comment by super-harsh** [comment]
Hi @jimseld, We're already looking into publishing ASOv2 in OperatorHub for which we have a draft PR #2929 and, #1967 issue to track the same. We're currently running into a few issues with the size of the operator exceeding the allowed limit as we support over 150 Azure resources hence having over 150 CRDs. I'm continuously connecting with the RedHat team to figure out a workaround if possible. 

PS: we can look into updating the ASOv1 operator while we figure out something for ASOv2.

**Comment by super-harsh** [comment]
@jimseld We've sent a PR to support [azure-service-operator (1.0.59040) operator bundle](https://github.com/redhat-openshift-ecosystem/community-operators-prod/pull/2828) which should be approved and merged soon.

Closing this issue as we have #1967 to track the ASOv2 operator bundle.
