### ISSUE TITLE
Feature: Export OIDC from Managed Cluster

### ISSUE THREAD

**Issue by theunrepentantgeek** [Azure/azure-service-operator#3031]
A [`ManagedCluster`](https://azure.github.io/azure-service-operator/reference/containerservice/v1api20230201/#containerservice.azure.com/v1api20230201.ManagedCluster) may optionally define an OIDC issuer for use with Federated Identity. We should allow publication of this value to a config-map to allow dynamic use by other resources.

See the property `oidcIssuerProfile` and the underlying type [`ManagedClusterOIDCIssuerProfile `](https://azure.github.io/azure-service-operator/reference/containerservice/v1api20230201/#containerservice.azure.com/v1api20230201.ManagedClusterOIDCIssuerProfile). The URL is available as `issuerURL` on the status.

(Requested in https://github.com/Azure/azure-service-operator/issues/2950 as an example of a wider requirement.)

**Comment by matthchr** [comment]
There's also a way to get this for the current cluster you're in, if you're in a cluster which is OIDC enabled. That has benefits if you want the FederatedIdentityCredential to apply on the cluster you're on (which you probably want to)
