### ISSUE TITLE
Pull image 2.1.0

### ISSUE THREAD

**Issue by HappyCodeHub** [Azure/azure-service-operator#3042]
Good Morning,

The chart helm version 2.1.0 has just been deployed however the images cannot be pull

Best regarde

**Comment by matthchr** [comment]
Issue seems to be that the image was tagged w/ the wrong tag in this job:
https://github.com/Azure/azure-service-operator/actions/runs/5138083115/jobs/9247021058

```
task: [controller:docker-tag-version] if [ -z "***" ]; then echo "Error: DOCKER_PUSH_TARGET must be set"; exit 1; fi
[controller:docker-build] Successfully tagged azureserviceoperator:v2.1.0-dirty
task: [controller:docker-tag-version] docker tag azureserviceoperator:v2.1.0-dirty "***/azureserviceoperator:v2.1.0-dirty"
```

**Comment by matthchr** [comment]
This is fixed now. Sorry about the issue - teething with our release automating

**Comment by HappyCodeHub** [comment]
Hello, 
Thank you for the quick correction. 
Have a good continuation.

Have fun !
