### ISSUE TITLE
Add readOnlyRootFilesystem and AllowPrivilegeEscalation to securityContext

### ISSUE THREAD

**Issue by EppO** [Azure/azure-service-operator#3056]
**Describe the current behavior**
Today, filesystem on the containers are not read-only and even though containers are running as non-root, privilege escalation is permitted. 

**Describe the improvement**
Containers shouldn't run with privilege escalation to root in your Kubernetes cluster.
The AllowPrivilegeEscalation attribute controls whether a process can gain more privileges than its parent process.
For these pods, set the AllowPrivilegeEscalation flag to 'false' on the security context of the container's spec.

Containers should run with a read only root file system in your Kubernetes cluster. Immutable filesystem protects containers from changes at run-time with malicious binaries being added to PATH.
 For these pods, set the readOnlyRootFilesystem flag to 'true' on the security context of the container's spec.

**Additional context**

**Comment by matthchr** [comment]
Thanks for the suggestion @EppO. We'll investigate doing this for the next ASO release.
