### ISSUE TITLE
Bug : ErrorCode: InvalidAddressPrefixFormat when trying to deploy IP Groups from Powershell

### ISSUE THREAD

**Issue by ggeorgiadis21** [Azure/azure-service-operator#3081]
When trying to create an IP Group, I get error:

$IPGroup_DRVnet_Name = 'IPGroup_DRVnet'
$IPGroup_DRVnet_Networks = '10.10.3.0/24,10.10.4.0/24,10.10.6.0/24,192.6.5.0/24,192.168.43.0/24,192.168.70.0/24,192.168.71.0/24,192.168.74.0/24,192.168.76.0/24,192.168.77.0/24,192.168.78.0/24,192.168.90.0/24'

New-AzIpGroup -Name $IPGroup_DRVnet_Name -ResourceGroupName $netRG -Location $Location -IpAddress $IPGroup_DRVnet_Networks

New-AzIpGroup: Operation returned an invalid status code 'BadRequest'
StatusCode: 400
ReasonPhrase: Bad Request
Status: Failed
ErrorCode: InvalidAddressPrefixFormat
ErrorMessage: IP Prefix  is invalid.

Ιf I run the same command like this

New-AzIpGroup -Name $IPGroup_DRVnet_Name -ResourceGroupName $netRG -Location $Location -IpAddress $IPGroup_DRVnet_Networks 10.10.3.0/24,10.10.4.0/24,10.10.6.0/24,192.6.5.0/24,192.168.43.0/24,192.168.70.0/24,192.168.71.0/24,192.168.74.0/24,192.168.76.0/24,192.168.77.0/24,192.168.78.0/24,192.168.90.0/24

the IP Group is created correctly

As far as I know, I cannot create a variable that without single or double quotes and the New-AzIpGroup -IpAddress  seems to accept string without quotes

Thanks 
GG

**Comment by theunrepentantgeek** [comment]
This doesn't seem to be a request about the Azure Service Operator project, so I'm going to close this as off topic.

However, a quick review of the [New-AzipGroup documentation](https://learn.microsoft.com/en-us/powershell/module/az.network/new-azipgroup?view=azps-10.0.0) shows that the `-IpAddress` parameter takes an array of strings `String[]` - you're passing all your IP Ranges as a single string when you need to pass each one as an individual string.

Given the array construction operator in PowerShell is `,` (the comma), you'll have to write something like this:

``` powershell
$IPGroup_DRVnet_Networks = '10.10.3.0/24', '10.10.4.0/24', '10.10.6.0/24', '192.6.5.0/24', 
'192.168.43.0/24', '192.168.70.0/24', '192.168.71.0/24', '192.168.74.0/24', '192.168.76.0/24', '192.168.77.0/24', '192.168.78.0/24', '192.168.90.0/24'
```
