### ISSUE TITLE
Bug: CustomResourceDefinition.apiextensions.k8s.io "storageaccounts.storage.azure.com" is invalid: metadata.annotations: Too long: must have at most 262144 bytes

### ISSUE THREAD

**Issue by b1zzu** [Azure/azure-service-operator#3093]
**Version of Azure Service Operator**

`2.1.0`

**Describe the bug**

When deploying the CRDs using `kubectl apply` the following error is logged from kubectl:
```
CustomResourceDefinition.apiextensions.k8s.io "storageaccounts.storage.azure.com" is invalid: metadata.annotations: Too long: must have at most 262144 bytes
```

**To Reproduce**

```
kubectl apply -f azureserviceoperator_customresourcedefinitions_v2.1.0.yaml 
```

**Comment by matthchr** [comment]
I believe you need to use `--server-side=true` (server side apply), see: https://azure.github.io/azure-service-operator/guide/installing-from-yaml/

This avoids storing the entire CRD in an annotation, which as you say, doesn't fit.

**Comment by matthchr** [comment]
Once you confirm the above fixes the issue, we'll close this issue.

**Comment by matthchr** [comment]
Closing this. Please comment/re-open if the above didn't solve your issue
