### ISSUE TITLE
Bug: ASO upgrade fails on AKS when Flux is installed via AKS extensions

### ISSUE THREAD

**Issue by abigailrmiller** [Azure/azure-service-operator#3127]
**Version of Azure Service Operator**
v2.1.0
```
azureserviceoperator-controller-manager   1/1     1            1           22h   manager,kube-rbac-proxy   mcr.microsoft.com/k8s/azureserviceoperator:v2.1.0,gcr.io/kubebuilder/kube-rbac-proxy:v0.13.1   control-plane=controller-manager
```

**Describe the bug**
helm upgrade fails when flux has been installed using k8s-extension. Flux installs the following CRDs:

- configsyncstatuses.clusterconfig.azure.com
- extensionconfigs.clusterconfig.azure.com
- fluxconfigs.clusterconfig.azure.com
- fluxconfigsyncstatuses.clusterconfig.azure.com

The name of these CRDs matches the pattern ASO pre-upgrade-checker looks for. As the CRDs do not set the "helm.sh/resource-policy"annotation the pre-upgrade-checker fails.

logs from pre-upgrade-checker:
```
I0706 13:11:58.691116       1 main.go:29] setup "msg"="Launching with flags" "flags"="MetricsAddr: 0, HealthAddr: , EnableLeaderElection: false, CRDPatterns: , PreUpgradeCheck: true"
E0706 13:11:59.152665       1 main.go:34] setup "msg"="pre-upgrade check failed" "error"="[CRD 'configsyncstatuses.clusterconfig.azure.com' does not have annotation for helm keep policy. Make sure the upgrade is from beta.5, CRD 'extensionconfigs.clusterconfig.azure.com' does not have annotation for helm keep policy. Make sure the upgrade is from beta.5, CRD 'fluxconfigs.clusterconfig.azure.com' does not have annotation for helm keep policy. Make sure the upgrade is from beta.5, CRD 'fluxconfigsyncstatuses.clusterconfig.azure.com' does not have annotation for helm keep policy. Make sure the upgrade is from beta.5]"
```

**To Reproduce**

- Install flux on AKS using az k8s-extension

```
 az k8s-extension create --cluster-type managedClusters --cluster-name $aksName --resource-group $resourceGroupName --name flux --extension-type microsoft.flux --configuration-settings "multiTenancy.enforce=false"
```
- Install Azure Service Operator using helm [as documented ](https://azure.github.io/azure-service-operator/#installation)
- Install succeeds
- Subsequent upgrades fail

**Expected behavior**
helm upgrade succeeds

**Screenshots**
helm upgrade logs:
![image](https://github.com/Azure/azure-service-operator/assets/92383170/a5ae156c-6600-4f5d-ba4b-5c6bde75ab16)
pre-upgrade-checker logs:
![image](https://github.com/Azure/azure-service-operator/assets/92383170/3aa685f9-a3f3-443f-aa96-dd0860acc6cd)

**Additional context**
Relevant code block: https://github.com/Azure/azure-service-operator/blob/659f57df8dc411aea6a86812e524ef441b1c254d/v2/cmd/controller/app/setup.go#L69C2-L87C3

**Comment by matthchr** [comment]
Thanks for the report. We were worried that regex was too broad (which is why we added the label we could also use). Looks like we need to rethink that a bit.

**Comment by theunrepentantgeek** [comment]
We could add a cross check that the resource identified by the regex is one of ours. I think we already have all the information onboard to do that.
