### ISSUE TITLE
TLS version on Azure Service Bus

### ISSUE THREAD

**Issue by sutterv** [Azure/azure-service-operator#3143]
Hello all, 

is there a way to set  the MinimumTlsVersion of an Azure Service Bus? 
I see we can do that in a Storage ([like here](https://azure.github.io/azure-service-operator/reference/storage/v1api20220901/#storage.azure.com/v1api20220901.StorageAccountPropertiesCreateParameters_MinimumTlsVersion)), but i can find any similar property in Service Bus documentation.

Thank you.

**Comment by theunrepentantgeek** [comment]
According to the [ARM documentation](https://learn.microsoft.com/en-us/azure/templates/microsoft.servicebus/namespaces?pivots=deployment-language-arm-template#sbnamespaceproperties-1) for ServiceBus Namespace, there should be a `minimumTlsVersion` property that you can set.

Looking at the [ASO documentation](https://azure.github.io/azure-service-operator/reference/servicebus/v1api20210101preview/#servicebus.azure.com/v1api20210101preview.Namespace), that property is missing! I'll investigate why and report back.

**Comment by theunrepentantgeek** [comment]
Found it - the `minimumTLSVersion` property was introduced in a newer version of the ARM API - it's not available in `2021-11-01`, but it is in `2022-01-01-preview` and newer.  Currently ASO [supports](https://azure.github.io/azure-service-operator/reference/servicebus/) only the earlier version `2021-01-01-preview`.

Adding the latest version of `ServiceBus` should be straightforward; I'll put this into our roadmap for **v2.3.0**.

**Comment by sutterv** [comment]
Thank you for your answer. So, we will vait for the 2.3.0 release.
