### ISSUE TITLE
Expose user-facing constants

### ISSUE THREAD

**Issue by nojnhuh** [Azure/azure-service-operator#3149]
**Describe the current behavior**
Currently, some constant variables that would be useful to import to other Go projects can't be because they are defined in `internal` packages.

e.g.
https://github.com/Azure/azure-service-operator/blob/0eb60541b2ac8c3b8d41ada52f9165cb2cbb8bd6/v2/internal/reconcilers/reconcile_policy.go#L16-L37
https://github.com/Azure/azure-service-operator/blob/0eb60541b2ac8c3b8d41ada52f9165cb2cbb8bd6/v2/internal/reconcilers/predicates.go#L18
https://github.com/Azure/azure-service-operator/blob/0eb60541b2ac8c3b8d41ada52f9165cb2cbb8bd6/v2/internal/config/vars.go#L17-L36

**Describe the improvement**
It would be helpful to projects like CAPZ if these definitions were either moved or mirrored to packages that external projects can import.

**Additional context**
Add any other context about the suggested improvement.

**Comment by matthchr** [comment]
Can put this into `genruntime` or maybe even better a `common`
