### ISSUE TITLE
Feature: Add Microsoft.Monitor capabilities

### ISSUE THREAD

**Issue by ashetonh-ad** [Azure/azure-service-operator#3173]
Our team would like to be able to manage Microsoft.Monitor azure resources like Azure Monitor Workspaces via the operator. Currently our options are having to use the Go SDK / ARM directly to create these resources via code.

**Comment by theunrepentantgeek** [comment]
If the resource can be deployed via ARM, then we should be able to easily add it to ASO. We'll check into the [Swagger spec](https://github.com/Azure/azure-rest-api-specs/tree/3ac733b1b1c63969fbed0c7ffe60ff5cccc708c7/specification/monitor/resource-manager/Microsoft.Monitor/preview/2021-06-03-preview).

**Comment by matthchr** [comment]
I missed closing this as part of #4052, but this will be supported in v2.8.0
