### ISSUE TITLE
Publish chart versions that are SemVer 2 compatible 

### ISSUE THREAD

**Issue by kengibous** [Azure/azure-service-operator#3189]
**Describe the current behavior**
Currently chart versions are being published with a prefix, "v" (example v2.2.0) which is not SemVer 2 compatible.  Such charts like aad-pod-identity are not including "v" in the version.

**Describe the improvement**
Consider dropping the "v" from publish charts so that the helm manifest provides SemVer 2 compatible versions.

**Additional context**
I believe the change could be as straightforward as changing - https://github.com/Azure/azure-service-operator/blob/main/v2/charts/azure-service-operator/Chart.yaml#L3 - to `version: 2.2.0`

**Comment by matthchr** [comment]
We'll look into this - need to think about impact on existing users, etc as well.

**Comment by kengibous** [comment]
@matthchr sounds good, I appreciate the consideration.

**Comment by kengibous** [comment]
@matthchr - i see that version 2.30 is released, but i do not see a published chart

**Comment by matthchr** [comment]
There was an issue with the 2.3.0 chart (unrelated to this issue). See #3259. We're fixing that and will republish the chart later today.

Sorry about that
