### ISSUE TITLE
Do we need to remove Hashicorp libraries?

### ISSUE THREAD

**Issue by theunrepentantgeek** [Azure/azure-service-operator#3202]
Hashicorp recently [announced](https://www.hashicorp.com/blog/hashicorp-adopts-business-source-license):

> That is why today we are announcing that HashiCorp is changing its source code license from Mozilla Public License v2.0 (MPL 2.0) to the Business Source License (BSL, also known as BUSL) v1.1 on all future releases of HashiCorp products. HashiCorp APIs, SDKs, and almost all other libraries will remain MPL 2.0.
> ...
> End users can continue to copy, modify, and redistribute the code for all non-commercial and commercial use, except where providing a competitive offering to HashiCorp. Partners can continue to build integrations for our joint customers.

Many of HashiCorp's products are described as "Deployment Automation" tools, a description that can equally be applied to Azure Service Operator, so it's unclear whether ASO project would be categorized as a competitor or not.

We should review our use of Hashicorp libraries by ASO to ensure we remain compliant with licensing.

**Comment by theunrepentantgeek** [comment]
There are four Hashcorp libraries referenced in the repo, all by ASO v1:

* [Go MultiError](https://github.com/hashicorp/go-multierror) 
* [ErrWrap](https://github.com/hashicorp/errwrap) 
* [UUID](https://github.com/hashicorp/go-uuid) 
* [Golang-LRU](https://github.com/hashicorp/golang-lru)
 
All of these libraries have MPL-2.0 licenses.

Given:
(a) The Hashicorp licensing change doesn't currently (as of August 2023) apply to these libraries;
(b) Any licensing change would apply only to future versions of these libraries; and
(c) ASO v1 is in maintenance mode, receiving only security updates and fixes for major bugs.

We don't believe any action is required at this time.

That said, the Hashicorp announcement was made recently and it's possible the effects of the change are not yet fully observable. We should leave this issue open and check back in a few months to confirm today's findings.

**Comment by matthchr** [comment]
Closing this - things seem (for now) to be stable and not a risk. We can revisit in the future if need be.
