### ISSUE TITLE
Feature: Support for publicNetworkAccess property for keyvault.azure.com

### ISSUE THREAD

**Issue by ahmadhusaini** [Azure/azure-service-operator#3217]
It would be great to include support for the 'publicNetworkAccess' property for keyvault.azure.com in order to enhance security while utilizing private endpoints.

**Comment by theunrepentantgeek** [comment]
Our current KeyVault support is based on version `2021-04-01-preview`. 

It appears the `publicNetworkAccess` property was introduced in `2021-06-01-preview`. We should import the latest stable version (`2022-07-01`) to provide access to the latest features.

**Comment by davidkarlsen** [comment]
+1 to apply the same on storageaccounts.
