### ISSUE TITLE
Have ManagedClusters reconcile again when hitting error code CustomKubeletIdentityMissingPermissionError

### ISSUE THREAD

**Issue by comptonad** [Azure/azure-service-operator#3267]
**Describe the current behavior**
When creating `UserAssignedIdentity`, `RoleAssignment`, and a `ManagedCluster` all at once that reference each other the resources can become deadlocked. The only remedy is manual intervention to modify the `ManagedCluster` or to delete the aso pod to force another reconcile.

Here is the status of the `ManagedCluster` when this happens

```
status:
  conditions:
  - lastTransitionTime: "2023-09-06T21:24:00Z"
    message: |
      The cluster using user-assigned managed identity must be granted 'Managed Identity Operator' role to assign kubelet identity. You can run 'az role assignment create --assignee <control-plane-identity-principal-id> --role 'Managed Identity Operator' --scope <kubelet-identity-resource-id>' to grant the permission. See https://learn.microsoft.com/en-us/azure/aks/use-managed-identity#add-role-assignment: PUT https://management.azure.com/subscriptions/{subid}/resourceGroups/{rgname}providers/Microsoft.ContainerService/managedClusters/{clustername}
      --------------------------------------------------------------------------------
      RESPONSE 400: 400 Bad Request
      ERROR CODE: CustomKubeletIdentityMissingPermissionError
      --------------------------------------------------------------------------------
      {
        "code": "CustomKubeletIdentityMissingPermissionError",
        "details": null,
        "message": "The cluster using user-assigned managed identity must be granted 'Managed Identity Operator' role to assign kubelet identity. You can run 'az role assignment create --assignee \u003ccontrol-plane-identity-principal-id\u003e --role 'Managed Identity Operator' --scope \u003ckubelet-identity-resource-id\u003e' to grant the permission. See https://learn.microsoft.com/en-us/azure/aks/use-managed-identity#add-role-assignment",
        "subcode": ""
      }
      --------------------------------------------------------------------------------
    observedGeneration: 1
    reason: CustomKubeletIdentityMissingPermissionError
    severity: Error
    status: "False"
    type: Ready
```

**Describe the improvement**
When the specific code `CustomKubeletIdentityMissingPermissionError` occurs retry the reconcile function. In this case, the `RoleAssignment` granting the necessary permissions just needed additional time to propagate.

**Additional context**
In the above scenario we're apply a large number of resources via flux and ideally they would eventually all reconcile into their ready states. This specific case is for creating a cluster with workload identity enabled. Will note that this is still not entirely possible without #2950.

**Comment by theunrepentantgeek** [comment]
If all that's required is for `ManagedCluster` reconciliation to continue when the error `CustomKubeletIdentityMissingPermissionError` occurs, this should be reasonably straightforward to do by implementing the [`ErrorClassifier`](https://github.com/Azure/azure-service-operator/blob/main/v2/pkg/genruntime/extensions/error_classifier.go) interface to reclassify that error as non-fatal.

An [example](https://github.com/Azure/azure-service-operator/blob/5bab50b8292ab8ea0a88773fc0c7cf1e1d64ea64/v2/api/compute/customizations/vm_extensions.go#L16) of this can be seen for VirtualMachines; the approach would be similar.

**Comment by theunrepentantgeek** [comment]
@comptonad - are you able to confirm that my understanding is correct? 

I'm stumped by your use of the term _deadlock_ in your original description.

**Comment by comptonad** [comment]
@theunrepentantgeek Aside from the classification stuff that I'm not familiar with, you are correct. The first few times I tried this the `ManagedCluster` controller would not reconcile again on the resource with that error, until I forced it to. So without that intervention it was stuck in that error state.

Will note that my last couple of attempts last week I did NOT hit this issue. I believe this was simply due to race condition where the `RoleAssignment` permissions _beat_ the cluster creation attempt. During these attempts I was applying a larger number of resources so I believe more time passed between these 2 steps. I'm going to continue testing this week so will update this issue if I have any other findings.

**Comment by theunrepentantgeek** [comment]
Thanks for the clarification. We'll implement the classification piece I mentioned earlier, which will change this to a non-fatal error, where ASO keeps trying to reconcile the cluster until the identity is available.
