### ISSUE TITLE
Feature: support publicNetworkAccess on storageaccount

### ISSUE THREAD

**Issue by davidkarlsen** [Azure/azure-service-operator#3372]
Note - this flag should not be confused with the existing `allowBlobPublicAccess` flag - it's not the same - although the naming is super-confusing similar (see https://github.com/MicrosoftDocs/azure-docs/issues/90530).

If you add the firewall, and want it to be default deny, but open for a given range of IPs, and only those, one need to flip this flag:
```
!diff
diff /tmp/before /tmp/after
64c64
<     "resourceAccessRules": null,
---
>     "resourceAccessRules": [],
97c97
<   "publicNetworkAccess": "Disabled",
---
>   "publicNetworkAccess": "Enabled",
```
this will flip network -> "Public network access" to "Enabled from selected virtual networks and IP addresses"

you can check this by going to the portal and change the toggle, and export the json with:
az storage account show --name <the account>

and compare before and after.

effectively this allows for a concervative setting, but enable opening from selected ranges and vnet service-endpoints.

**Comment by matthchr** [comment]
I think we need a new API version of storage for this.

**Comment by davidkarlsen** [comment]
Seems to have been there for some time? https://learn.microsoft.com/en-us/azure/templates/microsoft.storage/2021-01-01/storageaccounts?pivots=deployment-language-bicep

**Comment by matthchr** [comment]
oh. So it is. We already have this on the storage account.

You use it like:
```
spec:
  publicNetworkAccess: Disabled
```

You can see the backing Go code for it [here](https://github.com/Azure/azure-service-operator/blob/main/v2/api/storage/v1api20220901/storage_account_types_gen.go#L534).

Sorry I didn't notice that sooner.

**Comment by davidkarlsen** [comment]
Naaah:
```shell
for: "storage-account.yaml": error when patching "storage-account.yaml": admission webhook "default.v1api20220901.storageaccounts.storage.azure.com" denied the request: json: cannot unmarshal bool into Go struct field StorageAccount_Spec.spec.publicNetworkAccess of type v1api20220901.StorageAccountPropertiesCreateParameters_PublicNetworkAccess
```

**Comment by davidkarlsen** [comment]
ah - so it is - I missed it as it didn't show in the OCP api-explorer.
