### ISSUE TITLE
APIM Subscription: support $azureGeneratedSecrets for Primary and Secondary Keys

### ISSUE THREAD

**Issue by ross-p-smith** [Azure/azure-service-operator#3379]
Primary and Secondary Keys should be `$azureGeneratedSecrets`. However we still need to mark them as secret since users can provide their own primary and secondary keys as per documentation - **Primary subscription key. If not specified during request key will be generated automatically.**

_Originally posted by @super-harsh in https://github.com/Azure/azure-service-operator/pull/3376#discussion_r1348045981_

**Comment by matthchr** [comment]
I think that this actually is supported already, as long as we can figure out how to call the `ListSecrets` API from APIM to implement the `azureGeneratedSecrets` backend code.

**Comment by matthchr** [comment]
https://github.com/Azure/azure-rest-api-specs/blob/main/specification/apimanagement/resource-manager/Microsoft.ApiManagement/stable/2022-08-01/examples/ApiManagementSubscriptionListSecrets.json shows an example call to ListSecrets, it's not clear to me how/where to get the `  "sid": "5931a769d8d14f0ad8ce13b8"` value from.

**Comment by matthchr** [comment]
Closing this as we figured out the answer to the above.
