### ISSUE TITLE
Feature: Add support to CDN Profile AFD resources

### ISSUE THREAD

**Issue by ppotturi** [Azure/azure-service-operator#3382]
Hi Team, We plan to use the ASO with flux for our resource deployments, The existing CDN Profile doesn't support AFD resources. 

Please add support to the CDN Profile for the following resources: 

- AFD Endpoints/Routes
- Origin Groups/Origins
- Custom Domains
- Rules Sets/Rules
- Secrets
- Security Policies

**Comment by DaRoszko** [comment]
this ones quite important to us in the future - would love to get this one implemented asap

**Comment by owainow** [comment]
+1. This would be a great addition.

**Comment by matthchr** [comment]
https://learn.microsoft.com/en-us/rest/api/frontdoorservice/frontdoor/front-doors/create-or-update?view=rest-frontdoorservice-frontdoor-2019-05-01&tabs=HTTP

Closing #3737 in favor of this
