### ISSUE TITLE
APIM: Generate types that have no body (e.g. ProductAPI)

### ISSUE THREAD

**Issue by ross-p-smith** [Azure/azure-service-operator#3398]
There are a few APIM resources that are created with a PUT and no body. This causes them to not be generated.

Examples can be found in `/workspaces/azure-service-operator/v2/specs/azure-rest-api-specs/specification/apimanagement/resource-manager/Microsoft.ApiManagement/stable/2022-08-01/apimproducts.json`

- ProductApi
- ProductGroup
- ProductSubscription
- ProductPolicy
- ProductTag
- ProductWiki

We could change the generator to generate these types.

**Comment by matthchr** [comment]
I'm looking into this. I suspect the fix in the generator should be relatively easy.

**Comment by matthchr** [comment]
I have this fixed locally but realized that one gotcha is that these resources don't actually have a GET, which we rely on in the reconciler currently. We need to fix that too. 

Need some way to indicate at codegen time what operations a resource supports and then hook the operator in to looking at that. Shouldn't be too hard, will work on this as well.

**Comment by tomkerkhove** [comment]
https://github.com/Azure/azure-service-operator/issues/2747 depends on this
