### ISSUE TITLE
Allow programatic reuse of import functionality

### ISSUE THREAD

**Issue by theunrepentantgeek** [Azure/azure-service-operator#3399]
Expose the `import azure-resource` functionality from **asoctl** as a public library so that it can be reused.

Currently the functionality is in `internal` packages and can't be reused.

* Need to refactor to remove dependencies on console tools such as the multiple-progress-bar.

**Comment by ashetonh-ad** [comment]
this would help us immensely as we want to wrap the import process programmatically to allow for custom validation and formatting for our kube manifests and where they live.

**Comment by matthchr** [comment]
We're still interested in this.
