### ISSUE TITLE
Add TypeTransformers documentation for generator

### ISSUE THREAD

**Issue by super-harsh** [Azure/azure-service-operator#3401]
**Describe the current behavior**

Currently, we don't have any documentation for how to use `TypeTransformers` in azure-arm.yaml for the generator and what available options we can use. 

**Describe the improvement**

Add a documentation for: 
- What all can be TypeTransfomers used for
- An example usage for each scenario
- When to use

**Comment by theunrepentantgeek** [comment]
Closed by #3405
