### ISSUE TITLE
APIM: Product should delete any Subscriptions it owns when it deletes

### ISSUE THREAD

**Issue by ross-p-smith** [Azure/azure-service-operator#3408]
When you create an APIM Product it creates a Subscription. When you come to delete the Product, you will get an error saying you must delete the Subscription first

The ApiManagementDeleteProducts.json shows that an extra parameter is passed in the body 
`"deleteSubscriptions": true`

Map that field into the Code Generation

**Comment by matthchr** [comment]
I think that field is actually passed via the URL in REST: https://github.com/Azure/azure-rest-api-specs/blob/main/specification/apimanagement/resource-manager/Microsoft.ApiManagement/stable/2022-08-01/apimproducts.json#L365

as DELETE has no body.

I think in a perfect world we would know/remember/check if an APIM owned a subscription, and then pass `deleteSubscriptions: true` when it did?

Or maybe we need a flag on the object which flows into that? Unclear to me what exactly the best solution is but at the end of the day we have to pass the queryString parameter to the delete to make it delete the subscription too.

**Comment by ross-p-smith** [comment]
Here is the error at the moment

```txt
[controller:test-integration-envtest]     logr.go:278: I2023-10-12T12:20:13+01:00] ProductController "msg"="Reconcile invoked" name="asotestxrhkfo" namespace="aso-test-samples-creationanddeletion-test-apimanagement-v-88dd7" kind="&TypeMeta{Kind:Product,APIVersion:apimanagement.azure.com/v1api20220801storage,}" resourceVersion="1733" generation=2 uid="2a87b4a2-53f9-4cb7-b7b6-d7556b55cedb" ownerReferences=[]v1.OwnerReference{v1.OwnerReference{APIVersion:"apimanagement.azure.com/v1api20220801storage", Kind:"Service", Name:"asotestaerndr", UID:"d6c6e9e5-d3e6-4a85-85fe-d2a62503235f", Controller:(*bool)(nil), BlockOwnerDeletion:(*bool)(nil)}} creationTimestamp="2023-10-12 11:27:48 +0100 BST" deletionTimestamp="2023-10-12 12:16:59 +0100 BST" finalizers=[]string{"serviceoperator.azure.com/finalizer"} annotations=map[string]string{"serviceoperator.azure.com/resource-id":"/subscriptions/xxxxxx/resourceGroups/asotest-rg-nnxzgr/providers/Microsoft.ApiManagement/service/asotestaerndr/products/asotestxrhkfo"} conditions="[Condition [Ready], Status = \"False\", ObservedGeneration = 2, Severity = \"Warning\", Reason = \"Failed\", Message = \"deleting resource \\\"/subscriptions/xxxxxx/resourceGroups/asotest-rg-nnxzgr/providers/Microsoft.ApiManagement/service/asotestaerndr/products/asotestxrhkfo\\\": DELETE https://management.azure.com/subscriptions/xxxxxx/resourceGroups/asotest-rg-nnxzgr/providers/Microsoft.ApiManagement/service/asotestaerndr/products/asotestxrhkfo\\n--------------------------------------------------------------------------------\\nRESPONSE 400: 400 Bad Request\\nERROR CODE: ValidationError\\n--------------------------------------------------------------------------------\\n{\\n  \\\"error\\\": {\\n    \\\"code\\\": \\\"ValidationError\\\",\\n    \\\"message\\\": \\\"Product cannot be deleted since it has existing subscriptions. Delete subscriptions before deleting the product or pass in deleteSubscriptions=true as query param\\\",\\n    \\\"details\\\": null\\n  }\\n}\\n--------------------------------------------------------------------------------\\n\", LastTransitionTime = \"2023-10-12 12:19:13 +0100 BST\"]" owner="asotestaerndr, Group/Kind: apimanagement.azure.com/Service"
```

**Comment by matthchr** [comment]
Open questions here:
1. How do we know if we should or should not pass this parameter to the DELETE. Can we infer it from the Product somehow? Or, is it safe to always pass `deleteSubscriptions` because the service will not delete a "BYO subscription" that the product doesn't actually "own"?

**Comment by ross-p-smith** [comment]
When you ask the service to delete a product, I dont believe it will delete "other" subscriptions only ones that the product is associated with. Maybe @tomkerkhove can confirm.

Terraform will just pass this [parameter](https://github.com/hashicorp/terraform-provider-azurerm/blob/a4e9c91923fd893e62e11ed8cee9d13fa338ad8a/internal/services/apimanagement/api_management_product_resource.go#L201) when it deletes the Product.

**Comment by tomkerkhove** [comment]
> When you create an APIM Product it creates a Subscription. When you come to delete the Product, you will get an error saying you must delete the Subscription first

I don't know if this is correct, do we really create a subscription for a product automatically?

You can, however, create subscription resources and scope it just to the product. So personally, I'm not sure if we should delete these subscriptions automatically or leave it up to the end-user to make that decision given it can impact APIM customers their customers (what we call C2)

**Comment by tomkerkhove** [comment]
I think it will delete _all_ subscriptions - https://learn.microsoft.com/en-us/rest/api/apimanagement/current-ga/product/delete?tabs=HTTP#uri-parameters

**Comment by ross-p-smith** [comment]
I think that's just a badly worded sentence.

_Delete existing subscriptions associated with the product or not._

I think that is just describing the bool. I will test it

**Comment by ross-p-smith** [comment]
> do we really create a subscription for a product automatically

Yes. https://learn.microsoft.com/en-us/rest/api/apimanagement/current-ga/product/create-or-update?tabs=HTTP#request-body
_Whether a product subscription is required for accessing APIs included in this product. If true, the product is referred to as "protected" and a valid subscription key is required for a request to an API included in the product to succeed. If false, the product is referred to as "open" and requests to an API included in the product can be made without a subscription key. If property is omitted when creating a new product it's value is assumed to be true._

Looking at my ASO Integration test, it creates a Subscription when you create a Product

**Comment by matthchr** [comment]
The fact Terraform just always passes this parameter makes me think we should do the same.
