### ISSUE TITLE
Support collection of SecretReferences

### ISSUE THREAD

**Issue by super-harsh** [Azure/azure-service-operator#3435]
**Describe the current behavior**

Currently `isSecret` field for the generator, only lets us specify the string fields to mark as a secret reference.

**Describe the improvement**

We should be able to mark collections(map, slice) as a secret reference

**Additional context**

Prerequisite for #2934

**Comment by tomkerkhove** [comment]
I see it is mentioned that this is a requirement for https://github.com/Azure/azure-service-operator/pull/3528, but it has been merged.

Does that mean that this has been completed, @matthchr? I presume it is not?

**Comment by matthchr** [comment]
It's not done, we worked around it in #3528.

I'm working on this now though.
