### ISSUE TITLE
Add storage account name as a property to StorageAccountOperatorSecrets

### ISSUE THREAD

**Issue by jonasnorlund** [Azure/azure-service-operator#3446]
**Description**
Today when a storage account is created the operatorspec can create secrets and configmaps. Under the secrets creation there are a few properties but we are missing the storage account name as a property. 

If we want to automate the process of enabling storage for consumers of a namespace this is needed. 

Use ASO to create storage in one process using a GitOps flow (ArgoCD or Flux)
1. Create storage account (when the storage account is created a secret is also created with the key.) 
3. Create StorageAccountsFileService
4. Create StorageAccountsFileServicesShare   
5. Create a Persistent Volume which refers to the secret that has been created in step 1. The PV refers to the secret using  "nodeStageSecretRef.name" (https://github.com/kubernetes-sigs/azurefile-csi-driver/blob/master/docs/driver-parameters.md#static-provisionbring-your-own-file-share)

Next step would be to create a PVC but that fails due to the secret is missing the storage account name. 

This property is needed when working with static provisioning of PV's.

**Improvement**
Add the storage account name as a property to https://azure.github.io/azure-service-operator/reference/storage/v1api20220901/#storage.azure.com/v1api20220901.StorageAccountOperatorSecrets

**Comment by matthchr** [comment]
This seems very related to #2555, but it might make sense to do this now even though we have a longer term item to do better there.

**Comment by theunrepentantgeek** [comment]
Is the name of that storage account actually a secret? That is, is it sensitive? I'm wondering whether this should be published to a configmap instead.

**Comment by jonasnorlund** [comment]
Hi, when using secrets to authenticate against a PV (multitenant scenario when you don't want the kubelet identity to be used) you need the storage account name in the secret. 

See more info here https://github.com/kubernetes-sigs/azurefile-csi-driver/blob/master/docs/driver-parameters.md#tips

**Comment by matthchr** [comment]
Closing this in favor of #2555. We're committed to taking a generic approach here that allows export of any status field (as well as any secret). That way users can do whatever they want/need.
