### ISSUE TITLE
Update tooling

### ISSUE THREAD

**Issue by theunrepentantgeek** [Azure/azure-service-operator#3494]
**Describe the current behavior**

Post the v2.4.0 release, update to the latest appropriate versions of the tooling we use - including Go 1.21

**Comment by matthchr** [comment]
We should check with CAPZ if they will care if we update to Go 1.21

**Comment by theunrepentantgeek** [comment]
CAPZ indicated they'd prefer we didn't upgrade our go.mod files until they've moved to Go 1.21 themselves, but otherwise we should be good.

**Comment by theunrepentantgeek** [comment]
Closed by #3494
