### ISSUE TITLE
Add support for postgres 15 and 16

### ISSUE THREAD

**Issue by timja** [Azure/azure-service-operator#3627]
**Describe the current behavior**

https://azure.github.io/azure-service-operator/reference/dbforpostgresql/v1api20221201/#dbforpostgresql.azure.com/v1api20221201.ServerVersion

Uses ARM 2022-12-01 which only supports up to v14.
Unfortunately for whatever reason GA versions of the API haven't been released in ages even though the product is GA.

The 2023-06-01-preview API has support for both 15 and 16

**Describe the improvement**

Add an API version for 2023-06-01-preview postgres 

**Additional context**

Docs on how to add a new one would be nice I didn't see anything in the contribution guide

**Comment by matthchr** [comment]
Docs are here: https://azure.github.io/azure-service-operator/contributing/add-a-new-code-generated-resource/

But you're right it might be nice if a section called how specifically "how to add a new version", which is probably a subset of that doc.
