### ISSUE TITLE
ASO helm chart should allow specifying affinity and tolerations for pod deployments.

### ISSUE THREAD

**Issue by Roman-Galeev** [Azure/azure-service-operator#3646]
Otherwise the deployment may stuck for clusters configured with node taints.

**Comment by matthchr** [comment]
We have [podAnnotations](https://github.com/Azure/azure-service-operator/blob/main/v2/charts/azure-service-operator/values.yaml#L125) but agree it seems like it would be good to have more control than that.

**Comment by Roman-Galeev** [comment]
Yeah, podAnnotations are a bit different. When cluster nodes are tainted, tolerations is the only way to allow deployments.

**Comment by matthchr** [comment]
Ah yeah sorry, wasn't trying to imply that `podAnnotations` solved your problem, just saying I think these newly proposed fields could go next to that.
