### ISSUE TITLE
Introduce experimental image

### ISSUE THREAD

**Issue by tomkerkhove** [Azure/azure-service-operator#3682]
**Describe the current behavior**
As of today, you have to wait for a new release or build the container image yourself to have a preview image.

**Describe the improvement**
Introduce a nightly image that gets built every day, or even for every main push, that can be pulled for dev/test/experimentation through official channels.

**Additional context**
Relates to https://github.com/Azure/azure-service-operator/issues/3648

**Comment by tomkerkhove** [comment]
I am happy to contribute this if you are interested

**Comment by matthchr** [comment]
You're not the first to ask about this. It seems like it is probably a good idea for us to do some sort of nightly build. There's a couple things off the top of my head we need to do this:
1. The GitHub action (script + YAML) to actually publish a nightly (and name it, etc). I think we're close to having this already as we already have a version that is accessible in the `Taskfile`. We might need to add a date as well as right now it's just got a git hash.
2. The infrastructure to host the nightly - we have an ACR to publish to for the officials and we can probably just use that same ACR to publish the nightly as long as it has a clear name - we _might_ need to hook the new paths up to MCR I don't remember how that works.

**Comment by tomkerkhove** [comment]
That is what I have identified as well and started working on something, but I am new to Make so will need to get used to that a bit first.

The idea I have was actually to move from a nightly image and move to pushing a new image for every commit to main. What do you think about this? The idea is to use the SHA as the tag and potentially include a `main`/`preview` tag or so.

We can re-use the same registry, or push them to GitHub Container Registry to clearly distinguish that this is not for production. I'm open to anything here.
