### ISSUE TITLE
How can we support secrets in property of type map[string]string?

### ISSUE THREAD

**Issue by ansulgoenka** [Azure/azure-service-operator#3735]
https://learn.microsoft.com/en-us/azure/templates/microsoft.apimanagement/service/authorizationproviders?pivots=deployment-language-bicep#authorizationprovideroauth2granttypesauthorizationcode

```
resource symbolicname 'Microsoft.ApiManagement/service/authorizationProviders@2023-05-01-preview' = {
  name: 'string'
  parent: resourceSymbolicName
  properties: {
    displayName: 'string'
    identityProvider: 'string'
    oauth2: {
      grantTypes: {
        authorizationCode: {
          {customized property}: 'string'
        }
        clientCredentials: {
          {customized property}: 'string'
        }
      }
      redirectUrl: 'string'
    }
  }
}
```

AuthorizationCode is of type map[string]string and accepts ClientId and ClientSecret. ClientId is from managed Identity and ClientSecret is a secret and I need to pass these values to Authorization Code. Can you please give me some pointers on how to do this?

**Comment by theunrepentantgeek** [comment]
Did you mean to close this, @ansulgoenka ?

**Comment by theunrepentantgeek** [comment]
Support for collections and maps of secrets is being tracked in #3435.
