### ISSUE TITLE
Bug: MySQL Flexible Server property sourceServerResourceId has wrong type

### ISSUE THREAD

**Issue by theunrepentantgeek** [Azure/azure-service-operator#3772]
While responding to a [question on Slack](https://kubernetes.slack.com/archives/C046DEVLAQM/p1707656368127859), I spotted the property [FlexibleServer](https://azure.github.io/azure-service-operator/reference/dbformysql/v1api20210501/#dbformysql.azure.com/v1api20210501.FlexibleServer) `sourceServerResourceId` which looks to be an ARM resource ID, and therefore should be a `genruntime.ResourceReference` not a `string`.

We can't really change the existing version, but I think we should import the latest version(s) of the API (`2023-06-30` and maybe `2023-10-01-Preview`) and change it there.

**Comment by matthchr** [comment]
We should investigate how the heuristic missed this, and see if we can improve it - for example looking for properties that end in "resourceId" as I don't think it's doing that

**Comment by theunrepentantgeek** [comment]
Trying out some improvements to our heuristic and finding other properties we missed:

| Group | Version | Kind | Property |
| -- | -- | -- | -- |
| authorization | v1api20200801preview | RoleAssignmentProperties | DelegatedManagedIdentityResourceId |
| authorization | v1api20220401 | RoleAssignmentProperties | DelegatedManagedIdentityResourceId |
| dbformysql | v1api20210501 | ServerProperties | SourceServerResourceId |
| machinelearningservices | v1api20210701 | IdentityForCmk | UserAssignedIdentity |
| machinelearningservices | v1api20210701 | KeyVaultProperties | KeyVaultArmId |

We need to decide whether fixing these is important enough to have a breaking change, or whether we can do so without breaking.

**Comment by theunrepentantgeek** [comment]
We could make this _less_ of a breaking change if we modified `genruntime.ResourceReference` to allow deserialization from a plain string. We then wouldn't break existing resources, so in-place upgrades of ASO in an existing cluster would work fine. Users would still need to modify their resources to apply them though.

**Comment by matthchr** [comment]
> We could make this less of a breaking change if we modified genruntime.ResourceReference to allow deserialization from a plain string. We then wouldn't break existing resources, so in-place upgrades of ASO in an existing cluster would work fine. Users would still need to modify their resources to apply them though.

I think we've looked into this in the past and determined that it won't work because of Kubernetes structured schema requirements, specifically that they won't let you model that in the Swagger so even if the underlying Go type can do it, APIServer will (I believe) reject the request because it doesn't match the OpenAPI spec.

**Comment by matthchr** [comment]
Synced up and decided to first check what _new_ apiversions for these resource types are supported - possibly we can fix there in a totally nonbreaking way.

**Comment by theunrepentantgeek** [comment]
For the three identified groups, the latest available versions are:

| Group | Stable | Preview |
| -- | -- | -- |
| authorization | 2022-04-01 | 2020-10-01-preview |
| dbformysql | 2023-06-30 | 2023-10-01-preview |
| machinelearningservices | 2023-10-01 | 2023-08-01-preview |
