### ISSUE TITLE
Re-record flaky resource tests

### ISSUE THREAD

**Issue by theunrepentantgeek** [Azure/azure-service-operator#3835]
**Describe the current behavior**

Some of our tests are currently flaky due to timing issues during playback of recordings.

**Describe the improvement**

Post merge of PR #3753 we should re-record those tests that are known to be flaky, so that our CI process becomes more reliable.

**Additional context**

Tests to re-record

- [x] Test_Workspace_BigDataPool
- [ ] Test_Owner_IsMutableIfNotSuccessfullyCreated
- [ ] Test_MissingSecret_ReturnsError_ReconcilesSuccessfullyWhenSecretAdded 
- [ ] Test_DBForPostgreSQL_FlexibleServer_20230601Preview_CRUD
- [ ] Test_Samples_CreationAndDeletion/Test_Synapse_v1api_CreationAndDeletion
- [ ] Test_Multitenant_SingleOperator_PerResourceCredential

**Comment by matthchr** [comment]
We need to deduplicate this and the other flaky test tracking
