### ISSUE TITLE
Bug:  Azure Service Operator Incorrectly Denying '_' Character in Azure Resource Group Names

### ISSUE THREAD

**Issue by eiriksanderfjeld** [Azure/azure-service-operator#3932]
**Version of Azure Service Operator**
ASO V2:  mcr.microsoft.com/k8s/azureserviceoperator:v2.6.0,gcr.io/kubebuilder/kube-rbac-proxy:v0.13.1

**Describe the bug**
The Azure Service Operator is incorrectly denying the usage of the "_" (underscore) character in Azure Resource Group names. This restriction is not consistent with Azure's naming conventions and is causing inconvenience to users who wish to include underscores in their resource group names.

**To Reproduce**
1.  Attempt to create an Azure Resource Group using the Azure Service Operator.
2.  Include the "_" character in the name of the resource group.
3.  Notice that the operation fails with an error indicating that the "_" character is not allowed.

**Expected behavior**
According to Azure's naming conventions, the _ character is a valid character for resource group names. The Azure Service Operator should allow the usage of "_" in resource group names without any restrictions.

Actual Behavior:
The Azure Service Operator is denying the usage of the "_" character in resource group names, contrary to Azure's naming conventions.

`The ResourceGroup "dev_resources" is invalid: metadata.name: Invalid value: "dev_resources": a lowercase RFC 1123 subdomain must consist of lower case alphanumeric characters, '-' or '.', and must start and end with an alphanumeric character (e.g. 'example.com', regex used for validation is '[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*')`

**Additional context**
The rg.yaml file used apply the resoure group. 

```
apiVersion: resources.azure.com/v1api20200601
kind: ResourceGroup
metadata:
  name: dev_resources
  namespace: default
spec:
  location: westeurope
```

**Comment by matthchr** [comment]
You're running into a situation where what _Kubernetes_ allows for names differs from what Azure allows for names.

We have the `.spec.azureName` field for this reason. You can't name the Kubernetes representation of the resource group with an `_` in it, so you have two choices:

1. Pick a different name, if you want the k8s `ResourceGroup` and the Azure resource group to have the same name.
2. Pick a different name _for the Kubernetes resource_ and set `azureName` to `dev_resources`

**Comment by matthchr** [comment]
Closing this as it's working as designed. Please feel free to reply if you have any additional quesitons.
