### ISSUE TITLE
Bug: BackupVaultBackupInstance resource comes to ready state inside cluster even when the protection state is "configuring protection"

### ISSUE THREAD

**Issue by mayankagg9722** [Azure/azure-service-operator#3985]
ASO V2 - v2.7.0

Resource Provider: Microsoft.DataProtection

**Describe the bug**
BackupVaultBackupInstance resource comes to ready state inside cluster even when the protection state is "configuring protection" in Azure. Also when protection state changes to "protection configured", the YAML of the resource is not refreshed and took long time before it shows the right updated details that is shown in Azure portal. This might cause confusion for the customers.

**To Reproduce**
1) Post performing all the prerequisutes create the BackupVaultBackupInstance resource in the cluster using ASO. 
2) BackupVaultBackupInstance will come to ready state immediately, but the protection state is configuring protection.

**Expected behavior**
BackupVaultBackupInstance resource should be in waiting state (or show some message along with ready state) until the protection state changes from configuring protection to protection configured. Also, the refresh/fetch rate should be immediate so that misinformation is not communicated to customers from Azure portal and in ASO resource YAML.

**Screenshots**
![image](https://github.com/Azure/azure-service-operator/assets/17884128/3f30b43c-9522-44b5-8686-7d2b1e7ae4f6)
![image](https://github.com/Azure/azure-service-operator/assets/17884128/19f83b71-90ca-4a84-a7d3-3a2b8e3e2c83)
![image](https://github.com/Azure/azure-service-operator/assets/17884128/1f26a383-1008-430c-a935-aabc318b7b47)
![image](https://github.com/Azure/azure-service-operator/assets/17884128/e9819801-c05a-418e-95a2-44aa6134eabd)

**Comment by mayankagg9722** [comment]
Discussed with @theunrepentantgeek offline.

**Comment by theunrepentantgeek** [comment]
We agree that the resource shouldn't show Ready **true** until protection is fully configured; we'll look into updating this.
(Reference links included in the original Conditions ADR.)

**Comment by super-harsh** [comment]
Fixed in #4180
