### ISSUE TITLE
Feature: Specify Workload Environment Type When Creating a Azure SQL Database

### ISSUE THREAD

**Issue by moiacsidi** [Azure/azure-service-operator#4001]
I would like to be able to create databases with a environment type : **Development** and compute tier **Serverless.**

If this feature is supported the documentation is not very clear on it: 
https://azure.github.io/azure-service-operator/reference/sql/v1api20211101/#sql.azure.com/v1api20211101.ServersDatabase

Feature in Portal:

![image](https://github.com/Azure/azure-service-operator/assets/140609941/b7ff23c1-314c-4c5a-84fd-394079a83731)

**Comment by theunrepentantgeek** [comment]
From a quick look, it seems the portal is offering a convenience feature - selecting "Development" or "Production" just preconfigures your instance, and doesn't appear on the final resource. I think it's setting up a [`WorkloadGroup`](https://learn.microsoft.com/en-us/azure/templates/microsoft.sql/servers/databases/workloadgroups?pivots=deployment-language-bicep) but I may be wrong (I've run out of time to look further today).

**Comment by moiacsidi** [comment]
Thanks @theunrepentantgeek
