### ISSUE TITLE
Batch Job - Pre update checker should honor toloration/affinity

### ISSUE THREAD

**Issue by tikicoder** [Azure/azure-service-operator#4114]
**Describe the current behavior**
There is not tolerations or affinity applied to the batch job.
v2/charts/azure-service-operator/templates/pre-release-hook/batch_v1_job_pre-upgrade-checker.yaml

**Describe the improvement**
I would presume if I have created tolerations/node affinity that it would use that as part of its creation to ensure its not interfering with other node pools

**Comment by theunrepentantgeek** [comment]
Possibly related to #3436

**Comment by tikicoder** [comment]
@theunrepentantgeek Thanks, that does look to be the cause of my issue
#3436

I will look to monitor that milestone and hope it is included.

**Comment by matthchr** [comment]
Going to go ahead and close this in favor of #3436 - which should ideally be happening in 2.9.0
