### ISSUE TITLE
ASO V1 Deprecation

### ISSUE THREAD

**Issue by AriLFrankel** [Azure/azure-service-operator#4140]
Howdy
I'm looking for some input on whether there are any short term plans to deprecate any APIs in use by ASO V1? As my team looks to prioritize upgrading from V1 → V2, we are trying to understand the level of urgency of this upgrade. 
Thank you :)

**Comment by matthchr** [comment]
Azure themselves is deprecating MySQL single server and PostgreSQL single server, so if you're using either of those two resources there is a deadline for migration. That change is outside of the ASO teams control as the whole Azure resource is being deprecated, regardless of if it's created via ASO, BICEP, Terraform, etc.

Other than that, there's nothing we're doing to _force_ you off of ASOv1 in any particular timeframe. ASOv1 should continue to work. With that said, ASOv1 is EoL at this point and we're not updating it regularly anymore. We would definitely recommend you look into migrating from ASOv1 -> ASOv2 when you have time. We've got a document on tips for performing that migration [here](https://azure.github.io/azure-service-operator/guide/asov1-asov2-migration/). If you run into any issues or gaps in that process let us know.

**Comment by matthchr** [comment]
Closing this as we believe the question has been answered. If not, feel free to reply here or reopen the issue.
