### ISSUE TITLE
Avoid assigning illegal names when importing resources

### ISSUE THREAD

**Issue by theunrepentantgeek** [Azure/azure-service-operator#4156]
**Describe the current behavior**

When doing an import from Azure, `asoctl import azure-resource` currently assigns the name of the Azure resource as the name of the Kubernetes cluster - but as reported in #4153 not all legal Azure names are legal Kubernetes names.

**Describe the improvement**

Sanitize the names to ensure they're Kubernetes compliant, filling in AzureName where required to maintain the name used in Azure.

**Additional context**

Ownership references need to be updated too.

**Comment by theunrepentantgeek** [comment]
Should we consider lowercasing the cluster names as well?

**Comment by matthchr** [comment]
Yeah because RFC1123 doesn't allow uppercase, so probably we should do a normalization pass that includes removal of characters that don't comply.
