### ISSUE TITLE
Question: Can the kubelet Identity be stored in the same configmap where principaI Id is stored

### ISSUE THREAD

**Issue by RSE132** [Azure/azure-service-operator#4163]
**aso v2 - v2.7.x**

**Current State**
Currently managed cluster creates a configmap where the principal id is stored. 

**Expected behavior**
I want kubelet identity object id to be stored in the same configmap along with principal id so that `RoleAssignment` CRD could refer the kubelet object id from configmap. I want this feature because I want to assign permission to kubelet only instead of entire AKS  

**Question**
Does this feature already exist ? Just wanted to make sure that I am not missing anything. Currently I see `managedcluster` crd only allows below to be created 
- `.spec.operatorSpec.configMaps.principalId`
- `.spec.operatorSpec.configMaps.oidcIssuerProfile`

Expecting an addition filed `.spec.operatorSpec.configMaps.kubeletObjectId`

**Comment by RSE132** [comment]
Any update on having kubeletObjectId in configmap ?

**Comment by matthchr** [comment]
I don't think that this is supported now, but we are working towards support for this, see #2555.

With our plans for that, you can export anything you want on the spec or status of the object to wherever you want it.

**Comment by matthchr** [comment]
This slipped to 2.10.0 as I had some snags with the implementation, but I am working on it and it should make 2.10.0.

**Comment by matthchr** [comment]
Going to go ahead and close this in favor of using #2555 tracking it. As I mentioned above, I am working through the implementation for it right now and it should make 2.10.0
