### ISSUE TITLE
Add support to hide custom recording data while recording tests

### ISSUE THREAD

**Issue by super-harsh** [Azure/azure-service-operator#4172]
**Describe the current behavior**

Currently, we only support pre-defined regex matchers to redact/hide recordings data and don't have support to hide custom test data while recording tests dynamically

**Describe the improvement**

Add a function to support redaction of custom data like ClientIds, PrincipalIds etc in the test so that no sensitive data is added into the recordings. This can be configured dynamically depending upon the needs of the test.

**Comment by theunrepentantgeek** [comment]
We should assess any use of this functionality to see if our generic redaction needs to be extended (so that we don't have a dozen tests all individually redacting the same thing, for example).
