### ISSUE TITLE
Feature: support Microsoft.Network/serviceEndpointPolicies

### ISSUE THREAD

**Issue by vronnG** [Azure/azure-service-operator#4199]
Support Microsoft.Network/serviceEndpointPolicies
```
asoctl import azure-resource /subscriptions/XXXXXXX/resourceGroups/rg-networking-xxxxxx-westus3/providers/Microsoft.Network/serviceEndpointPolicies/xxx-test --output aso.yaml
11:23:43 ERR Failed error="unable to determine GVK of resource: unable to determine resource type from ID /subscriptions/xxxxxxxxxx/resourceGroups/rrg-networking-xxxxxx-westus3/providers/Microsoft.Network/serviceEndpointPolicies/xxx-test" kind= name=xxx-test
```

**Comment by theunrepentantgeek** [comment]
Currently ASO supports Microsoft.Network/serviceEndpointPolicies as embedded details within a [VirtualNetworksSubnet](https://azure.github.io/azure-service-operator/reference/network/v1api20201101/#network.azure.com/v1api20201101.VirtualNetworksSubnet), but not as an independent resource.

We could possibly change this, but it would be a breaking change to existing ASO users with `VirtualNetworksSubnet` resources in their clusters. 

You should be able to import them with `asoctl` by importing the VirtualNetworkSubnet containing the policy.
