### ISSUE TITLE
Feature: Support for creating Diagnostic Settings via ASO

### ISSUE THREAD

**Issue by nishant221** [Azure/azure-service-operator#4248]
This is a request to add  [Diagnostic settings in Azure Monitor](https://learn.microsoft.com/en-us/azure/azure-monitor/essentials/diagnostic-settings) in `Support Resources" list of ASO.

**Comment by matthchr** [comment]
It looks like these are ARM resources, here is a sample ARM template:
https://learn.microsoft.com/en-us/azure/azure-monitor/essentials/resource-manager-diagnostic-settings?tabs=bicep

**Comment by dtzar** [comment]
So is this something which can be done already or needs to be added with ASO?

**Comment by nraooptum** [comment]
Curious about this as well. @matthchr are you saying we can deploy arbitrary ARM templates through ASO? That would bridge the gap in the interim for us as well, kind of like how the azapi provider in terraform is like an escape hatch for the official azurerm provider.

**Comment by matthchr** [comment]
It can't already be done: I'm just saying it shouldn't be that hard to add. ASO is set up to generate CRDs for ARM resources relatively easily.

We don't currently have support for arbitrary ARM resources but we have an item tracking that here: https://github.com/Azure/azure-service-operator/issues/4028

**Comment by matthchr** [comment]
The above linked PR resolved this issue. Closing.

Thanks for the contribution @nishant221
