### ISSUE TITLE
ArgoCD health indicator colors

### ISSUE THREAD

**Issue by neil-119** [Azure/azure-service-operator#4258]
Not sure if this the right place to post this, but ArgoCD shows green on the custom resources for ASO even when the status field in the CR shows errors. Has anyone figured out how to get ArgoCD to show realistic indicator colors for ASO resources yet?

**Comment by neil-119** [comment]
I'll see if I can create my own lua script for it.

https://argo-cd.readthedocs.io/en/stable/operator-manual/health/

**Comment by theunrepentantgeek** [comment]
You should be able to use our [`Ready` condition](https://azure.github.io/azure-service-operator/guide/conditions/) in your LUA script. 

I'm surprised that ArgoCD doesn't check for that by default, but they probably have a good reason for this.

**Comment by neil-119** [comment]
> I'll see if I can create my own lua script for it.
> 
> https://argo-cd.readthedocs.io/en/stable/operator-manual/health/

Just an update -- the sample script that was provided in the link above (for crossplane) also works for ASOP v2.

**Comment by nraooptum** [comment]
Just a small update -- the above script _almost_ works. I had to make some tweaks:

```
"*.azure.com/*":
  health.lua: |
    hs = {}
    if obj.status ~= nil then
      if obj.status.conditions ~= nil then
        for i, condition in ipairs(obj.status.conditions) do
          if condition.type == "Ready" and condition.status == "False" and condition.reason ~= nil and condition.reason ~= "Reconciling" then
            hs.status = "Degraded"
            hs.message = condition.message
            return hs
          end
          if condition.type == "Ready" and condition.status == "True" then
            hs.status = "Healthy"
            hs.message = condition.message
            return hs
          end
        end
      end
    end

    hs.status = "Progressing"
    hs.message = "Waiting for ASO"
    return hs
```
