### ISSUE TITLE
Support for provisioning resources to different subscriptions

### ISSUE THREAD

**Issue by old-guy-coder** [Azure/azure-service-operator#4284]
**Describe the current behavior**
A description of how things are today.

Current behavior is that any Azure resources created in the cluster will be created in the same subscription, we need a way to provision resources across multiple subscriptions to deal with Azure resource limits per subscription (f.e. SQL Server, SQL Database.

**Describe the improvement**
How should things be changed or improved?

Would like to see the support to be able to specify which subscription a resource could be provisioned in, this would require a managed identity with permissions over the subscriptions and then we would need a way through annotations to specify which subscription we want the resources deployed into, for example in an overflow scenario.

**Additional context**
Add any other context about the suggested improvement.

**Comment by theunrepentantgeek** [comment]
ASO already supports deploying resources across multiple subscriptions, by using [scoped credentials](https://azure.github.io/azure-service-operator/guide/authentication/credential-scope/). 

The most usual approach is to create a credential with _namespace_ scope - this will be used for all ASO resources in that cluster namespace. One of the fields in a credential is the AZURE_SUBSCRIPTION for which the credential is to be used (see [Credential Format](https://azure.github.io/azure-service-operator/guide/authentication/credential-format/)).

Alternatively, you can apply the annotation `serviceoperator.azure.com/credential-from` to any ASO resource to specify which credential should be used, allowing you to freely distribute resources across multiple subscriptions within a single cluster namespace.

**Comment by theunrepentantgeek** [comment]
Closing as no further response. Feel free to reopen if you have any further questions.
