### ISSUE TITLE
Feature: Support for creating Application Security Groups via ASO

### ISSUE THREAD

**Issue by nishant221** [Azure/azure-service-operator#4291]
This is a request to add [Application security groups](https://learn.microsoft.com/en-us/azure/virtual-network/application-security-groups) in `Support Resources" list of ASO.

**Comment by matthchr** [comment]
I think the REST API for this is here: https://learn.microsoft.com/en-us/rest/api/virtualnetwork/application-security-groups/create-or-update?view=rest-virtualnetwork-2024-03-01&tabs=HTTP
