### ISSUE TITLE
Long term support and future of this project

### ISSUE THREAD

**Issue by artisticcheese** [Azure/azure-service-operator#4435]
Hello,

I can see that this project is not officially supported my Microsoft but wondering if there is path where this project is incorporated into main Azure AKS offering and hence will be get official support and cadence from Microsoft.
This is probably a big stumbling block for adoption for bigger companies.

Greg

**Comment by matthchr** [comment]
You can see the [FAQ](https://azure.github.io/azure-service-operator/guide/frequently-asked-questions/#what-is-the-support-model), which covers this somewhat.

> Azure Service Operator is an officially supported Microsoft OSS product. Currently, support is done via GitHub issues or the azure-service-operator channel of the [Kubernetes Slack](https://kubernetes.slack.com/). There are plans to integrate ASO into AKS as an addon after ASO has officially gone GA. At that point, support for ASO as an AKS addon would be accessed by raising an Azure support ticket.

It is probably worth highlighting that every core maintainer of ASO works at Microsoft, in the AKS product group. We do have an open item tracking making ASO an Azure Kubernetes Extension, (see #4344) - the ability to create support tickets (via the Azure Portal for example) will come as part of that effort. Do keep in mind that regardless of the support channel, GitHub or support ticket, the MSFT ASO engineering team will be the ones responding.
