### ISSUE TITLE
Bug: Parameterize regions used in tests

### ISSUE THREAD

**Issue by frodopwns** [Azure/azure-service-operator#496]
**Describe the bug**
Hard coded region in sqlclient end_to_end test file. The region being used `eastus2` sometimes is at max capacity for Visual Studio Enterprise accounts. This is troublesome because I do most of my testing in that account. 

https://github.com/Azure/azure-service-operator/blob/94b83810299d88b34b2846e276f3bca39b841086/pkg/resourcemanager/sqlclient/endtoend_test.go#L40

**To Reproduce**
- Use a service principal from a free developer account to run the operator, run the end to end tests.

should get an error like this

```
2019/12/05 16:16:39 cannot create sql server: sql.ServersCreateOrUpdateFuture#Result: Polling failure: StatusCode=200 -- Original Error: Code="RegionDoesNotAllowProvisioning" Message="Location 'East US 2' is not accepting creation of new Windows Azure SQL Database servers at this time."
cannot create sql server: sql.ServersCreateOrUpdateFuture#Result: Polling failure: StatusCode=200 -- Original Error: Code="RegionDoesNotAllowProvisioning" Message="Location 'East US 2' is not accepting creation of new Windows Azure SQL Database servers at this time."
```

**Expected behavior**
The environment running the tests sets test regions via local variables and the tests load it using the `config` client.

https://github.com/Azure/azure-service-operator/blob/94b83810299d88b34b2846e276f3bca39b841086/pkg/resourcemanager/eventhubs/suite_test.go#L66

**Comment by babbageclunk** [comment]
We won't fix this in v1. In v2 the test region is parameterised - it's still hard-coded, but in one place.
