### ISSUE TITLE
[OpenShiftSupport] Integrate operator with RedHat Operator Lifecycle Manager

### ISSUE THREAD

**Issue by jananivMS** [Azure/azure-service-operator#613]
OLM provides support for operator updates and makes operator lifecycle management easier.
[Link](https://github.com/operator-framework/operator-lifecycle-manager/blob/master/doc/install/install.md)

**Done criteria **
This is the "done" criteria for this task

- [ ] Azure Service Operator can be managed using the Operator Lifecycle Manager

**Comment by sakthi-vetrivel** [comment]
This has been completed.
