### ISSUE TITLE
Task: Investigate how to move update code to generic controller

### ISSUE THREAD

**Issue by cnadolny** [Azure/azure-service-operator#633]
Currently, update will be implemented at the resource level within Keyvault. Investigation work needs to be done to generically do the object hashing within the generic controller, and storing it within Status. Investigation should also be made to see if the Get call check can be removed from the resource level, and instead replaced by checking the object hash + timestamp. 

**Done criteria **
This is the "done" criteria for this task

- [ ] Hashing can be done generically rather than at resource level

**User story reference***

#<issue number of the user story that this task accrues to>

**Comment by matthchr** [comment]
Closing as this is no longer applicable.
