### ISSUE TITLE
Task: Make controller tests consistent

### ISSUE THREAD

**Issue by jananivMS** [Azure/azure-service-operator#677]
Currently the tests aren't consistent in terms of the helpers they use to reduce redundant code, what the test etc. This task tracks making sure all the controller tests look consistent.

Also look at issue #528 (this should be fixed by using EnsureDelete)

**Done criteria **
This is the "done" criteria for this task

- [x] All tests that can use EnsureInstance() and EnsureDelete() helpers should use this (addressed in PR #971)
- [ ] All tests for controllers that write secrets should test that the secret exists after successful creation of the resource
- [ ] Ensure tests do not ignore the errors from Get or Create Call. If this is ignored, we may get a value that is nil and cause panic references

**Comment by matthchr** [comment]
This has mostly been done
