### ISSUE TITLE
Bug: Telem submits extra data when superfluous reconciliations happen

### ISSUE THREAD

**Issue by frodopwns** [Azure/azure-service-operator#706]
**Describe the bug**
Whenever we update the status of a resource, it causes a reconciliation. What this means is that the telemetry will send the provisioning time an additional time for each extra reconciliation.

**To Reproduce**

- Check out the telem pr (or master if it is merged at this point)
- deploy a SQLSERver
- go to localhost:8080/metrics and see how many items are in the sqlserver execution time bucket...should be 1 but there are actually 2

**Expected behavior**
telem client ignores superfluous reconciliations

This should be easily fixable once the hash work from #631

**Comment by sakthi-vetrivel** [comment]
Validate that we're using status subresources on our side before closing this issue.

**Comment by Porges** [comment]
This issue is specific to v1, which is now in maintenance mode.
