### ISSUE TITLE
Task:  Investigate ways to start storing metrics about service provisioning times

### ISSUE THREAD

**Issue by frodopwns** [Azure/azure-service-operator#710]
We now have the functionality to track total provisioning time for services we operate. To make this useful we will need to start saving the metrics from our pipeline runs and storing them somewhere. Normally users would set up their own prometheus server or scrape the metrics an dpush them somewhere else. For us to use this data we will need a persistent cluster scraping the metrics via prometheus or we will need another way...

**Done criteria **
- [ ] The ASO project is storing historical provisioning metrics, using the pipeline run data

Note: one option that strikes me as feasible is to scrape /metrics at teh end of testing before teardown and push the metrics to appinsights.

**Comment by matthchr** [comment]
Closing this in favor of the more generic #1387
