### ISSUE TITLE
Bug: Deployment of service operator on Azure China failure due to image gcr.io/kubebuilder/kube-rbac-proxy:v0.4.0 cannot be pulled.

### ISSUE THREAD

**Issue by buhongw7583c** [Azure/azure-service-operator#715]
**Describe the bug**
Deployment of service operator failure due to image gcr.io/kubebuilder/kube-rbac-proxy:v0.4.0 cannot be pulled. 

**Done Criteria**
- [ ] Find an image in MCR or a repo that can be accessed from China

**To Reproduce**
-- Use Azure China environment to deploy the service operator. 
-- Follow the deploy.md. 
-- High probability (90%) you will encounter the error
`
 'issue: Failed to pull image "gcr.io/kubebuilder/kube-rbac-proxy:v0.4.0": rpc error: code = Unknown desc = Error response from daemon: Get https://gcr.io/v2/: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)'
`

**Expected behavior**
Download image from gcr.io/* is highly likely to fail in Azure China as the China firewall issue. Better relocate the image to other docker hub or maybe kubebuilder should have other docker hub without the 'gcr.io' prefix. 

**Additional context**

The image is required from config/default/manager_auth_proxy_patch.yaml.

**Comment by rguptar** [comment]
@matthchr, now that we have MCR, can `gcr.io/kubebuilder/kube-rbac-proxy` be added there?

**Comment by matthchr** [comment]
@rguptar - possibly? Can you open a new issue and link to this existing issue, as well as explain the scenario? Is the main issue just the timeouts mentioned above or are there other problems as well?
