### ISSUE TITLE
Bug: Changing tags doesn't update the resource in Azure

### ISSUE THREAD

**Issue by jpflueger** [Azure/azure-service-operator#870]
**Describe the bug**
If I apply a spec like config/samples/azure_v1alpha1_azuresqlserveranddb.yaml and then add a tag and re-apply it the labels are not updated as tags in Azure.

**To Reproduce**
1. Apply config/samples/azure_v1alpha1_azuresqlserveranddb.yaml
2. Add a label to the spec
3. Re-apply config/samples/azure_v1alpha1_azuresqlserveranddb.yaml 
4. Check the tags in Azure portal and see that they haven't changed

**Expected behavior**
An update to labels should propagate to Azure even if there are no other 

**Additional context**
Maybe adjust helpers.Hash256 to take in the labels so the SpecHash changes when the labels do.

**Comment by matthchr** [comment]
Closing this in favor of #1366
