### ISSUE TITLE
Task: refactor sql user secret formatting

### ISSUE THREAD

**Issue by frodopwns** [Azure/azure-service-operator#887]
Any secret formatting that exists for Keyvault should also exist for kube. The Operators should not know the type of secret store being used.

The secret formatting is also a bit cumbersome and messy for the Ensure method. It should be pushed into its own function and called from Ensure.

The flatten option should be removed from the Keyvault client and the sql user Ensure method should instead create a list of secrets that get sent to the secret client. Feel free to add methods to the secret client for creating multiple secrets or just call the existing methods in a loop from the operator.

**Done criteria**
- no conditional functionality based on type of secret store in sql user operator
- function or functions for creating the formatted secrets
- no magical implicit functionality in Upsert...do that elsewhere

**Comment by matthchr** [comment]
Related to #1471.

**Comment by matthchr** [comment]
Closing this in favor of #1471.
