### ISSUE TITLE
Bug: Something keeps updating the content of 'config/default/manager_image_patch.yaml' 

### ISSUE THREAD

**Issue by huangpf** [Azure/azure-service-operator#892]
**Describe the bug**
Every time I rebuild the container and run tests, something in the process will update the content of 'config/default/manager_image_patch.yaml':

Path	Filename	Extension	Status	Lines added	Lines removed	Last Modified	Size
config/default/manager_image_patch.yaml	manager_image_patch.yaml	.yaml	Modified	1	1	4/7/2020 10:48:09 AM	1.48 KB

The change content is from:
      - image: controller:latest
To:
      - image: IMAGE_URL

**To Reproduce**
Rebuild the container and re-run some tests.

**Expected behavior**
The file shouldn't change with unnecessary content.

**Screenshots**
N/A

**Additional context**
N/A

**Comment by jananivMS** [comment]
This usually happens when you do a make deploy to replace the controller image. Shouldnt be an issue for the project itself.
