### ISSUE TITLE
Task: Refactor Key Vault Ensure 

### ISSUE THREAD

**Issue by cnadolny** [Azure/azure-service-operator#927]
Refactor Key Vault Ensure to make provisioning flow consistent across all operators.

Remove provisioned/provisioning variables, and catch the success in the Get Vault check, which would return true, nil on success. Otherwise, Ensure should return false, nil.

Refer back to #743 for more details.

**Done criteria**
This is the "done" criteria for this task

- [ ] Key Vault is refactored with above flow.

**Comment by matthchr** [comment]
Closing this as not applicable now
