### ISSUE TITLE
Task: Add cert-manager as dependency to Helm Chart

### ISSUE THREAD

**Issue by cnadolny** [Azure/azure-service-operator#961]
Currently, we require the user to run a few commands prior to installing the Helm Chart, to install cert-manager dependencies.
https://github.com/Azure/azure-service-operator/tree/master/charts/azure-service-operator

It's not trivial to add cert-manager as a dependency to the Helm Chart, as even in the install instructions it requires manual input from the user prior to installing with Helm:
https://cert-manager.io/docs/installation/kubernetes/#installing-with-helm

Investigate if there is a way to automate this installation via some sort of pre install hooks or other method.

**Done criteria**
This is the "done" criteria for this task

- [ ] Investigate if possible to add cert-manager installation as automated process to Helm Chart

**User story reference**

#<issue number of the user story that this task accrues to>

**Comment by matthchr** [comment]
Quoting @super-harsh 

> cert-manager doesn't allow namespace override and limitation/feature for helm-v3 is that we can't specify a different namespace for sub-charts and namespaces get overridden by .Release.Namespace

See #2094. Closing this issue given the lack of upstream support
