### ISSUE TITLE
Task: kustomize - well-defined vars that were never replaced

### ISSUE THREAD

**Issue by cnadolny** [Azure/azure-service-operator#988]
When running kustomize build in makefile via make deploy or other commands, this is the output of kustomize build:
```
well-defined vars that were never replaced: SERVICE_NAME,SERVICE_NAMESPACE
```

The command runs fine, but we should investigate if these are unneeded variables, and either fix or remove them.

**Done criteria**
This is the "done" criteria for this task

- [ ] Fix or remove above variables from kustomization file

**Comment by jananivMS** [comment]
This was fixed with Erin's change for versioning
