### ISSUE TITLE
Task: Store Helm Chart in Azure Container Registry

### ISSUE THREAD

**Issue by cnadolny** [Azure/azure-service-operator#991]
Right now, Helm Charts are stored as a tar file in Github. While this is a good short term solution, it's becoming difficult to sync changes between the project and Helm Charts, as they need to be manually updated every time a CRD is removed or added.

Storing the Helm Chart in an ACR repository will work well with the DevOps pipeline, and allow us to update the chart automatically each time a new change is pushed.

https://docs.microsoft.com/en-us/azure/container-registry/container-registry-helm-repos

**Done criteria**
This is the "done" criteria for this task

- [x] ACR is created to store Helm Chart
- [x] Pipeline is updated to push new chart tar file to ACR 
- [x] Helm Chart documentation is updated to have user pull from ACR repository rather than Github
- [ ] Helm Chart tar file is removed from Github

**User story reference**

#<issue number of the user story that this task accrues to>

**Comment by bergerx** [comment]
Please also factor in the fact that ACR cant act as a conventional "helm repo" as in `helm repo add <repo-name> ... + helm install <release-name> <repo-name>/<chart-name>`. Instead one has to follow `helm chart export ... + helm install <release-name> <exported-folder>` procedure. This second flow, which ACR expect users to follow as a helm repo integration, is not supported by most (if not all) automation tools out there (helmsman, helmfile, argo/flux, harness, etc.).

I hope the place where the chart is currently stored (`helm repo add azureserviceoperator https://raw.githubusercontent.com/Azure/azure-service-operator/master/charts`) will be deprecated as part of this.

**Comment by matthchr** [comment]
We should look into this, but as @bergerx mentioned the actual Helm experience with ACR is not as great, so we may not do it, especially if we don't see many other Helm charts following this pattern. Goal is to do what the community expects.

**Comment by matthchr** [comment]
Closing this as we've decided that it doesn't make sense to do it
