### ISSUE TITLE
Task: Create static tag or add logic to continually update default Helm Chart image

### ISSUE THREAD

**Issue by cnadolny** [Azure/azure-service-operator#993]
Currently, images from MCR are being tagged with each build number. 

Logic needs to be added to the pipeline to either 
* update the values.yaml file within the Helm Chart before we package it and push to ACR, to ensure that install of the Helm Chart will be using latest changes
* or continue tagging images with the build number, but also create a second static tag (something like latest-helm?) that we can insert into the values.yaml file, and do not have to keep continually updating as long as we continue retagging all new images with the static tag.

Related to #938

**Done criteria**
This is the "done" criteria for this task

- [ ] Pick one of the above two approaches and implement
- [ ] Docs are updated

**User story reference**

#<issue number of the user story that this task accrues to>

**Comment by matthchr** [comment]
@babbageclunk has fixed this in #1345.
