### ISSUE TITLE
Bug: Helm Install warning message "skipping unknown hook"

### ISSUE THREAD

**Issue by cnadolny** [Azure/azure-service-operator#994]
**Describe the bug**
When installing the Helm Chart hosted on Github, installation succeeds but we see these warning messages:
```
Release "aso" does not exist. Installing it now.
manifest_sorter.go:175: info: skipping unknown hook: "crd-install"
manifest_sorter.go:175: info: skipping unknown hook: "crd-install"
manifest_sorter.go:175: info: skipping unknown hook: "crd-install"
manifest_sorter.go:175: info: skipping unknown hook: "crd-install"
NAME: aso
LAST DEPLOYED: Thu Apr 23 11:58:49 2020
NAMESPACE: default
STATUS: deployed
REVISION: 1
TEST SUITE: None
```

We should fix the chart so that it no longer emits those messages upon installing.

**To Reproduce**
<Fill in the steps>

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by jananivMS** [comment]
This is expected with Helm3 not processing CRDs
